### PR TITLE
Useless escape in charset warning

### PR DESCRIPTION
**Pull request by KvanTTT**
Fixes https://github.com/antlr/antlr4/issues/1537.

### CODE REVIEW

**Comment by KvanTTT** [comment]
@parrt don't merge it until I check it on our grammars.

**Comment by parrt** [comment]
@KvanTTT seems like a major bit of surgery when I was kind of expecting ERROR->WARNING on a few things.

**Comment by KvanTTT** [comment]
I don't know a simple way to fix it. `CharSupport` does not have a `public final Grammar g;` property, therefore it's impossible to throw errors and warnings via `CharSupport`.

**Comment by KvanTTT** [comment]
I fixed all discovered errors and check ANTLR 4.7 on our grammars repository.
Also I fixed all warnings in grammars: https://github.com/antlr/grammars-v4/pull/566

So, this PR is ready to merge for now.

**Comment by parrt** [comment]
I still don't think I can agree with this PR. For one it is altering @bhamiltoncx 's new unicode stuff. what is the `intChar` in:

```java
int t1 = CharSupport.getCharValueFromGrammarCharLiteral(a.getText()).intChar
```

for example? that already is an int.  I think we just need to convert some errors to warnings. nothing else. Maybe I'll respond to #1537 myself to show what I mean.

**Comment by parrt** [comment]
See https://github.com/antlr/antlr4/pull/1709

**Comment by parrt** [comment]
It's ok to just give a warning:

```
A : [\[] ;
B : [\v] ;
C : [\j\k\l] ;
```

gets

```
warning(156): T.g:5:4: invalid escape sequence
warning(156): T.g:6:4: invalid escape sequence
warning(156): T.g:7:4: invalid escape sequence
```

**Comment by KvanTTT** [comment]
I created a new pull request with my improvements: https://github.com/antlr/antlr4/pull/1715
`'\"'` string literal also should throw an "invalid escape sequence" warning.

Disadvantage of warning: such char sets and string literals `[\u24\uA2]` will be treated as warnings despite of they are errors clearly.

**Comment by parrt** [comment]
oh right. we should have **unnecessary** vs **invalid** escape. First one is warning, second is error. Does that sound right?

**Comment by KvanTTT** [comment]
Yes, you are right.

**Comment by parrt** [comment]
Your new PR is probably good enough. :)

**Comment by KvanTTT** [comment]
Just now found another issue with lexer (during testing our grammars repository) :( Will fix it ASAP.

**Comment by KvanTTT** [comment]
It's ok! Just a error in grammar [UCBLogo.g4]  :)
We should escape a first minus sign in this rule:
```
NAME
 : ~[-+*/=<> \t\r\n[\]()":{}] ( ~[-+*/=<> \t\r\n[\](){}] | LINE_CONTINUATION | '\\' [-+*/=<> \t\r\n[\]();~{}] )*
 ;
```

But I want to improve error messages anyway. Now they are too confused for such rule:
```
warning(180): UCBLogo.g4:699:4: chars "42" used multiple times in set [-+*/=<> \t\r\n[\]()":{}]
```

**Comment by KvanTTT** [comment]
> oh right. we should have unnecessary vs invalid escape. First one is warning, second is error. Does that sound right?

What do you think about moving grammar instance `Grammar g` to `CharSupport.java` for handling errors and warnings there?

**Comment by parrt** [comment]
Can't. Grammar is not in runtime.

**Comment by parrt** [comment]
Those are just static support functions. pass in g if you need I guess. I'd prefer we have a central place to check all this. i was uncomfortable with your change to ATNOptimizer to check ranges so...

**Comment by KvanTTT** [comment]
> i was uncomfortable with your change to ATNOptimizer to check ranges so...

Actually there is no another place where some kind of ranges can be checked.

**Comment by parrt** [comment]
I was thinking maybe a separate checking phase over the ATN but no biggie.

**Pull request closed without merging**
