### PR TITLE
C# runtime clearing up

### PR DESCRIPTION
**Pull request by KvanTTT**

### CODE REVIEW

**Comment by ericvergnaud** [comment]
@KvanTTT I'm theoretically supportive but can't review so many changes in one PR

**Comment by KvanTTT** [comment]
To simplify, I can split PR on two ones. The first one will mostly include manual improvements, the second one will include improvements made by IDE (Rider).

**Comment by ericvergnaud** [comment]
Sorry to be a pain in the ass, but I think 1 PR per commit would be the right granularity

**Comment by KvanTTT** [comment]
By the way, every PR can be reviewed commit by commit instead of full change set: 
Screenshot from 2022-09-02 17-08-28

**Comment by ericvergnaud** [comment]
Sure, but I can only approve the full PR, correct ?

**Comment by KvanTTT** [comment]
> Sure, but I can only approve the full PR, correct ?

Yes.

**Comment by KvanTTT** [comment]
I'm closing in favor of https://github.com/antlr/antlr4/pull/3861

**Pull request closed without merging**
