### PR TITLE
Avoid double deletion when NoViableAltException is thrown

### PR DESCRIPTION
**Pull request by gedimitr**
When ownership of the configurations set is passed to a NoViableAltException,
it gets deleted more than once if the exception happens to get copied.

The exception copy can happen due to `std::make_exception_ptr` being invoked in
`DefaultErrorStrategy::reportNoViableAlternative`

### CODE REVIEW

**Comment by sannysanoff** [comment]
Voting on this.

**Comment by mike-lischke** [comment]
@gedimitr In order to have your patch accepted you have to fix all merge conflicts first.

**Comment by gedimitr** [comment]
@mike-lischke merge conflicts have been fixed.

**Comment by mike-lischke** [comment]
@parrt This patch is ready to merge. C++ change only.

**Pull request merged**
