### PR TITLE
added Token.DEFAULT_CHANNEL and Token.HIDDEN_CHANNEL

### PR DESCRIPTION
**Pull request by RobEin**
issue #4110:
https://github.com/antlr/antlr4/issues/4110#issuecomment-1898214382

### CODE REVIEW

**Comment by RobEin** [comment]
added Token.DEFAULT_CHANNEL and Token.HIDDEN_CHANNEL to TypeScript runtime

**Comment by ericvergnaud** [comment]
Hi, thanks for this. Can you fix the DCO issue: https://github.com/antlr/antlr4/pull/4516/checks?check_run_id=20672759783

**Comment by RobEin** [comment]
Sorry, 
DCO issue is fixed.

**Comment by ericvergnaud** [comment]
Thanks!

**Pull request merged**
