### PR TITLE
Fixes Markdown table in targets.md

### PR DESCRIPTION
**Pull request by reitzig**

### CODE REVIEW

**Comment by parrt** [comment]
hi. for cleanliness, can you add yourself to contributors.txt?

**Comment by reitzig** [comment]
Oh dear, that's quite the overkill for a little Markdown fix. XD

**Comment by parrt** [comment]
indeed. Sorry about that but people are very happy when my license is extremely clean. As doc changes could include code, I have to be pedantic!

**Comment by reitzig** [comment]
I understand, no harm done. :) 
(And since we are already writing: thanks for all the work!)

**Comment by parrt** [comment]
at your service. thanks!

**Pull request merged**
