### PR TITLE
Fix for redeclared error is generated Go code. 

### PR DESCRIPTION
**Pull request by wxio**
@parrt @pboyer 
Clean pull request for redeclared var error.

Create block so _x and _m var are created in a local scope.

### CODE REVIEW

**Comment by millergarym** [comment]
@parrt Question about pull request etiquette. Should these changes have been separate pull requests?

**Comment by sridharxp** [comment]
Checking...Skipped some tests  (5+7) in ` TestPerformance` and `TestVisitors` Other tests passed ok.
After inclusion of `GetTokenSourceCharStreamPair` method there are no failures which surfaced after recent changes in Go.stg

**Comment by parrt** [comment]
@antlr/antlr-targets just a note that I'm out of action til this coming weekend

**Comment by pboyer** [comment]
Hey folks, 

Generally, yes, I would prefer to see this as separate PR's. But, their impact should each be fairly limited and there are only two. So, we'll let you get away with it this time. :)

@millergarym We need your changes in contributors.txt to merge this.

**Comment by millergarym** [comment]
@pboyer my pull request for the contributor.txt change containing my details has already been accepted by Terrance.

**Comment by pboyer** [comment]
@millergarym Sorry I didn't see that! Thank you so much!

**Pull request merged**
