### PR TITLE
Tweak Repo to use SwiftPackageManager.

### PR DESCRIPTION
**Pull request by hanjoes**
This PR is meant for SPM integration. This will make future runtime test/build easier/faster and has better compatibility on Linux platforms.

Also this PR contains a fix for #1584 w/ unit tests.

### CODE REVIEW

**Comment by parrt** [comment]
@hanjoes howdy! looks like a big change is it really just moving files around?

**Comment by hanjoes** [comment]
yep! The purpose is to integrate Swift Package Manager which works based off some conventions.

**Comment by parrt** [comment]
@janyou any issues with this?

**Comment by hanjoes** [comment]
btw, i tweaked the old xcodeproj to work with the new directory structure. So everything should work as before with added SPM integration.

**Pull request merged**
