### PR TITLE
Fix wrong include path of antlr4cpp runtime in cmake/ExternalAntlr4Cpp.cmake

### PR DESCRIPTION
**Pull request by mshockwave**
The include path variable exported by `cmake/ExternalAntlr4Cpp.cmake` doesn't follow up the latest update of the include folder hierarchy. Which may raise compile error on generated cpp/header files since they try to `#include "antlr4-runtime.h"` but the correct path is `#include "antlr4-runtime/antlr4-runtime.h"`.
I modify `ExternalAntlr4Cpp.cmake` so that we don't need to touch the generation of grammar cpp/header files.

### CODE REVIEW

**Comment by parrt** [comment]
@mike-lischke Is this correct?

**Comment by JPGygax68** [comment]
What is the fix for those not using `ExternalAntlr4Cpp.cmake`? Is there no better way than to find the absolute path of the runtime headers and add it to the compiler's include path?

**Comment by mike-lischke** [comment]
That `ExternalAntlr4Cpp.cmake` is just an additional make file for people who prefer to use this approach. There's another CmakeLists.txt file for building the runtime in a more straight forward way, which should work as is.

**Comment by JPGygax68** [comment]
Thank you @mike-lischke. My issue however is not with building the runtime, but with the include statement that antlr4 produces:
```
// Generated from Scene.g4 by ANTLR 4.7.1
#pragma once
#include "antlr4-runtime.h"
...
```
The file `antlr4-runtime.h` in turn includes a lot of header files, some of which having names that are at high risk of clashing with include files from other libraries (e.g. `Token.h`). 

Is there any way to make antlr4 generate `#include <antlr4-runtime/antlr4-runtime.h>` instead?

**Comment by mike-lischke** [comment]
That include is generated via templates - a pretty complicated setup. Instead of forcing a specific include path there (and possibly produce problems in other environments) it's better to control the inclusion behavior with project header search paths (and put all the parsing code into an own library). That worked well for me even in cases where headers clash (e.g. Python also has a Token.h file IIRC).

**Comment by JPGygax68** [comment]
Thanks! This is what I ended up doing, and indeed it works ok. The preprocessor inclusion rules will make sure that `antlr4-runtime.h` will find its own sub-headers first.

Still, I was wondering why not more people were complaining about this, and found the answer when I got the usual C++ linker errors: because this is C++ and not C, the libraries must match perfectly (release/debug, static or dll runtime - under Windows), so you have to find and set the specific library path anyway.

**Comment by Ralith** [comment]
It's very confusing for the runtime to install the headers in a place the generated source files won't find. @JPGygax68's suggestion to use `#include <antlr4-runtime/antlr4-runtime.h>` instead makes a great deal of sense to me. It's not forcing a specific include path; it's referencing the location relative to global include paths that matches the one installed to by default. Surely if any environment should work out of the box, it should be the one produced by installing the runtime normally?

**Pull request merged**
