### PR TITLE
Create functionality to get all possible parse trees for ambiguous input.

### LINKED ISSUE #807: Allow parsing decision override for (decision, input index) in parsers
This would allow all ambiguous alts for any decision to be attempted for debugging purposes.

### PR DESCRIPTION
**Pull request by parrt**
Fixes #807. Currently, the parser will return a single parse tree for ambiguous input. It will, however, notify listeners upon ambiguous input. There just isn't a way to get the other interpretations for those ambiguity events. I have added a mechanism to override a specific decision at a specific input position to choose a specific alternative. This allows me to restart the entire parse to get different interpretation. Currently the implementation only allows a single decision override.

Everything about this feature gets down to a single new static method `Parser. getAmbiguousParseTrees()`, which allows development tools to show all interpretations of ambiguous phrases. The trees returned are the smallest trees that completely cover the ambiguous input phrase. They do not return a pointer to the entire ambiguous tree.

### CODE REVIEW

**Comment by marcospassos** [comment]
@parrt what happened to this feature? I cannot find it on 4.5.3

**Comment by marcospassos** [comment]
Such an amazing job, very useful for debugging/instrumenting purposes. Is there any change to merge it into master again?

**Comment by parrt** [comment]
In fact I just updated them to be more robust. See class GrammarParserInterpreter and methods getAllPossibleParseTrees, getLookaheadParseTrees

**Comment by marcospassos** [comment]
Oh, I see. I could not find it because the method name changed from`getAmbiguousParseTrees` to `getAllPossibleParseTrees`. Thanks, @parrt!

**Comment by parrt** [comment]
oh crap.  I shouldn't change the name. hmm... it looks like the name has always been getAllPossibleParseTrees.  but then again I see something in the swift target that has that name, commented out and not implemented. Hmm...6/17/15 is when I added it. Anyway it's all good now. enjoy.

**Pull request merged**
