### PR TITLE
[Go] Check bounds on operands before indexing in equals

### PR DESCRIPTION
**Pull request by gordon-klotho**
The following javascript was failing to parse:

```javascript
let a = 1;
```

Was giving the following panic:
<details>
<summary>panic</summary>

```
panic: runtime error: index out of range [2] with length 2                                                                                                                                                                                                                                                                                                                                                                                                                                              goroutine 1 [running]:                                                                                                                                                                                                                              github.com/antlr/antlr4/runtime/Go/antlr.(*AND).equals(0xc00034f818, {0x5d5c00, 0xc00034f8d8})                                                                                                                                                              /home/gordon/.gvm/pkgsets/go1.17/global/pkg/mod/github.com/antlr/antlr4/runtime/!go/antlr@v0.0.0-20211101200231-0802afb9c160/semantic_context.go:245 +0x10a                                                                                 github.com/antlr/antlr4/runtime/Go/antlr.equalATNConfigs({0x5de600, 0xc0003705f0}, {0x5de600, 0xc000384be0})                                                                                                                                                /home/gordon/.gvm/pkgsets/go1.17/global/pkg/mod/github.com/antlr/antlr4/runtime/!go/antlr@v0.0.0-20211101200231-0802afb9c160/atn_config_set.go:406 +0x195                                                                                   github.com/antlr/antlr4/runtime/Go/antlr.(*Array2DHashSet).innerAdd(0xc000360d20, {0x5de600, 0xc000384be0})                                                                                                                                                 /home/gordon/.gvm/pkgsets/go1.17/global/pkg/mod/github.com/antlr/antlr4/runtime/!go/antlr@v0.0.0-20211101200231-0802afb9c160/utils_set.go:174 +0x1cf                                                                                        github.com/antlr/antlr4/runtime/Go/antlr.(*Array2DHashSet).Add(0x0, {0x5de600, 0xc000384be0})                                                                                                                                                               /home/gordon/.gvm/pkgsets/go1.17/global/pkg/mod/github.com/antlr/antlr4/runtime/!go/antlr@v0.0.0-20211101200231-0802afb9c160/utils_set.go:72 +0x50                                                                                          github.com/antlr/antlr4/runtime/Go/antlr.(*BaseATNConfigSet).Add(0xc000360d70, {0x65a088, 0xc000384be0}, 0x0)                                                                                                                                               /home/gordon/.gvm/pkgsets/go1.17/global/pkg/mod/github.com/antlr/antlr4/runtime/!go/antlr@v0.0.0-20211101200231-0802afb9c160/atn_config_set.go:129 +0xf2                                                                                    github.com/antlr/antlr4/runtime/Go/antlr.(*ParserATNSimulator).closureWork(0xc0001282a0, {0x65a088, 0xc000384be0}, {0x65f7e0, 0xc000360d70}, {0x6590c0, 0xc000360eb0}, 0x0, 0x4b, 0xfffffffffffffff7, ...)
        /home/gordon/.gvm/pkgsets/go1.17/global/pkg/mod/github.com/antlr/antlr4/runtime/!go/antlr@v0.0.0-20211101200231-0802afb9c160/parser_atn_simulator.go:1036 +0xbd                                                                             github.com/antlr/antlr4/runtime/Go/antlr.(*ParserATNSimulator).closureCheckingStopState(0xc0001282a0, {0x65a088, 0xc000384be0}, {0x65f7e0, 0xc000360d70}, {0x6590c0, 0xc000360eb0}, 0x50, 0x0, 0xfffffffffffffff7, ...)                                     /home/gordon/.gvm/pkgsets/go1.17/global/pkg/mod/github.com/antlr/antlr4/runtime/!go/antlr@v0.0.0-20211101200231-0802afb9c160/parser_atn_simulator.go:1028 +0x359                                                                            github.com/antlr/antlr4/runtime/Go/antlr.(*ParserATNSimulator).closureWork(0xc0001282a0, {0x65a088, 0xc000384b90}, {0x65f7e0, 0xc000360d70}, {0x6590c0, 0xc000360eb0}, 0x0, 0x4b, 0xfffffffffffffff7, ...)
        /home/gordon/.gvm/pkgsets/go1.17/global/pkg/mod/github.com/antlr/antlr4/runtime/!go/antlr@v0.0.0-20211101200231-0802afb9c160/parser_atn_simulator.go:1089 +0x519                                                                            github.com/antlr/antlr4/runtime/Go/antlr.(*ParserATNSimulator).closureCheckingStopState(0xc0001282a0, {0x65a088, 0xc000384b90}, {0x65f7e0, 0xc000360d70}, {0x6590c0, 0xc000360eb0}, 0x8, 0x0, 0xfffffffffffffff7, ...)                                      /home/gordon/.gvm/pkgsets/go1.17/global/pkg/mod/github.com/antlr/antlr4/runtime/!go/antlr@v0.0.0-20211101200231-0802afb9c160/parser_atn_simulator.go:1028 +0x359                                                                            github.com/antlr/antlr4/runtime/Go/antlr.(*ParserATNSimulator).closureWork(0xc0001282a0, {0x65a088, 0xc000384b40}, {0x65f7e0, 0xc000360d70}, {0x6590c0, 0xc000360eb0}, 0x0, 0x0, 0xfffffffffffffff7, ...)                                                   /home/gordon/.gvm/pkgsets/go1.17/global/pkg/mod/github.com/antlr/antlr4/runtime/!go/antlr@v0.0.0-20211101200231-0802afb9c160/parser_atn_simulator.go:1089 +0x519                                                                            github.com/antlr/antlr4/runtime/Go/antlr.(*ParserATNSimulator).closureCheckingStopState(0xc0001282a0, {0x65a088, 0xc000384b40}, {0x65f7e0, 0xc000360d70}, {0x6590c0, 0xc000360eb0}, 0x50, 0x0, 0xfffffffffffffff7, ...)                                     /home/gordon/.gvm/pkgsets/go1.17/global/pkg/mod/github.com/antlr/antlr4/runtime/!go/antlr@v0.0.0-20211101200231-0802afb9c160/parser_atn_simulator.go:1028 +0x359                                                                            github.com/antlr/antlr4/runtime/Go/antlr.(*ParserATNSimulator).closureWork(0xc0001282a0, {0x65a088, 0xc000384af0}, {0x65f7e0, 0xc000360d70}, {0x6590c0, 0xc000360eb0}, 0x0, 0x4a, 0xfffffffffffffff7, ...)                                                  /home/gordon/.gvm/pkgsets/go1.17/global/pkg/mod/github.com/antlr/antlr4/runtime/!go/antlr@v0.0.0-20211101200231-0802afb9c160/parser_atn_simulator.go:1089 +0x519                                                                            github.com/antlr/antlr4/runtime/Go/antlr.(*ParserATNSimulator).closureCheckingStopState(0xc0001282a0, {0x65a088, 0xc000384af0}, {0x65f7e0, 0xc000360d70}, {0x6590c0, 0xc000360eb0}, 0x50, 0x0, 0xfffffffffffffff7, ...)                                     /home/gordon/.gvm/pkgsets/go1.17/global/pkg/mod/github.com/antlr/antlr4/runtime/!go/antlr@v0.0.0-20211101200231-0802afb9c160/parser_atn_simulator.go:1028 +0x359                                                                            github.com/antlr/antlr4/runtime/Go/antlr.(*ParserATNSimulator).closureWork(0xc0001282a0, {0x65a088, 0xc000384aa0}, {0x65f7e0, 0xc000360d70}, {0x6590c0, 0xc000360eb0}, 0x0, 0x4a, 0xfffffffffffffff7, ...)
        /home/gordon/.gvm/pkgsets/go1.17/global/pkg/mod/github.com/antlr/antlr4/runtime/!go/antlr@v0.0.0-20211101200231-0802afb9c160/parser_atn_simulator.go:1089 +0x519
github.com/antlr/antlr4/runtime/Go/antlr.(*ParserATNSimulator).closureCheckingStopState(0xc0001282a0, {0x65a088, 0xc000384aa0}, {0x65f7e0, 0xc000360d70}, {0x6590c0, 0xc000360eb0}, 0x8, 0x0, 0xfffffffffffffff7, ...)
        /home/gordon/.gvm/pkgsets/go1.17/global/pkg/mod/github.com/antlr/antlr4/runtime/!go/antlr@v0.0.0-20211101200231-0802afb9c160/parser_atn_simulator.go:1028 +0x359
github.com/antlr/antlr4/runtime/Go/antlr.(*ParserATNSimulator).closureWork(0xc0001282a0, {0x65a088, 0xc000384a50}, {0x65f7e0, 0xc000360d70}, {0x6590c0, 0xc000360eb0}, 0x0, 0x0, 0xfffffffffffffff7, ...)
        /home/gordon/.gvm/pkgsets/go1.17/global/pkg/mod/github.com/antlr/antlr4/runtime/!go/antlr@v0.0.0-20211101200231-0802afb9c160/parser_atn_simulator.go:1089 +0x519
github.com/antlr/antlr4/runtime/Go/antlr.(*ParserATNSimulator).closureCheckingStopState(0xc0001282a0, {0x65a088, 0xc000384a50}, {0x65f7e0, 0xc000360d70}, {0x6590c0, 0xc000360eb0}, 0x7, 0x0, 0xfffffffffffffff7, ...)
        /home/gordon/.gvm/pkgsets/go1.17/global/pkg/mod/github.com/antlr/antlr4/runtime/!go/antlr@v0.0.0-20211101200231-0802afb9c160/parser_atn_simulator.go:1028 +0x359
github.com/antlr/antlr4/runtime/Go/antlr.(*ParserATNSimulator).closureWork(0xc0001282a0, {0x65a088, 0xc000384a00}, {0x65f7e0, 0xc000360d70}, {0x6590c0, 0xc000360eb0}, 0x0, 0x0, 0xfffffffffffffff7, ...)
        /home/gordon/.gvm/pkgsets/go1.17/global/pkg/mod/github.com/antlr/antlr4/runtime/!go/antlr@v0.0.0-20211101200231-0802afb9c160/parser_atn_simulator.go:1089 +0x519

<and so on>
```
</details>

The stack trace was being hidden by the recovery code [1] in the generated parser, so I removed it to get the underlying cause. 


[1] Recovery code:
```go
	defer func() {
		if err := recover(); err != nil {
			if v, ok := err.(antlr.RecognitionException); ok {
				localctx.SetException(v)
				p.GetErrorHandler().ReportError(p, v)
				p.GetErrorHandler().Recover(p, v)
			} else {
				panic(err) // <- this line changes the stack trace
			}
		}
	}()

```

### CODE REVIEW

**Comment by parrt** [comment]
I will have to leave this to the expertise of @jcking

**Comment by gordon-klotho** [comment]
I don't _think_ those CI failures have to do with this PR, but let me know if there's anything I need to address/fix and I'd be happy to.

**Comment by shawnzhesun** [comment]
I'm seeing the same error while parsing JavaScript. Saw a fix for this issue in https://github.com/antlr/antlr4/commit/923858d005d1aaf96b8dffde19f2b95eab16f9ad. Will it be merged to `dev`?

**Comment by gordon-klotho** [comment]
The merge conflicts became too much to resolve, so I abandoned this PR (hence the closing). I've switched to https://github.com/smacker/go-tree-sitter for my parsing needs. You're welcome to take over the fix, that commit is indeed the one that fixed it for me.

**Comment by parrt** [comment]
Ok,Sorry for the hassles.

**Pull request closed without merging**
