### PR TITLE
Add Go language target

### PR DESCRIPTION
**Pull request by pboyer**
### ANTLR4 Go target

This target has been production use for nearly a year now under constant load. This equates to about 1 billion runs on a non-trivial grammar.

Presently, this implementation matches pretty closely to the Java and JavaScript implementation. That said, it is not entirely idiomatic Go. Go doesn't really have classes. It panics instead of returning error values. This means it's easier for existing ANTLR users to switch, but some Go purists might be annoyed. I'm open to making this change.

**Contributors**: Almost all contributors have signed the CLA. I still need to track down 1 or 2. Worst case I'd need to rebase and re-add a few trivial changes.

**Test status:** All runtime tests pass for all languages. 

**Changes affecting all targets (new + old):** The changes here are very minor and reflected in the runtime tests.

**Merge status:** I've recently merged changes with no issue.

**Doc status:** I have not written up much documentation on usage. This is forthcoming.

### CODE REVIEW

**Comment by parrt** [comment]
It looks like some files in codegen were changed but diff is too big for viewing files changed. can you lemme know if they are major or minor changes so i don't have to pull to look?

**Comment by parrt** [comment]
I think many of the model changes are related to:

```
recognizerName = factory.getGrammar().getRecognizerName();
```

can you use <factory.grammar.recognizerName> in the templates instead? hmm...maybe not good idea as it exposes details of the model.

**Comment by pboyer** [comment]
@parrt When you say "codegen" I assume you mean: antlr4/tool/src/org/antlr/v4/codegen

Is that right?

**Comment by pboyer** [comment]
Assuming "yes" to the above question :): 

@willfaught Should be able to clarify, but the changes introduced related to `recognizerName` should be summarized in this PR: https://github.com/pboyer/antlr4/pull/29/ I don't think they should affect other targets, but instead are just propagating some additional info into the templates.

The other primary changes in that directory are: 

* The Go.stg generator template: https://github.com/pboyer/antlr4/blob/master/tool/resources/org/antlr/v4/tool/templates/codegen/Go/Go.stg
* The GoTarget implementation: 
https://github.com/pboyer/antlr4/blob/master/tool/src/org/antlr/v4/codegen/target/GoTarget.java

**Comment by pboyer** [comment]
@parrt Just a clarification, should I prepend all of the new source files with the BSD license?

**Comment by parrt** [comment]
Yep, codegen is all of the model stuff, which can affect template arguments. The introduction of new files should be no problem.  Per my other thread, I will find the commonality between your changes for this new property and Mike's. I will also look at the Swift target for the same.

Yep, introducing the BSD license. hmm... I'm sure I have not done it consistently and I should check to see if it's two or three clause BSD. ack. ok,  added an issue to fix later once all the targets are in. https://github.com/antlr/antlr4/issues/1322

**Comment by parrt** [comment]
BTW @pboyer what about StructDecl:

```
    @ModelElement public OrderedHashSet<Decl> tokenDecls = new OrderedHashSet<Decl>();
```

 what is the exact requirement here in terms of the generated output?

**Comment by parrt** [comment]
Ok, can you try `<parser.name>` and see if you get the right thing as recognizerName?  should be same.

**Comment by parrt** [comment]
To make it build on my mac, I needed to change the BaseTest:

```java
	private static void cacheGoRuntime(File tmpPackageDir) throws Exception {
		String goExecutable = locateGo();
		ProcessBuilder pb = new ProcessBuilder(goExecutable, "install", "-x");
```

i didn't fork as i'm worried about forking a fork with same name as my original fork of antlr4 ;)

**Comment by parrt** [comment]
Actually, if you can add me as colloborator on your fork, i can just push changes in prep for later. i have it testing/running on my box now.

**Comment by parrt** [comment]
Spent about an hour but can't see what you're doing with RuleActionFunction's isRuleContext. I think it's true ONLY when it's in a lexer. What specifically are you trying to distinguish?

**Comment by willfaught** [comment]
@parrt Sorry, it's been a while since I've looked at the code. Can you point to a file/line?

**Comment by parrt** [comment]
i'm making a branch and will push shortly :)

**Comment by pboyer** [comment]
You're now a collaborator on my fork.

**Comment by parrt** [comment]
ok, please check my changes so far in https://github.com/pboyer/antlr4/tree/reduce-model-changes

**Comment by parrt** [comment]
jetlag getting me. brain shutting down for the day...CA time. lemme know what you think of my tweaks in the branch.

**Comment by parrt** [comment]
@pboyer what about StructDecl:

    @ModelElement public OrderedHashSet<Decl> tokenDecls = new OrderedHashSet<Decl>();
what is the exact requirement here in terms of the generated output?

maybe you could email me so we can chat? skype maybe? I'm parrterence

**Comment by pboyer** [comment]
@parrt All your changes are merged into pboyer/antlr4:master and tests pass.

**Comment by parrt** [comment]
Life is good! Do i have green light to integrate into antlr/antlr4? Have you checked all committers?

**Comment by pboyer** [comment]
I believe so. The only other committers are @wjkohnen @willfaught and @runner-mei and they have all signed the CLA.

**Comment by willfaught** [comment]
Stellar work, @pboyer! Thanks so much for your hard work.

**Comment by jasonmoo** [comment]
Amazing! Thanks to all who contributed!

**Pull request merged**
