### PR TITLE
[Swift] reduce Optionals in APIs

### PR DESCRIPTION
**Pull request by Dante-Broggi**
This PR modifies public API and has several questions:
should `ParserRuleContext.removeLastChild` require it be not empty?
I think the change to `Parser._parseListeners` requires changes to code templates, but I couldn't get them to apply in local testing.

### CODE REVIEW

**Comment by parrt** [comment]
Looks like we get an error:

```
/private/var/folders/85/3yb73nr53qgf68tmtfby5s3c0000gp/T/BaseSwiftTest-main-1649088422626/testcase-1649088422654/Sources/testcase-1649088422654/TParser.swift:280:42: error: argument type 'Token?' does not conform to expected type 'Token'
```

**Comment by KvanTTT** [comment]
The error is still presented. Please run runtime tests before preparing pull request.

**Comment by Dante-Broggi** [comment]
I've been having problems running tests: even on a clean `dev` branch I get:
```text
~/antlr4/runtime/Swift/Tests/Antlr4Tests/gen/VisitorCalcParser.swift:393:38: error: value of type 'ATNDeserializer' has no member 'deserializeFromJson'
        static let _ATN = ATNDeserializer().deserializeFromJson(_serializedATN)
                          ~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~
~/antlr4/runtime/Swift/Tests/Antlr4Tests/gen/VisitorCalcParser.swift:46:7: error: method does not override any method from its superclass
        func getSerializedATN() -> String { return VisitorCalcParser._serializedATN }
```
Due to the change removing them.
This is running:
```fish
set -lx JAVA_HOME (java -XshowSettings:properties -version 2>&1 | grep 'java\.home' | awk '{ print $3 }')
python3 runtime/Swift/boot.py --test
```

**Comment by parrt** [comment]
Hi! It looks like there are more grammars that need to be regenerated for that target. 4.10 is backward incompatible because of that realization. let me take a look.

**Comment by parrt** [comment]
Oh, @Dante-Broggi sorry. I just merged my massive prep-4.10 branch into dev.  can you pull dev again and retry?  it looks like swift is working for me locally.

**Comment by KvanTTT** [comment]
@Dante-Broggi try to execute the following commands on your repo (`dev` branch):

```
mvn clean
mvn -DskipTests install
```

It looks like generated files are generated with the precious version.

**Comment by KvanTTT** [comment]
Or just ignore them. It looks like they are not executed by CI.

**Comment by parrt** [comment]
I think we are okay now: https://github.com/antlr/antlr4/actions/runs/2144550279  I had to merge my preparatory branch into dev

**Comment by parrt** [comment]
as this does not affect windows, I will merge.

**Comment by KvanTTT** [comment]
The errors like

```
/private/var/folders/92/21tbdwzn1rd2c0pk986w1hkr0000gq/T/BaseSwiftTest-main-1649566326427/testcase-1649566326440/Sources/testcase-1649566326440/MParser.swift:116:116: error: argument type 'Token?' does not conform to expected type 'Token'
                        print(((_localctx.castdown(SContext.self)._a != nil ? try _input.getText(_localctx.castdown(SContext.self)._a!.start,_localctx.castdown(SContext.self)._a!.stop) : "")) ?? "nil", terminator: "")
                                                                                                                                       ^
                                                                                                                                             as! Token
```

are still presented.

**Comment by parrt** [comment]
That might be an old run, @KvanTTT

**Comment by parrt** [comment]
@Dante-Broggi There are definitely still errors.  I need to get 4.10 out.  should I revert this one?

```
Process exited with status 1
java.io.IOException: Process exited with status 1:
Building for production...
remark: Incremental compilation has been disabled: it is not compatible with whole module optimization[1/2] Compiling testcase_1649612770407 TBaseListener.swift
/private/var/folders/w1/_nr4stn13lq0rvjdkwh7q8cc0000gn/T/BaseSwiftTest-main-1649612770400/testcase-1649612770407/Sources/testcase-1649612770407/TParser.swift:154:42: error: argument type 'Token?' does not conform to expected type 'Token'
                        print(((try _input.getText(_localctx.start, try _input.LT(-1)))) ?? "nil")
                                                             ^
                                                                  !
/private/var/folders/w1/_nr4stn13lq0rvjdkwh7q8cc0000gn/T/BaseSwiftTest-main-1649612770400/testcase-1649612770407/Sources/testcase-1649612770407/TParser.swift:154:60: error: argument type 'Token?' does not conform to expected type 'Token'
                        print(((try _input.getText(_localctx.start, try _input.LT(-1)))) ?? "nil")
                                                                               ^
                                                                                     !


	at org.antlr.v4.test.runtime.swift.BaseSwiftTest.runProcess(BaseSwiftTest.java:238)
	at org.antlr.v4.test.runtime.swift.BaseSwiftTest.buildProject(BaseSwiftTest.java:170)
	at org.antlr.v4.test.runtime.swift.BaseSwiftTest.execParser(BaseSwiftTest.java:296)
	at org.antlr.v4.test.runtime.swift.BaseSwiftTest.execParser(BaseSwiftTest.java:134)
	at org.antlr.v4.test.runtime.BaseRuntimeTest.testParser(BaseRuntimeTest.java:213)
	at org.antlr.v4.test.runtime.BaseRuntimeTest.testOne(BaseRuntimeTest.java:175)
	at jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

junit.framework.AssertionFailedError: [Swift:AorBStar_1] Parse output is incorrect: expectedOutput:<
>; actualOutput:<>; expectedParseErrors:<>; actualParseErrors:<>; expectedToolErrors:<>; actualToolErrors:<>.

	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.TestCase.fail(TestCase.java:223)
	at org.antlr.v4.test.runtime.BaseRuntimeTest.assertCorrectOutput(BaseRuntimeTest.java:601)
	at org.antlr.v4.test.runtime.BaseRuntimeTest.testParser(BaseRuntimeTest.java:222)
	at org.antlr.v4.test.runtime.BaseRuntimeTest.testOne(BaseRuntimeTest.java:175)
	at jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

**Comment by KvanTTT** [comment]
> There are definitely still errors. I need to get 4.10 out. should I revert this one?

I suggest waiting for fix.

**Comment by Dante-Broggi** [comment]
just revert for now, I think.

**Comment by parrt** [comment]
ok. thanks.

**Pull request merged**
