### PR TITLE
Fix mistake in tokenIndex bounds check

### PR DESCRIPTION
**Pull request by pboyer**
I noticed a minor mistake in the JavaScript runtime. From what I can tell the `tokenIndex` property is never assigned and thus is `undefined`

Note that in JavaScript,

```js
undefined < anyInteger
```

returns `false`

### CODE REVIEW

**Comment by ericvergnaud** [comment]
Hi,
thanks for this.
Have you signed the contributors agreement?
Eric

**Comment by sharwell** [comment]
@pboyer Before we can accept this, you'll need to update the pull request to add a commit to sign [the contributor agreement](https://github.com/antlr/antlr4/blob/master/contributors.txt).

I would prefer to see a test covering this case, but it does appear to resolve a bug.

:memo: I am not a JavaScript developer, so @ericvergnaud will need to review this as well.

**Comment by pboyer** [comment]
Thanks, guys! I'll take a look after work. Can you point out where I might add a test for this?

**Comment by sharwell** [comment]
@pboyer I'm not sure a test for this case is easy to write with the current infrastructure, but @ericvergnaud should be able to point you in the right direction if there's a good place for it. :smile:

**Comment by pboyer** [comment]
Hi @ericvergnaud and @sharwell!

I added my name to the contributors agreement. I have some more improvements for the js runtime but I'll send them in separate PR's.

**Pull request merged**
