### PR TITLE
[C++] Bump minimum required version to C++17

### PR DESCRIPTION
**Pull request by jcking**
Bump the minimum required version to C++17 and remove preprocessor guards that are no longer necessary. Additionally it switches `antlrcpp::SingleWriteMultipleReadLock` to just use `std::shared_mutex`. #3330

### CODE REVIEW

**Comment by jcking** [comment]
@mike-lischke

**Review by mike-lischke — APPROVED** [review]

**Comment by mike-lischke** [comment]
Good job! Though we need a look at Visual Studio Code and Xcode. Can you do that yourself? I might be able to check Xcode, however.

**Comment by jcking** [comment]
I do not have a Mac to check XCode. What in visual studio code needs to be checked? I do not see any of the editor configuration files directly checked in. Do you mean Visual Studio?

**Comment by mike-lischke** [comment]
Ah, I'm working too much in vscode lately :-) I meant Visual Studio of course. I don't expect much to be changed (if at all) for VS, as that by default uses the latest support C++ dialect. In Xcode we need to change at least the build project settings for C++17. Not sure when I'll find the time to do that, but I see what I can do.

**Comment by jcking** [comment]
I think I got them, but I am not sure if its correct as it was manual. I also fixed the files after the guid.{h,cpp} -> Guid.{h,cpp} rename.

**Comment by mike-lischke** [comment]
Strange, I just committed my macOS fixes to this PR and was successful, but the change don't appear here. Is there anything else that must be done?

Note: I checked out the branch using `gh pr checkout 3335`.

**Comment by jcking** [comment]
That might be because I force pushed at some point after fixing something. If you still have them locally you can pull the latest changes for the pr then repush them.

**Comment by mike-lischke** [comment]
My changes still exist (https://github.com/mike-lischke/antlr4/tree/cpp17) and I have merged in all other changes, but they don't automatically merge, as they should. I guess I have to open a new PR with them. If you don't have a better idea I'll ask Ter to merge this PR and I'll open a follow up PR then.

**Comment by jcking** [comment]
Works for me.

**Comment by jcking** [comment]
@parrt

**Comment by parrt** [comment]
Hi @jcking !  Upgrading to C++17 sounds great, assuming most compilers can handle it, but I'll have to defer to @mike-lischke   thanks!

**Review by mike-lischke — APPROVED** [review]

**Comment by mike-lischke** [comment]
OK, then let's do it. @parrt please merge this patch. I'll open a new PR with my additional changes.

**Pull request merged**
