### PR TITLE
Update description about running + adding tests in ANTLR.

### PR DESCRIPTION
**Pull request by mike-lischke**
Added new file for testing in general and consolidated the other testing related info there and in adding-tests.md.

### CODE REVIEW

**Comment by parrt** [comment]
oh shoot. i didn't see this before i updated doc. i guess my change was similar so i'll close. thanks!

**Comment by ericvergnaud** [comment]
the C# Runtime only requires Mono on non-Windows boxes
On Windows it uses the Microsoft .net stack

Envoyé de mon iPhone

**Comment by parrt** [comment]
thanks. I'll update

**Comment by mike-lischke** [comment]
:-(

**Pull request closed without merging**
