### PR TITLE
Fixes #994; poor left-recursive rule performance

### LINKED ISSUE #994: Another poor performance about expression parsing
I'm using ANTLR-4.4 with a grammar file modified from [sqlite.g4](https://github.com/antlr/grammars-v4/blob/master/sqlite/SQLite.g4),and find  some complex expressions cost too much time to parse.And then I found  [issue#192](https://github.com/antlr/antlr4/issues/192) .

That grammar file works fast with the antlr version I'm using now.But when I add some rules I used in my grammar file,it get slow down.

To make the issue simple,the grammar I use is just like this:

```
grammar expr;

expr: ID
    | 'not' expr
    | expr 'and' expr
    | expr 'or' expr
    | expr 'between' expr 'and' expr
    ;

ID: [a-zA-Z_][a-zA-Z_0-9]*;
WS: [ \t\n\r\f]+ -> skip;
ERROR: .;
```

and the sample file is just same like

```
not X1 and not X2 and not X3 and not X4 and not X5 and not X6 and not X7 and not X8 and not X9 and not X10 and not X11 and not X12 or
    X1 and not X2 and not X3 and not X4 and not X5 and not X6 and not X7 and not X8 and not X9 and not X10 and not X11 and not X12 or
not X1 and     X2 and not X3 and not X4 and not X5 and not X6 and not X7 and not X8 and not X9 and not X10 and not X11 and not X12
```

I tried this with the antlr plugin in IDEA,just 3 lines of the expressions will make the parsing time unacceptable.

### PR DESCRIPTION
**Pull request by parrt**

### CODE REVIEW

**Comment by parrt** [comment]
Dear @antlr/antlr-targets folks, you should take a look at this small 60 line patch (method `canDropLoopEntryEdgeInLeftRecursiveRule()`) to ParserATNSimulator. It is a 10,000x speed boost. I added tests in PerformanceDescriptors that ignore all but Java target so you can unignore and see it take overnight to parse 10 lines. Then fix and it's fast :)

**Comment by parrt** [comment]
@hanjoes @pboyer looks like team antlr-targets invitation went to your spam buckets. can you check?

**Comment by hanjoes** [comment]
Yep, I've accepted the invitation.

**Comment by mike-lischke** [comment]
Hmm, strange, your largest test case takes just 3ms in the C++ target using a much more complex expr rule set (see the MySQL grammar), **without** this patch. It might not have the same impact on already fast language targets. I'll work on the translation soon.

**Comment by sharwell** [comment]
@mike-lischke this is an algorithm complexity change for the affected grammars. It only affects grammars and inputs with particular lookahead characteristics. For example, it affects the Java grammar yet no file in the entire JDK code base (12,000+ source files) hits the slow case. In other cases, the bad performance could be hit on a regular basis.

**Comment by mike-lischke** [comment]
I understand, but Ter mentioned that the test grammars would take minutes for him, while in the C++ target they only take ms (without the patch). Which is what makes me wondering.

**Comment by parrt** [comment]
Also the new tests that I added are set to be ignored for all but the Java target... just in case it looked like they were executing okay.

**Comment by mike-lischke** [comment]
Quite confusing what the actual fix is, when looking at this entry. I assume the thing that target author should care about is [fdee94d] (mentioned in the final merge)? But that's a bit more than 60 LOCs. And in that patch I see new tests, but no change that would enable/disable them for a target. Is that in yet another patch?

**Comment by ericvergnaud** [comment]
just did the Python migration
it breaks 2 LR tests - it might take me some time to figure out why…

**Comment by parrt** [comment]
@ericvergnaud ok, lemme know if you need help

**Comment by parrt** [comment]
@mike-lischke You just have to implement function https://github.com/antlr/antlr4/commit/fdee94d52906985ffd93fe7bdf752dffb1272bbf#diff-49c5618cf842764cf250783fe7c0fe6cR1701 and inject a call to it elsewhere. the runtime tests work automatically.

**Comment by mike-lischke** [comment]
@parrt yes, yes, I was just wondering why I didn't see a full patch link, only those from individual commits. But this is probably the result of the already closed pull request. A Github usability issue...

**Comment by pboyer** [comment]
@parrt I don't see an invite for @antlr/antlr-targets in my email.

**Comment by parrt** [comment]
@pboyer i canceled and reinvited you. :) check spam

**Comment by parrt** [comment]
@mike-lischke yep, that's why i looked at "files changed" not "commits". much easier. :) Actually, i often pull into a branch and then run a diff on the two directories to see the complete set of changes.

**Comment by pboyer** [comment]
Thanks @parrt! I'm in. "10,000x"? Sounds like only a constant factor to me! 😆 I'll give this a shot, ASAP.

**Pull request merged**
