### PR TITLE
Character issues

### PR DESCRIPTION
**Pull request by KvanTTT**
fixed https://github.com/antlr/antlr4/issues/1077 and another character issues (see tests for detail).
Some changes are taken from https://github.com/antlr/antlr4/pull/1092

### CODE REVIEW

**Comment by mike-lischke** [comment]
While you are that would it be possible for you to add full Unicode sets (everything up to 0x10FFFF) in the code generator? That looks like something related to your changes here, so you might have a quick idea how to implement that.

**Comment by parrt** [comment]
There's a lot going on here. Not sure I can make all of these right before a release.  E.g., I don't agree that 'keyword' and ID should yield a warning. we'll see millions of them in a typical grammar.

**Comment by KvanTTT** [comment]
@mike-lischke I think full Unicode sets should be implemented in separated pull request. This one it too big and fixes the bugs, not brings a new features.

**Comment by KvanTTT** [comment]
> E.g., I don't agree that 'keyword' and ID should yield a warning

@parrt 'keyword' and ID does not yield a warning here. This PR about incorrect, duplicated and empty char sets.

**Comment by parrt** [comment]
ah. ok, well, let me pull and sniff some more.

**Comment by parrt** [comment]
@mike-lischke I don't see a quick way to do 32-bit unicode. certainly makes everything hard as char is 16 bits in Java.

**Comment by parrt** [comment]
@KvanTTT  please note for future reference how i like my `else` on a separate line than `}` ;)

**Comment by KvanTTT** [comment]
@parrt ok, I got it :)

**Comment by parrt** [comment]
I pulled in your stuff into a separate branch, made some tweaks and will use a separate PR so I'm closing this.

**Pull request closed without merging**
