### PR TITLE
use src 11 for tool, but 8 for plugin/runtime

### PR DESCRIPTION
**Pull request by parrt**
Wow. This appears to work.

### CODE REVIEW

**Comment by parrt** [comment]
Seems to use Java 8 for runtime!

```
$ od -x `find runtime/Java -name Token.class`|head
0000000      feca    beba    0000    3400    2500    0007    0722    2300
```

That `34` after 0xCAFEBABE means Java 8 (Java 7 is 33).

**Comment by parrt** [comment]
Thanks to @ericvergnaud for pointing the obvious solution here to allow java 11 for tool while keeping java 8 runtime :)

**Review by KvanTTT — APPROVED** [review]

**Comment by parrt** [comment]
Awesome. Updated appveyor as well. All java stuff passing...merging. woot!

**Comment by ericvergnaud** [comment]
That's -really- cool!

**Comment by wangyum** [comment]
Hi @parrt Why tool must use java 11?

**Comment by parrt** [comment]
Because we wanted to use more recent versions of the language; I think there were some compatibility issues as well.

**Pull request merged**
