### PR TITLE
Bugfix 3375: Fix bug when pasing .interp file

### LINKED ISSUE #3375: The parseFile method  of the InterpreterDataReader class is missing code: "line = br.readLine();"
target information : Java
The parseFile method  of the InterpreterDataReader class before check the code "if (line.equals("channel names:"))", missing code "line = br.readLine();"
The source code like this:
image
The code we're expecting like this:
image

### PR DESCRIPTION
**Pull request by Tinker1024**
I have rised a issue #3375 when I was reading codes in runtime module.
The bug will lead the parseFile() to strange error.
So I open this PR to fix it.

fixes #3375

### CODE REVIEW

**Review by mike-lischke — APPROVED** [review]
@parrt Good patch for the Java interpreter data reader and a new test that probably needs a change wrt to the test reorg.

**Comment by parrt** [comment]
Hi! Thanks. could you also sign the contributors.txt file? Thanks!

**Comment by parrt** [comment]
@mike-lischke I'll tweak the test upon merging.

**Comment by parrt** [comment]
@Tinker1024 please ping with `@parrt` when you've signed.

**Review by mike-lischke — APPROVED** [review]

**Comment by Tinker1024** [comment]
> @Tinker1024 please ping with `@parrt` when you've signed.
Hi! I have signed the contributors.txt. :-）

**Pull request merged**
