### PR TITLE
[C++ codegen] Fixed deprecation warning for CPP targets > 17

### PR DESCRIPTION
**Pull request by sigmasoldi3r**
As proposed in the paper [P0409R2](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0409r2.html), in C++20 not capturing explicitly `this` is deprecated.

This causes warnings when compiling parsers generated for target C++:
```
/tmp/MyParser.cpp:242:25: note: add explicit 'this' or '*this' capture
/tmp/MyParser.cpp: In lambda function:
/tmp/MyParser.cpp:335:25: warning: implicit capture of 'this' via '[=]' is deprecated in C++20 [-Wdeprecated]
  335 |   auto onExit = finally([=] {
      |                         ^
```

The commit includes a simple preprocessor guard that generates the appropriate code if `__cplusplus > 201703L`.

### CODE REVIEW

**Comment by sigmasoldi3r** [comment]
PHP target does not pass tests on main? 🤔

**Review by mike-lischke — APPROVED** [review]
Nice to see work towards C++20!

**Comment by mike-lischke** [comment]
@sigmasoldi3r Please resolve the conflict with master.

@parrt Once the conflict is solved this patch is ready to be merged.

**Comment by sigmasoldi3r** [comment]
Done!

**Comment by parrt** [comment]
I'm not sure if appveyor timed out or what but the final message in the log file is:

```
org.antlr.v4.test.runtime.php.TestParserErrors
[00:59:53] Running org.antlr.v4.test.runtime.php.TestParserExec
```

 Does that mean it took more than an hour and failed? I'm nervous about merging this if it's failing. can you guys check it out? @sigmasoldi3r @mike-lischke

**Comment by sigmasoldi3r** [comment]
Last time happened too. Not sure why but the php target is not touched at all. 
The changes shouldn't make build times longer tho. :thinking:

**Comment by parrt** [comment]
maybe we have so many targets now that it just takes too long to process?

**Comment by mike-lischke** [comment]
The build for the other C++ patches succeeded, so it's probably not the number of targets. And no, the patch doesn't even remotely touch PHP. Can you respin the build again Ter?

**Comment by parrt** [comment]
Maybe @sigmasoldi3r  can just make a trivial whitespace commit or something to kick off the build? I think that's the only way we can kick it off.

**Comment by sigmasoldi3r** [comment]
I'll do It ASAP! Sorry I'm out of home

**Comment by sigmasoldi3r** [comment]
@parrt Ready to go! 🚀

**Pull request merged**
