### PR TITLE
Escape reserved words during grammar generation (@parrt version)

### LINKED ISSUE #1070: Have ANTLR4 prevent conflict with user rule names by behind-the-scenes renaming of its own variables
I have a grammar with rules named xif and xcontinue and others, which were renamed from if/continue/etc due to antlr creating variables with these names and clashing with java. It would be more polished if antlr distinguished its identifiers from any possible back-end reserved words somehow. 
A consistent prefixing scheme might suffice, preventing clashes but keep a human-comprehensible correspondence between the parser and the generated back-end code (perhaps have the prefix 'ANTLR4_' as a reserved prefix for antlr itself?).

### PR DESCRIPTION
**Pull request by KvanTTT**
fixes #1070

Always escape `x` to `x_`, `X` to `X_`, `XContext` to `X_Context` (@parrt version, see https://github.com/antlr/antlr4/issues/1070#issuecomment-1003596172). It does not relate to languages with reserved words escaping (C#, Swift).

Deprecate `USE_OF_BAD_WORD`

### CODE REVIEW

**Comment by KvanTTT** [comment]
@kaby76 or @studentmain could you provide updated lists of reserved words (both keywords and conflicting symbols) for all runtimes while I'm completing the fixes?

**Comment by kaby76** [comment]
> @kaby76 or @studentmain could you provide updated lists of reserved words (both keywords and conflicting symbols) for all runtimes while I'm completing the fixes?

As we have an undocumented requirement in grammars-v4 that an Antlr g4 should be target agnostic, the "bad word list" applied to all targets, not a specific target. And there was no differentiation between keyword vs a conflicting symbol. The initial version was culled from the Antlr tool sources, discussed [here](https://github.com/antlr/grammars-v4/issues/2153). But, you already are modifying that code.

To get a combined list, the easiest would be to use trxgrep and look for anything that ends in an underscore. But, that would be a merged list for all targets. I would have to write a grammar against each bad word, and test it against each of the targets, easily doable but I can't come up with that quickly.

**Comment by KvanTTT** [comment]
> There is no differentiation between keyword vs a conflicting symbol --all bad words are off limits regardless

Differentiation is worth only for languages that support keywords escaping (C#, Swift). But if this info is unknown, a word is treated as a conflicting symbol.

> To get an updated, combined list, the easiest would be to use trxgrep and look for anything that ends in an underscore. But, that would be a merged list for all targets. I would have to write a grammar against each bad word, and test it against each of the targets, easily doable but I can't come up with that quickly.

It would be great. No rush, especially since I haven't finished either.

**Comment by KvanTTT** [comment]
I'm closing it in favor of https://github.com/antlr/antlr4/pull/3451 Let's continue there.

**Comment by kaby76** [comment]
Here is the aggregated list of "bad symbols" (with an underscore at the end).

[all_underscore.txt](https://github.com/antlr/antlr4/files/7801985/all_underscore.txt)

It was computed using the following script on a clean git clone of grammars-v4.

[get-all-unames.txt](https://github.com/antlr/antlr4/files/7801989/get-all-unames.txt)

**Pull request closed without merging**
