### PR TITLE
C++ runtime: Fix two issues found by coverity

### PR DESCRIPTION
**Pull request by Griffon26**
Two tiny changes to fix two coverity violations that I encountered while checking my own codebase.

### CODE REVIEW

**Comment by jm-mikkelsen** [comment]
I have an alternate fix for the IntervalSet va_end problem in pull request #1930 that eliminates va_arg usage and replaces it with a variadic template. I don't think @mike-lischke has had a chance to review it yet, though.

**Comment by mike-lischke** [comment]
@jm-mikkelsen I reviewed that patch already.

**Comment by Griffon26** [comment]
@jm-mikkelsen Not a problem. I'll rebase this one if yours gets merged sooner.

**Comment by parrt** [comment]
weAlso need a signature in the contributors file...

**Comment by parrt** [comment]
@Griffon26 We need a signature in the contributors file before I can merge this.

**Comment by Griffon26** [comment]
Man you're fast! I was in the process of rebasing to master =D

**Pull request merged**
