### PR TITLE
Added templated move support for antlrcpp::Any

### PR DESCRIPTION
**Pull request by mattpaletta**
Related to: #1919 

I am also using std::unique_ptr for my project, and I tried to allow support for non-copyable types with the least amount of code changes.  Would love to hear your feedback.

### CODE REVIEW

**Review by mike-lischke — APPROVED** [review]
Looks good, pls fix the merge conflict in contributors.txt and any test fix that may come up.

@parrt A pure C++ fix to be merged, once the tests show this fix is ok.

**Comment by parrt** [comment]
@mike-lischke  looks like we have some builders. Did I do this in the wrong order? https://app.circleci.com/pipelines/github/antlr/antlr4/349/workflows/e86a524d-dbce-45cb-9b75-5387693a551f/jobs/2605

**Comment by mike-lischke** [comment]
I don't think this is a problem of the order. Something with that utf8cpp repo is wrong. I asked the author of the other patch to fix it. If that doesn't work out we can just revert his patch.

**Comment by parrt** [comment]
Looks like we might still be failing @mike-lischke  should we kick a new build to see if recent fixes have occurred?

**Comment by mike-lischke** [comment]
@parrt The two failures are about the Go runtime (appveyor) and a timeout (circleci C++ recursion). I doubt the recent patches have to do with any of them.

**Pull request merged**
