### PR TITLE
Annotate Java files as being generated

### PR DESCRIPTION
**Pull request by magicwerk**
Signed-off-by: magicwerk <magicwerk@gmail.com>

### CODE REVIEW

**Comment by parrt** [comment]
hi. I don't think it's a good idea to add an option to the entire tool just to get this tiny feature for one out of 10 targets.  What problem are you solving here may I ask?

**Comment by magicwerk** [comment]
The problem I try to solve is referenced:
- Add @SuppressWarnings and @Generated annotations to all generated classes and interfaces #2568
There is also another related issue:
- javax.annotation.processing.Generated #2512 
In both issues, feedback was positive that a PR would be welcomed and reviewed.
So this PR tries to solve theses issues.

**Comment by parrt** [comment]
Thanks very much for the detailed response. Could you modify this so all it does is add @generated("ANTLR") in Java.stg? Can I don't think I'm ready for options or any other warning suppression at this time. thanks!

**Comment by magicwerk** [comment]
Unfortunately things are not that easy...
The original annotation @javax.annotation.Generated is not longer part of Java 11.
You can use @javax.annotation.processing.Generated instead or bring back the old javax stuff with the artifact javax.annotation:javax.annotation-api.
As Antlr targets a wide ranch of Java versions, a command line option would definitely make more sense.

**Comment by parrt** [comment]
hm...ok, yeah, I don't want to add an option just for this. As it doesn't make sense to add something that will only work with certain versions then I guess I'll close. sorry!

**Comment by Vampire** [comment]
@parrt could you maybe reconsider this?
It would be super helpful.
Especially as both mentioned `Generated` annotations have `SOURCE` level retention and if you for example want JaCoCo to be able to exclude files, they need to have a `Generated` annotation with at least `CLASS` retention as it does not work with the source code.
So being able to pick an annotation to apply, or maybe even multiple to also add warning suppression, would really be helpful.

**Pull request closed without merging**
