### PR TITLE
C# and Go runtime tests fixes on non-Windows OS

### PR DESCRIPTION
**Pull request by KvanTTT**

### CODE REVIEW

**Comment by KvanTTT** [comment]
@ericvergnaud it seems like circleci builds now work.

**Comment by KvanTTT** [comment]
@ericvergnaud please merge, it fixes the rest problems with tests.

**Comment by parrt** [comment]
Somehow I just got maven to work and install locally. All Java and C# tests pass on my mac.   Are we sure these changes are needed? @ericvergnaud ?

**Comment by KvanTTT** [comment]
Yes, maybe something wrong with your configuration, because it is reproducible on the current master: https://app.circleci.com/pipelines/github/antlr/antlr4 Also. Those errors after that runtime tests optimization: https://github.com/antlr/antlr4/pull/3365 (Linux status were not being displayed there because of some problem on CircleCI and my side, that's why I didn't notice them in time. But the problem was eventually resolved).

Also, I didn't mention Java, but Go

**Comment by parrt** [comment]
ok.  let me look at these changes. 

I am updating versions of all of the maven plug-ins in the poms.  Is that a good idea? I'm working on another PR to get a reliable build.

**Comment by KvanTTT** [comment]
> I am updating versions of all of the maven plug-ins in the poms. Is that a good idea?

If everything works fine then why not. I have no objection.

**Comment by parrt** [comment]
all of the tests are passing so I will pull that in and see if I can build :)

**Comment by parrt** [comment]
@KvanTTT C#  doesn't test locally for me:

```
ANTLR installation corrupted; cannot find ANTLR messages format file org/antlr/v4/tool/templates/messages/formats/antlr.stg
ANTLR installation corrupted; cannot find ANTLR messages format file org/antlr/v4/tool/templates/messages/formats/antlr.stg

java.lang.Error: ANTLR ErrorManager panic

	at org.antlr.v4.tool.ErrorManager.panic(ErrorManager.java:303)
	at org.antlr.v4.tool.ErrorManager.setFormat(ErrorManager.java:229)
	at org.antlr.v4.Tool.<init>(Tool.java:200)
	at org.antlr.v4.test.runtime.BaseRuntimeTest.antlrOnString(BaseRuntimeTest.java:307)
	at org.antlr.v4.test.runtime.BaseRuntimeTest.antlrOnString(BaseRuntimeTest.java:276)
	at org.antlr.v4.test.runtime.csharp.BaseCSharpTest.rawGenerateRecognizer(BaseCSharpTest.java:123)
	at org.antlr.v4.test.runtime.csharp.BaseCSharpTest.rawGenerateRecognizer(BaseCSharpTest.java:111)
	at org.antlr.v4.test.runtime.csharp.BaseCSharpTest.execParser(BaseCSharpTest.java:90)
	at org.antlr.v4.test.runtime.BaseRuntimeTest.testParser(BaseRuntimeTest.java:220)
	at org.antlr.v4.test.runtime.BaseRuntimeTest.testOne(BaseRuntimeTest.java:182)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

**Comment by KvanTTT** [comment]
Not sure it's related to C#. Do other runtime tests work? Do you have installed dotnet? https://dotnet.microsoft.com/download

**Comment by parrt** [comment]
All is well. mvn works from the commandline.

**Comment by KvanTTT** [comment]
CircleCi says that c# is OK: https://app.circleci.com/pipelines/github/antlr/antlr4/705/workflows/aa5f52e2-b8c0-41e5-8bc2-e96e46fc8a78 maybe it's invalid cache in Idea.

**Pull request merged**
