### PR TITLE
Fix incorrect export in Javascript runtime tree/index.js

### PR DESCRIPTION
**Pull request by pboyer**
Fix for #1039. Please merge after #1039, which adds my name to the contributors agreement.

### CODE REVIEW

**Comment by ericvergnaud** [comment]
blessed

**Comment by pboyer** [comment]
Ah I meant merge after #1063

**Comment by jeroencranendonk-wf** [comment]
Will this PR be reopened and merged at some point?

**Comment by parrt** [comment]
Hmm.. shit. I missed that. only got part of it.

**Comment by parrt** [comment]
Fixed with https://github.com/antlr/antlr4/pull/1110

**Comment by pboyer** [comment]
Hey! @parrt stole my trivial PR! He's on a power trip! ;)

**Comment by parrt** [comment]
Hahahha!

**Pull request closed without merging**
