### PR TITLE
implement faster HashMap

### PR DESCRIPTION
**Pull request by ericvergnaud**
new faster HashMap

### CODE REVIEW

**Comment by ericvergnaud** [comment]
ignore unrelated php failure

**Comment by kaby76** [comment]
For this PR, there is a 40% speed up. (2.8537 +- SD 0.0124 vs 2.0492 +- SD 0.033).

java

**Comment by kaby76** [comment]
(There may be other optimizations that Antlr4ng does, but I haven't gotten that far.)

**Comment by ericvergnaud** [comment]
So we’re talking 60-65% cumulated improvements ? Whoosh!!!Envoyé de mon iPhoneLe 10 mars 2024 à 23:32, Ken Domino ***@***.***> a écrit :﻿
(There may be other optimizations that Antlr4ng does, but I haven't gotten that far.)

**Comment by kaby76** [comment]
Yes, something like ~60%. There are probably other optimizations to look at.

At some point, can we get a release of 4.13.2?? No hurries though, after other fixes are considered. I did not like this 4.13.1-patch1 release because that breaks my testing code, and I don't think GitHub Dependabot even considers this a release.

**Comment by kaby76** [comment]
This PR passes all grammars-v4 tests.

**Review by kaby76 — APPROVED** [review]

**Comment by ericvergnaud** [comment]
> At some point, can we get a release of 4.13.2?? No hurries though, after other fixes are considered. I did not like this 4.13.1-patch1 release because that breaks my testing code, and I don't think GitHub Dependabot even considers this a release.

That's a question for @parrt.

**Comment by ericvergnaud** [comment]
@kaby76 it's be interesting to run your performance benchmark on the merged dev version

**Comment by kaby76** [comment]
The runtime for the tip of dev is better.

java

But, it is still missing something as Antlr4ng is faster. I am still surprised the hash value caching didn't help. I must have done something wrong, or it should have been applied somewhere else. Looking....

**Comment by ericvergnaud** [comment]
antlr4ng also implements specialized constructors which avoid testing instance types. It might be worth doing this for the objects that are instantiated millions of times (such as ATNConfig). But we might be reaching a point where profiling becomes necessary to better understand the remaining bottlenecks.
Sam mentioned that the reason for not caching ATNConfig hashCode is memory footprint.

**Comment by ericvergnaud** [comment]
> But, it is still missing something as Antlr4ng is faster. I am still surprised the hash value caching didn't help. I must have done something wrong, or it should have been applied somewhere else. Looking....

I can revise and rebase that branch if you're willing to double-check that...

**Comment by kaby76** [comment]
I'm profiling the CSharp target because [your PR changed one file in that target](https://github.com/antlr/antlr4/pull/4546/files#diff-20dbca93785728353c109eb4fee6a1c1a308ddb178a58af9e1ddb17d915e383b). (IMO, C# has far-superior profiling tools to anything I've seen in all other targets.)

**Pull request merged**
