### PR TITLE
name 'state' conflict with Python3 runtime.

### PR DESCRIPTION
**Pull request by cyqw**
This PR fixes https://github.com/antlr/antlr4/issues/4291

This change add keyword tests.
add function names in parser as reserved keywords for targets.
use rule.escapedName instead  rule.name in php.stg

### CODE REVIEW

**Comment by ericvergnaud** [comment]
Hi,
thanks for this.
Unfortunately it's very likely that some developers are relying on `ctx.state` (a typical usage scenario is code completion).
The proposed refactoring would break their code. Plus it doesn't solve the problem, rather it moves it (now I can't use _state as a rule name).
I'm afraid the only reasonable solution here is to disallow usage of `state` as a rule name...

**Review by KvanTTT — CHANGES_REQUESTED** [review]
This fix is incorrect. Please add `state` to Python3 and Python2 [reservedWords](https://github.com/antlr/antlr4/blob/master/tool/src/org/antlr/v4/codegen/target/Python3Target.java#L15) list without touching runtime files.

**Comment by cyqw** [comment]
I think add the name of function or attribute of Parser, lexer to reservedWords is not a good idea.
The functions or attributes of parser, lexer should not expose to generated parser, lexer directly by inherit except some functions can be override. 
The parser should be split, one is the interface of generated parser, other one is the implement of basic parser, it is a member of generated parser.

**Comment by cyqw** [comment]
> This fix is incorrect. Please add `state` to Python3 and Python2 [reservedWords](https://github.com/antlr/antlr4/blob/master/tool/src/org/antlr/v4/codegen/target/Python3Target.java#L15) list without touching runtime files.
> 
> Also, it looks like `state` should be added to JavaScript, TypeScript and Dart reservedWords because CI tests are red: https://github.com/antlr/antlr4/actions/runs/5261330620/jobs/9509322855?pr=4312

@KvanTTT please review the new changes,  thanks

**Comment by KvanTTT** [comment]
Sorry, I don't review MR in this repository since I don't have maintainer rights and I can't merge requests.

**Comment by ericvergnaud** [comment]
@parrt blessed

**Comment by ericvergnaud** [comment]
@parrt kind reminder

**Pull request merged**
