### PR TITLE
C++ VS project updates for next ANTLR4 release

### PR DESCRIPTION
**Pull request by mike-lischke**
This patch contains a few changes to build now VS 2017/19 binaries instead of VS 2013/15 (with the deployment script). Also a warning was fixed (suppressed) and the docs updated wrt. the C++ target.

### CODE REVIEW

**Comment by mike-lischke** [comment]
@parrt Here's the promised patch. Depending on which prebuilt binaries you want to provide for download you will need Visual Studio 2017 and/or Visual Studio 2019. In the last ANTLR4 release we only had libs for VS 2015 IIRC, so it should be fine to only provide VS 2019 libs now. The script will check and compile only with those versions that really exist on your box. It will even succeed if you have no VS at all installed :-D (you just don't get any binaries to publish then). The release doc has been updated too.

**Comment by parrt** [comment]
I only have 2019 so we're cool. thanks!

**Comment by parrt** [comment]
Getting some errors:
Screen Shot 2020-01-03 at 8 40 31 AM

**Comment by parrt** [comment]
Screen Shot 2020-01-03 at 8 58 11 AM

**Comment by mike-lischke** [comment]
> Getting some errors:
> Screen Shot 2020-01-03 at 8 40 31 AM

I got similar errors, seems something specific to VS 2019. However I could fix them. Can you check if that path given in the error message exists? Maybe it's something that is different for the community version of VS (I have professional)?

**Pull request merged**
