### PR TITLE
Added ParserRuleContext.getFullText()

### PR DESCRIPTION
**Pull request by RedTailedHawk**

### CODE REVIEW

**Comment by sharwell** [comment]
With ANTLR 4.7, it should be possible to accomplish these goals without making changes to the runtime:

1. Create a class derived from `ParserRuleContext`
2. Set the new class as the base class for all rule context classes created for your grammar
3. Override `RuleContext.setParent`, and set `this.tokenStream = parent.tokenStream` (this way after setting it in the root it propagates to the entire tree).
4. In your root rule, set the token stream for the root node:

    ```antlr
    compilationUnit
    @before {
      $ctx.tokenStream = getTokenStream();
    }
      : ...
      ;
    ```

**Comment by RedTailedHawk** [comment]
@sharwell `Set the new class as the base class for all rule context classes created for your grammar` -- how do I do this?

**Comment by sharwell** [comment]
You can use the `contextSuperClass` option:

```
options {
  contextSuperClass=com.your.qualified.CustomParserRuleContext;
}
```

**Comment by RedTailedHawk** [comment]
Thanks, `contextSuperClass` is working great!  But I'm not having success with `@before`.  Here's my rule:

```
script
@before {
  $ctx.tokenStream = getTokenStream();
}
    : statements EOF
    ;
```

I regenerated the class, but I'm not seeing the above code in the generated `ScriptContext` class.  Am I looking in the wrong place?

**Comment by sharwell** [comment]
It's supposed to be `@init`. Sorry about that!

**Comment by RedTailedHawk** [comment]
OK, that works great!

Is there any way to skip these Java-specific annotations in my grammar when I also generate my classes for JavaScript?  If not, I can comment them out when I generate JavaScript, and then uncomment for Java.  Not too big a deal, but I do have to remember to do that whenever my grammar changes.

**Comment by parrt** [comment]
Thanks to @sharwell  I believe we have a solution so I am closing.

**Pull request closed without merging**
