### PR TITLE
added SVG export of parse tree

### PR DESCRIPTION
**Pull request by rlfnb**
Main driver for exporting to SVG was the ability to search in big parse trees. I wont add new dependencies to the pom.xml, but if its ok, I'll prepare the next commit for the SVG view, too.

### CODE REVIEW

**Comment by parrt** [comment]
@rlfnb Can you change it so the whitespace doesn't show up as changed? I can't understand the difference with all those showing.

**Comment by rlfnb** [comment]
rebased it and resolved the whitespace issues

**Comment by parrt** [comment]
thanks!

**Comment by neon12345** [comment]
It seems some special chars are not handled/translated? &amp; &quot; &apos;

**Pull request merged**
