### PR TITLE
Fix travis timeouts

### PR DESCRIPTION
**Pull request by ericvergnaud**
experimental, I'll comment if ok

### CODE REVIEW

**Comment by parrt** [comment]
heh looks good!

**Comment by parrt** [comment]
@mike-lischke I think we might finally have the time out thing figured out thanks to Eric.

**Comment by mike-lischke** [comment]
\o/, excellent @ericvergnaud

**Comment by parrt** [comment]
He broke the tests into multiple groups and ran them separately

**Pull request merged**
