### PR TITLE
fix to the ATN deserialiser issue on big endian architecture

### PR DESCRIPTION
**Pull request by vaibhavaingankar09**
In ReadUUID `byte d[]` to be reversed only in case of little endian architecture. In the case of big endian  `Array.Reverse(d)` is not required since the bytes are stored in the order most significant to least significant.

### CODE REVIEW

**Comment by ericvergnaud** [comment]
Out of curiosity, which system is exposing the problematic behaviour?
I'm a bit surprised that this would be the only issue with the deserialiser.

**Comment by vaibhavaingankar09** [comment]
ATN deserialiser issue arises on s390x systems, with UUID 59627784-3be5-417a-**8960-28a73181ebb9** whereas the expected UUID is 59627784-3be5-417a-**b9eb-8131a7286089**. If we notice the highlighted section of UUID is the representation of 8 bit byte array which is reversed.

**Comment by ericvergnaud** [comment]
Thanks
To your knowledge, does this only happen with the c# runtime?

**Comment by vaibhavaingankar09** [comment]
Yes, it is specific to c# runtime.

**Comment by ericvergnaud** [comment]
Thanks
@parrt blessed

**Pull request merged**
