### PR TITLE
Add Support For Swift Package Manager

### PR DESCRIPTION
**Pull request by 100mango**
Fix  https://github.com/antlr/antlr4/issues/2719
https://github.com/antlr/antlr4/issues/2557

Please Review:@ericvergnaud   @hanjoes   @parrt  @ewanmellor  Thanks a lot.

### CODE REVIEW

**Comment by parrt** [comment]
Hi @100mango  is this PR still relevant given merging of https://github.com/antlr/antlr4/issues/3301  previously? thanks!

**Comment by 100mango** [comment]
Hi, @parrt  I think this PR is still relevant

1. After I check the current master branch and 4.9.3 release. I found that there is no update support for the Swift Package Manager. So people still can't use Swift Package Manager Properly.
2. In my fork version (containing this PR change), it works with Swift Package Manager.  
3. But I found that this PR will cause the swift target tests to fail.  I would like to try to fix it later(it would be nice to have someone more familiar with this test script to help fix it :)  ). 
Thank you for your response.

**Comment by parrt** [comment]
ok, I will leave this open. Maybe @hanjoes  has some ideas

**Comment by hanjoes** [comment]
@100mango could you elaborate on how this PR is related to #1771? I saw that discussion was about unicode but this PR is for onboarding SPM. 

You also mentioned this PR causes test failure, the integration results shows the tests are "cancelled" so hard to see what exactly is the failure.

**Comment by 100mango** [comment]
@hanjoes Sorry for the mistake. This PR is related to SPM, not the Unicode problem.
https://github.com/antlr/antlr4/issues/2719
https://github.com/antlr/antlr4/issues/2557

The PR Changes will not affect the actual Antlr implementation, only change the `Package.swift` file to enable people to use SPM to adopt Antlr Swift runtime. like this:

```
let package = Package(
    name: "MyProject",
    platforms: [
        .macOS(.v11),
    ],
    products: [
      //.......
    ],
    dependencies: [
        .package(name: "Antlr4", url: "https://github.com/100mango/antlr4", from: "4.9.3"),
    ],
    targets: [
        .target(
            name: "MyTarget",
            dependencies: ["Antlr4"])
    ]
)
```

"the integration results shows the tests are "cancelled" so hard to see what exactly is the failure."

Can we manually trigger the test pipeline to see the actual failure？ ( I think modifying the `runtime/Swift/boot.py` 's swift_test() method properly can fix these test failures.   )

Thanks for your response.

**Comment by parrt** [comment]
hiya. try this [log of build](https://github.com/antlr/antlr4/runs/3863274808?check_suite_focus=true)

**Comment by hanjoes** [comment]
The runtime unit tests are passing but the generated integration tests are having issues

scrolling down a bit, it seems we have lots of errors like: 
```
[1/4] Compiling testcase_1633996911876 L.swift
/private/var/folders/85/3yb73nr53qgf68tmtfby5s3c0000gp/T/BaseSwiftTest-main-1633996911726/testcase-1633996911876/Sources/testcase-1633996911876/main.swift:1:8: error: no such module 'Antlr4'
import Antlr4
       ^
[2/4] Compiling testcase_1633996911876 LATN.swift
/private/var/folders/85/3yb73nr53qgf68tmtfby5s3c0000gp/T/BaseSwiftTest-main-1633996911726/testcase-1633996911876/Sources/testcase-1633996911876/main.swift:1:8: error: no such module 'Antlr4'
import Antlr4
       ^
[3/4] Compiling testcase_1633996911876 main.swift
/private/var/folders/85/3yb73nr53qgf68tmtfby5s3c0000gp/T/BaseSwiftTest-main-1633996911726/testcase-1633996911876/Sources/testcase-1633996911876/main.swift:1:8: error: no such module 'Antlr4'
import Antlr4
       ^
```

I'm wondering if there is something obvious missing, maybe the Antlr4 module was not generated because of this change.

**Comment by hanjoes** [comment]
@100mango  i saw you added one line to boot.py:
```
check_call(["cd","./../.."])
```
there is a single dot before the first slash, was this intentional? maybe that's why boot.py couldn't find the SPM manifest.

**Comment by hanjoes** [comment]
but maybe not related, since it's only for unit tests. 

i'm trying to set things up and see if i can run the tests locally.

**Comment by hanjoes** [comment]
it seems [this line](https://github.com/antlr/antlr4/blob/48854d9831f040ef4a4d887206e2b70f6077433d/runtime-testsuite/test/org/antlr/v4/test/runtime/swift/BaseSwiftTest.java#L58) in the test rig builds the swift module, maybe we should update the working dir since the package manifest has been moved to the root folder of the project?

@100mango 
@parrt

**Comment by 100mango** [comment]
@hanjoes 

> @100mango i saw you added one line to boot.py:
> 
> ```
> check_call(["cd","./../.."])
> ```
> 
> there is a single dot before the first slash, was this intentional? maybe that's why boot.py couldn't find the SPM manifest.

I need to write clearer code comments.    

`
 #package.swift define in project root directory. 
 #The boot.py file is in projectRoot/runtime/Swift
 #So we back to project root directory. Then start swift test
 check_call(["cd","./../.."])
`


> it seems [this line](https://github.com/antlr/antlr4/blob/48854d9831f040ef4a4d887206e2b70f6077433d/runtime-testsuite/test/org/antlr/v4/test/runtime/swift/BaseSwiftTest.java#L58) in the test rig builds the swift module, maybe we should update the working dir since the package manifest has been moved to the root folder of the project?
> 
> @100mango @parrt

Yes,  after moving the `package.swift` file to the root folder.  We need to build/test swift runtime in the root folder.

`shell
swift build  // should run in the folder containing  package.swift
swift test   //  should run in the folder containing package.swift
`
Thanks for your response. @parrt @hanjoes

**Comment by 100mango** [comment]
> but maybe not related, since it's only for unit tests.
> 
> i'm trying to set things up and see if i can run the tests locally.

👍👍👍  It would be helpful for development if we could run tests locally.  Sorry that I can't seem to find the relevant guidance document at the moment.   If we can run tests locally (For example, we can run the Swift tests individually) ， maybe I can fix it before making a PR.

**Comment by parrt** [comment]
Hi @100mango quick link before I head to bed... https://github.com/antlr/antlr4/blob/master/doc/antlr-project-testing.md has the info.  cd to runtime-testsuite then to `mvn -Dtest=swift.** test`.

**Comment by 100mango** [comment]
@parrt 👍 Good Night

**Comment by 100mango** [comment]
After change `ANTLR_RUNTIME_PATH ` in [BaseSwiftTest.java](https://github.com/antlr/antlr4/blob/7135d1f0fd150bec746b04c06a83c4f960d3fc63/runtime-testsuite/test/org/antlr/v4/test/runtime/swift/BaseSwiftTest.java#L56)

We can build/test swift runtime in the root folder.

**Comment by hanjoes** [comment]
great! thanks and happy new year!

**Comment by hanjoes** [comment]
this addresses #1774 as well,

**Pull request merged**
