### PR TITLE
Replace JDialog with JFrame

### PR DESCRIPTION
**Pull request by vonloxley**
I was resizing the dialog about three dozen times the day before, so I thought it could use a maximize button.

### CODE REVIEW

**Comment by danielsun1106** [comment]
+1

**Comment by parrt** [comment]
Cool. can you sign contributors.txt?

**Comment by vonloxley** [comment]
Hi Terence,

I understand your need to defend against possible litigation, the proposed contract however is formulated in a way that leaves some open questions:

1. Point two: I can only claim that third party rights (a formulation I feel is way too broad) aren’t violated at the time of contribution, not at the time of incorporation into the product or for the future. Furthermore I am able to certify that my contribution is free of third party rights in my country. I can`t possible do so for other countries where, for example, patent laws may be quite different.
2. Point three: I can only accept liability up to the amount of money I received for my work.

Therefore, I feel sorry for not being able to sign this contract.

Regards,

Niki

**Comment by parrt** [comment]
@vonloxley I fully understand. thanks anyway. I'll do myself.

**Comment by parrt** [comment]
Fixed with https://github.com/antlr/antlr4/commit/d580f2184f7ca7b8fd106a3fbc5a7bb12be97260

**Pull request closed without merging**
