### PR TITLE
Fix 2016 [WIP]

### PR DESCRIPTION
**Pull request by parrt**
Trying to fix https://github.com/antlr/antlr4/issues/2016  I Have fixed the issue with the template definition but I don't know how to update the various targets. At the moment Java, Swift, C# look like they are now correct.

### CODE REVIEW

**Comment by parrt** [comment]
@mike-lischke I think I fixed the C++ target but it is failing for another reason maybe in PredictionContext::merge():

```
Assertion failed: (a && b), function merge, file /Users/parrt/antlr/code/antlr4/runtime/Cpp/runtime/src/atn/PredictionContext.cpp, line 97.
execution of 'running test binary' failed with error code: 134
```

Can you take a look at this branch?

**Comment by mike-lischke** [comment]
Is this failure from the new test? The template changes can't be it, I guess.

**Comment by parrt** [comment]
New test exposed a different bug I believe as it is in a prediction function not about dealing with list labels.

**Comment by parrt** [comment]
@mike-lischke Any time to look into this? I'd like to include for 4.7.1

**Comment by mike-lischke** [comment]
I'll try to get some time for this next weekend. Am pretty busy currently...

**Comment by parrt** [comment]
@mike-lischke can you peek at this?

**Comment by mike-lischke** [comment]
Maybe at the end of the month...

**Comment by mike-lischke** [comment]
@parrt I can't find the branch with those changes (parrt:fix-2016). But, is that actually required for this problem? From the patch I see only template changes. They certainly aren't the reason for an uncovered C++ problem. So, I wonder where do you see that failure? Obviously master runs fine. What can I do to reproduce the error?

**Comment by parrt** [comment]
I am running the tests in my branch fix-2016 but so far all I see is a warning:

```
Building ANTLR4 C++ runtime (if necessary) at /Users/parrt/antlr/code/antlr4/runtime-testsuite/target/classes/Cpp
/Users/parrt/antlr/code/antlr4/runtime-testsuite/target/classes/Cpp/runtime/src/atn/ParserATNSimulator.cpp:56:42: warning: field 'parser' will be initialized after field 'decisionToDFA' [-Wreorder]
: ATNSimulator(atn, sharedContextCache), parser(parser), decisionToDFA(decisionToDFA) {
                                         ^
/Users/parrt/antlr/code/antlr4/runtime-testsuite/target/classes/Cpp/runtime/src/atn/ParserATNSimulator.cpp:56:42: warning: field 'parser' will be initialized after field 'decisionToDFA' [-Wreorder]
: ATNSimulator(atn, sharedContextCache), parser(parser), decisionToDFA(decisionToDFA) {
```

**Comment by parrt** [comment]
ok, 1 failure:

```
C++ runtime build succeeded

.Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 56.462 sec - in org.antlr.v4.test.runtime.cpp.TestCompositeLexers
Running org.antlr.v4.test.runtime.cpp.TestCompositeParsers
...............Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 74.943 sec - in org.antlr.v4.test.runtime.cpp.TestCompositeParsers
Running org.antlr.v4.test.runtime.cpp.TestFullContextParsing
..............Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 73.692 sec - in org.antlr.v4.test.runtime.cpp.TestFullContextParsing
Running org.antlr.v4.test.runtime.cpp.TestLeftRecursion
.................................................................................................Tests run: 99, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 481.083 sec <<< FAILURE! - in org.antlr.v4.test.runtime.cpp.TestLeftRecursion
testOne[Cpp:ListLabelsOnRuleRefStartOfAlt](org.antlr.v4.test.runtime.cpp.TestLeftRecursion)  Time elapsed: 0.037 sec  <<< FAILURE!
java.lang.AssertionError

Running org.antlr.v4.test.runtime.cpp.TestLexerErrors
...Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 17.354 sec - in org.antlr.v4.test.runtime.cpp.TestLexerErrors
Running org.antlr.v4.test.runtime.cpp.TestLexerExec
...........Tests run: 37, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 52.93 sec - in org.antlr.v4.test.runtime.cpp.TestLexerExec
Running org.antlr.v4.test.runtime.cpp.TestListeners
......Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 32.429 sec - in org.antlr.v4.test.runtime.cpp.TestListeners
Running org.antlr.v4.test.runtime.cpp.TestParserErrors
..............................Tests run: 34, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 149.015 sec - in org.antlr.v4.test.runtime.cpp.TestParserErrors
Running org.antlr.v4.test.runtime.cpp.TestParserExec
.................................Tests run: 36, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 165.211 sec - in org.antlr.v4.test.runtime.cpp.TestParserExec
Running org.antlr.v4.test.runtime.cpp.TestParseTrees
........Tests run: 10, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 41.069 sec - in org.antlr.v4.test.runtime.cpp.TestParseTrees
Running org.antlr.v4.test.runtime.cpp.TestPerformance
.......Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 36.221 sec - in org.antlr.v4.test.runtime.cpp.TestPerformance
Running org.antlr.v4.test.runtime.cpp.TestSemPredEvalLexer
...Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 10.681 sec - in org.antlr.v4.test.runtime.cpp.TestSemPredEvalLexer
Running org.antlr.v4.test.runtime.cpp.TestSemPredEvalParser
......................Tests run: 26, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 112.005 sec - in org.antlr.v4.test.runtime.cpp.TestSemPredEvalParser
Running org.antlr.v4.test.runtime.cpp.TestSets
............................Tests run: 32, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 140.512 sec - in org.antlr.v4.test.runtime.cpp.TestSets

Results :

Failed tests: 
  TestLeftRecursion>BaseRuntimeTest.testOne:118->BaseRuntimeTest.testParser:155

Tests run: 340, Failures: 1, Errors: 0, Skipped: 3
```

**Comment by parrt** [comment]
Not doomed but might have to convert https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Parsing/Grammar/VBAParser.g4#L588 to avoid left-recursion. Are you using latest antlr 4.7.1?

**Comment by parrt** [comment]
Closing in favor of https://github.com/antlr/antlr4/pull/3841

**Pull request closed without merging**
