### PR TITLE
Dart int atn

### PR DESCRIPTION
**Pull request by parrt**

### CODE REVIEW

**Comment by parrt** [comment]
And this just leaves php. @marcospassos I'll take a wack at modifying that repo.

**Comment by marcospassos** [comment]
I'll take a look at this today, @parrt

**Comment by marcospassos** [comment]
Addressed by https://github.com/antlr/antlr-php-runtime/pull/23

**Comment by parrt** [comment]
oh! i got it working last night as well! I'll take a look. thanks

**Pull request merged**
