### PR TITLE
[dotnet] for linux target, bring up to jdk8 since jdk7 no longer available for Trusty; for linux and osx targets, bring up dotnet from 1.0.3 to 1.0.4; Trusty image now has mvn 3.3.9 builtin, removed install code

### PR DESCRIPTION
**Pull request by xied75**
@ericvergnaud @parrt

### CODE REVIEW

**Comment by parrt** [comment]
I'll wait for @ericvergnaud to review. thanks!

**Comment by ericvergnaud** [comment]
Linux build is fixed, but OS X one is now broken, see
https://travis-ci.org/antlr/antlr4/builds/247122557?utm_source=github_status&utm_medium=notification

**Comment by xied75** [comment]
It worked for my own push here https://travis-ci.org/xied75/antlr4/builds/247077570
The problem looks like transient random OSX image issues I guess. See the other two failures on OSX, try a restart?

**Comment by ericvergnaud** [comment]
Indeed, Travis is flaky, relaunching the build works
@parrt blessed

**Pull request merged**
