### PR TITLE
Enforce JDK runtime requirements

### PR DESCRIPTION
**Pull request by marcohu**
Use 1.6 version for the compiler and employ animal sniffer to enforce Java 6 compatibility.

### CODE REVIEW

**Comment by parrt** [comment]
We actually just decided on jdk 1.7 min for 4.6 ;)

**Comment by marcohu** [comment]
I've asked about the runtime requirement some days ago and you mentioned that Java 7 is only required for the build system, but the runtime will stay on 6 a bit longer. See here: https://github.com/antlr/antlr4/issues/1327#issuecomment-260126256.

Has that view changed and Java 7 is the new baseline for the runtime as well?

**Comment by parrt** [comment]
Hmm...yeah, I think i'll just make it all v7. Is there a reason you need 6?

**Comment by parrt** [comment]
Hmm..I'd rather not add yet more to pom files. I've been holding line at jdk 6 for a long time. I think i'll go with 7 for 4.6 release.  You can always compile locally for your customers.

**Pull request closed without merging**
