### PR TITLE
Javascript performance. 

### PR DESCRIPTION
**Pull request by ghosthope**
A new string.hash function has been added  (https://github.com/garycourt/murmurhash-js/blob/master/murmurhash3_gc.js). Performance of the function increased in two times

### CODE REVIEW

**Comment by ericvergnaud** [comment]
Hi,
haven't check the numbers, but this looks great!
I would expect an even greater performance improvement by refactoring the Set class, which calls object.hashString before calling String.hashCode.
The idea would be to through all the hash key components using murmur3 rather than hash the corresponding string.
Eric

**Comment by parrt** [comment]
@ericvergnaud so this is blessed?

**Comment by parrt** [comment]
@ghosthope Can you sign contributors.txt too?

**Comment by ericvergnaud** [comment]
I need to look at it again, will do that soon

**Comment by ericvergnaud** [comment]
blessed, although I may move this to a reusable hash class in the future

**Comment by ghosthope** [comment]
@parrt 
How can i do this?

**Comment by ericvergnaud** [comment]
yes

**Comment by parrt** [comment]
@ghosthope Can you sign contributors.txt too?

**Comment by parrt** [comment]
@ghosthope add a commit to https://github.com/antlr/antlr4/blob/master/contributors.txt that has your "sig" on the bottom.

**Comment by parrt** [comment]
Hi @ghosthope, I think your last commit was "blank"; i.e., not signature added.

**Pull request merged**
