### PR TITLE
Full tests for Python2:TokenStreamRewriter, runtime fixes, including fix for #550 (python and java) 

### LINKED ISSUE #550: TokenStreamRewriter doesn't preserve overrides order
Output order differs when many overrides are inserted with the same index.

I use `TokenStreamRewriter` in Listener. When a `placeholder` rule is entered I put `<b>` tag into rewriter with `insertBefore()`. When the placeholder is exited I put `</b>` tag into rewriter with `insertAfter()`. Everything is fine with call sequence but `rewriter.getText()` return something like the following when placeholders are side-by-side and not separated with some other lexer token.

```
<b>[placeholder1]<b></b>[placeholder1]</b>
```

### PR DESCRIPTION
**Pull request by lygav**
Following #1273 

Also fixes #550 for python runtime with new InsertAfter OP type

### CODE REVIEW

**Comment by lygav** [comment]
Added fix for #550 for Java also

**Comment by parrt** [comment]
Hi. it'd be better to have separate PRs for the python and java targets, but I'll take a look. thanks!

**Comment by lygav** [comment]
Sorry, it became automatically ‘bundled’ by GitHub together when i pushed to my fork master.

**Comment by parrt** [comment]
Separated manually. Pulled in #550 fix with https://github.com/antlr/antlr4/pull/1445

**Comment by parrt** [comment]
@lygav I separated python2 update too in https://github.com/antlr/antlr4/pull/1446

**Comment by parrt** [comment]
I will therefore close this one.

**Comment by lygav** [comment]
Thank you very much.

**Pull request closed without merging**
