### PR TITLE
Update LexerATNSimulator.cs with virtual Consume

### PR DESCRIPTION
**Pull request by cxambs**
Allow user to subclass and consume differently. Useful for CR handling as suggested in https://github.com/antlr/antlr4/pull/2519

### CODE REVIEW

**Comment by cxambs** [comment]
I understand this is a very small change, but if this gets accepted, a minor release would be very welcome.

**Comment by ericvergnaud** [comment]
@parrt blessed

**Comment by cxambs** [comment]
Do we have a tentative date for 4.12.1?
Thanks

**Comment by parrt** [comment]
unfortunately not. Kinda waiting on Go updates.

**Comment by jimidle** [comment]
I’ll be ready this week. I can pause optimizations Friday if you want to
get a release out?

**Comment by cxambs** [comment]
That would be nice. Waiting for that release :-)

**Pull request merged**
