### PR TITLE
Fixed TextIO compatibility with 3.6+

### PR DESCRIPTION
**Pull request by ImanHosseini**
Fixing this issue: https://github.com/antlr/antlr4/issues/2611 (and probably https://github.com/antlr/antlr4/issues/2193)
TextIO has moved since Python 3.6 so it should be imported considering the change for new versions.

[I have signed contributor's file: https://github.com/antlr/antlr4/pull/2612]

### CODE REVIEW

**Comment by michaeljquinn** [comment]
When can we get this fix into PyPi

I need this for my app,

**Comment by ericvergnaud** [comment]
@parrt blessed

**Comment by ericvergnaud** [comment]
@ImanHosseini you need to add yourself to the contributors list for this PR to make it

**Comment by michaeljquinn** [comment]
cool, good to hear !!!

**Comment by ImanHosseini** [comment]
> @ImanHosseini you need to add yourself to the contributors list for this PR to make it.
> #2612 is closed so better you do it as part of this PR.

Done!

**Pull request merged**
