### PR TITLE
Feature/gomod4110

### PR DESCRIPTION
**Pull request by jimidle**
feat: #3840  Implement go runtime v4 path correctly so that release tags work.

Though this PR will seem like a huge change, in fact most of the changes are just copying the existing runtime module to a new module path `github.com/antlr/antlr4/runtime/Go/antlr/v4` so that Go runtime tags will actually work in this release.

The actual changes are:

  - Updated documentation
  - Change Go codegen template to use the new `v4` path
  - Change go test suite to use new v4 path
  - Change v4/go.mod to use the new runtime path

*NB* Though the runtime path changes to `v4` the public runtime API has not changed and it is very little work to change
to use the new module path. Most go programmers will know how to do this, but it is also documented.

### CODE REVIEW

**Comment by parrt** [comment]
Looks good to me but let's synchronize so I don't screw this up.  

Oh, sorry emerged something related to the test rig from @KvanTTT and so there's a conflict you might want to resolve quickly.

**Comment by parrt** [comment]
Ok, looking good on Go target...merging!

**Comment by parrt** [comment]
@jimidle shouldn't we delete the non-v4 version of the Go code?

**Comment by jimidle** [comment]
Next release. I want to play it safe for existing projects. When I am sure
that v4 is good, we can then delete the code and clean up the repo.

**Pull request merged**
