### PR TITLE
Initial ParserInterpreter fix for Python3 target

### PR DESCRIPTION
**Pull request by JohnnyonFlame**
This is a set of initial changes in an attempt to update the ParserInterpreter in the Python3 target, however, there are still outstanding issues somewhere that are causing some of the cases in my test suite to fail, namely:

```Python traceback
$ PYTHONPATH="../antlr4/runtime/Python3/src" python3 output/test.py
........................F.F.........
======================================================================
FAIL: testLeftRecursion_interpreter (__main__.InterpreterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "output/test.py", line 201, in testLeftRecursion_interpreter
    testInterp(self, 'testLeftRecursion', parser_mod, lexer_mod, "s", "a+a", "(s (e (e a) + (e a)))")
  File "output/test.py", line 27, in testInterp
    who.assertEqual(tree.toStringTree(parser_mod.T.ruleNames), expect)
AssertionError: '(s (e a + (e a)))' != '(s (e (e a) + (e a)))'
- (s (e a + (e a)))
+ (s (e (e a) + (e a)))


======================================================================
FAIL: testLeftRecursiveStartRule_interpreter (__main__.InterpreterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "output/test.py", line 219, in testLeftRecursiveStartRule_interpreter
    testInterp(self, 'testLeftRecursiveStartRule', parser_mod, lexer_mod, "e", "a+a", "(e (e a) + (e a))")
  File "output/test.py", line 27, in testInterp
    who.assertEqual(tree.toStringTree(parser_mod.T.ruleNames), expect)
AssertionError: '(e a + (e a))' != '(e (e a) + (e a))'
- (e a + (e a))
+ (e (e a) + (e a))


----------------------------------------------------------------------
Ran 36 tests in 0.072s

FAILED (failures=2)
```

I am proposing this push request in hope that I can get an initial review and maybe some help on completing the behavior of this module.
[Here's a little test suite](https://github.com/JohnnyonFlame/antlr4/files/3580407/ParserInterpreterTestSuite.zip) automatically generated from "_tool-testsuite/test/org/antlr/v4/test/tool/TestParserInterpreter.java_", don't mind the code there too much, it's only meant to enable me to tdd with a known set of working examples and known possible regressions.

### CODE REVIEW

**Comment by ericvergnaud** [comment]
Why do you want to change ParserInterpreter ?

**Comment by JohnnyonFlame** [comment]
I was experimenting to get a feel for what it offers and how it performs, noticed some aspects of the Python 3 target seemed to not work on my end and decided to contribute tests and fixes.

Sorry, it's just contributing for the sake of open source.

**Comment by ericvergnaud** [comment]
Hi,

there are already a large number of tests that behave identically across targets, see runtime-testsuite.
Any chances that what you perceive as a bug in the runtime is actually correct behavior and you should be fixing your grammar instead?

Eric

**Comment by JohnnyonFlame** [comment]
I had runtime errors with ParserInterpreter on my end and the included tests in this PR were ported from the Java version if my memory serves me right, I don't recall testing ParserInterpreter with my grammar. Been a while however so I'm not too sure.

**Comment by ericvergnaud** [comment]
Closing this in the absence of an identified bug to fix.

**Pull request closed without merging**
