### PR TITLE
differentiate prefix/postfix type decl.

### PR DESCRIPTION
**Pull request by hanjoes**
not going to make any difference until the Swift target is merged.

### CODE REVIEW

**Comment by sharwell** [comment]
@hanjoes Can you clarify the purpose of this pull request?

**Comment by parrt** [comment]
It is a fix for https://github.com/antlr/antlr4/issues/1168

**Comment by parrt** [comment]
I'm merging manually into a branch parrt/add-postfix-types-in-args so that I can update the tests and everything else also.

**Comment by hanjoes** [comment]
Yeah, its a fix to support the postfix type decl in languages like Swift, while the identifier is delimited from the type by using ":".

**Comment by parrt** [comment]
Manually merged via https://github.com/antlr/antlr4/pull/1365

**Pull request closed without merging**
