### PR TITLE
Windows specific fixes

### PR DESCRIPTION
**Pull request by hs-apotell**
Windows specific fixes

* Set the MSVC runtime library configuration AFTER the option to select CRT is set.
* Add the post build steps only if building tests

Signed-off-by: HS <hs@apotell.com>

### CODE REVIEW

**Comment by hs-apotell** [comment]
@jcking Could you please look into this PR and promote it. This is a short follow up to https://github.com/antlr/antlr4/pull/3663 which you approved.

**Comment by mike-lischke** [comment]
Better @jcking reviews this patch, @parrt.

**Comment by QuantamHD** [comment]
@jcking Can you take a look at this?

**Comment by parrt** [comment]
Hi @hs-apotell could you take a look at the conflict here? Or maybe @QuantamHD?  I have refreshed my C++ knowledge but the build stuff is magic!

**Comment by hs-apotell** [comment]
@parrt Resolved.

**Pull request merged**
