### PR TITLE
Fix placement of @members in Javascript target lexers

### PR DESCRIPTION
**Pull request by tehbone**
When @members is used in the lexer grammar, the content gets placed in an arbitrary location that is out of scope of the generated lexer. The template was updated so the content gets placed in the constructor, allowing for the creation of class members. This is consistent with the placement of members for parser grammars in the Javascript target.

### CODE REVIEW

**Comment by ericvergnaud** [comment]
mmm... this is a breaking change...

**Comment by tehbone** [comment]
Can you elaborate? I do realize that it could impact existing grammars that may use members for lexers in its current form, but to that end I don't believe it sets out to do what it should be doing.

**Comment by ericvergnaud** [comment]
Well one can create a member like this:
MyLexer.prototype.myMethod = function() {};

**Comment by tehbone** [comment]
I'm fine with this being rejected then. I only point out that it is an oddity that parsers have members generated in the constructor while the lexers do not.

**Comment by ericvergnaud** [comment]
True.
May I suggest you run a survey on the google discussion group to find out who uses lexer members in javascript?
If nobody in 2 weeks, we can consider blessing.

**Comment by ericvergnaud** [comment]
@parrt blessed

**Pull request merged**
