### PR TITLE
[Python3] return result instead of None in visitor

### PR DESCRIPTION
**Pull request by jkmar**
Previously ParseTreeVisitor in the visitChildren method returned None when it shouldn't visit the next child, so if you overrode the shouldVisitNextChild you would also have to override the visitChildren method only to change that return statement.

### CODE REVIEW

**Comment by ericvergnaud** [comment]
Hi, thanks for this.
@parrt blessed

**Comment by parrt** [comment]
Does the same  Bug occur in Python 2 as well?

**Comment by ericvergnaud** [comment]
Indeed the same fix needs to be applied.
@jkmar may I ask that you make it part of this PR?

**Comment by jkmar** [comment]
@ericvergnaud sure, I've also applied the same fix to Python 2.

**Pull request merged**
