### PR TITLE
Remove double dots in the filename

### PR DESCRIPTION
**Pull request by michilu**
Some tools are can not handling files that have double dots in the filename.

example:
```console
$ vgo mod -vendor
go: extracting github.com/antlr/antlr4 v0.0.0-20180728001836-7d0787e29ca8
-> unzip go/src/mod/cache/download/github.com/antlr/antlr4/@v/v0.0.0-20180728001836-7d0787e29ca8.zip: malformed file path "runtime/Cpp/demo/Windows/antlr4-cpp-demo/antlr4-cpp-demo-vs2015.vcxproj..filters": double dot
```

Notes: The 'vgo' is a tool for golang.

### CODE REVIEW

**Comment by michilu** [comment]
I found a related issue: #2337

**Comment by rocketbitz** [comment]
can we get this merged in? this is a blocker now for people using `go mod` with go 1.11

**Comment by michilu** [comment]
Workaround for Go modules: Defines a 'replace' section into your `go.mod` file, as below.
```
replace (
  github.com/antlr/antlr4 master => github.com/michilu/antlr4 remove-double-dots-in-the-filename
)
```

**Comment by mike-lischke** [comment]
@parrt This is a pure C++ issue and can be merged without side effects.

**Comment by rocketbitz** [comment]
appreciate getting this merged in. will there be a hotfix release including this? thanks.

**Comment by parrt** [comment]
I'll likely do another release after i finish teaching in oct 18

**Pull request merged**
