### PR TITLE
[C++] Remove unused LexerATNSimulator::match_calls

### PR DESCRIPTION
**Pull request by jcking**
The variable appears to be unused and atomic operations are not exactly free.

### CODE REVIEW

**Comment by mike-lischke** [comment]
I'm not sure, but I believe this is for debugging. @parrt Do you remember what that `match_calls` is for?

**Comment by parrt** [comment]
I can only think that this is for debugging. I notice that it is not in the job a target. @ericvergnaud  any idea what `match_calls` is for other than debugging?  I see it in these targets

Screen Shot 2022-03-08 at 4 19 12 PM

@jcking care to fix the other targets in parallel?  if not I can easily make a separate PR

**Review by mike-lischke — APPROVED** [review]

**Comment by ericvergnaud** [comment]
I believe it is for debugging, particularly useful across targets to check if the algorithm behaves the same for a given grammar and input

**Comment by parrt** [comment]
ah! Ok, well, I hope we are beyond most issue with the ATN!  :)

**Pull request merged**
