### PR TITLE
Update base image to add multi-arch support

### PR DESCRIPTION
**Pull request by Prashant-Jagtap**
Added support for s390x
Also updated base image for multi-arch support.

### CODE REVIEW

**Comment by Prashant-Jagtap** [comment]
Hi team, could you please have a look at these changes?

**Comment by parrt** [comment]
@ericvergnaud do you know docker enough to look at this?

**Comment by ericvergnaud** [comment]
@Prashant-Jagtap Hi, thanks for this.
It seems that adoptopenjdk images are deprecated.
Shouldn't we be using eclipse-temurin images instead ?
Such eclipse-temurin:11 ?

**Comment by Prashant-Jagtap** [comment]
Hi @ericvergnaud 
Thanks for an update. I have updated the PR as per the suggestion. Please have a look.

**Comment by Prashant-Jagtap** [comment]
Hi @ericvergnaud ,  could you please have a look at these changes ?

**Comment by ericvergnaud** [comment]
Hi
Thanks for this, looks good to me.
Any chance you could add a test that instantiates the image and runs the tool such that it proves that the docker image satisfies all antlr4 requirements ?

**Comment by Prashant-Jagtap** [comment]
Hi @ericvergnaud , as suggested executed the [complete example](https://github.com/antlr/antlr4/blob/master/doc/go-target.md#complete-example) using the antlr4 image. The output obtained is as expected. Logs are attached for reference, Please have a look. Thanks.

```
$go/src/github.com/antlr/antlr4# mkdir parser
$go/src/github.com/antlr/antlr4# cd parser/
$go/src/github.com/antlr/antlr4/parser# ls
$go/src/github.com/antlr/antlr4/parser# wget https://raw.githubusercontent.com/antlr/grammars-v4/master/json/JSON.g4
--2023-05-10 02:55:29--  https://raw.githubusercontent.com/antlr/grammars-v4/master/json/JSON.g4
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 958 [text/plain]
Saving to: ‘JSON.g4’

JSON.g4                            100%[================================================================>]     958  --.-KB/s    in 0s

2023-05-10 02:55:29 (81.9 MB/s) - ‘JSON.g4’ saved [958/958]

$go/src/github.com/antlr/antlr4/parser# ls
JSON.g4
$go/src/github.com/antlr/antlr4/parser# docker run --rm -u $(id -u ${USER}):$(id -g ${USER}) -v `pwd`:/work antlr4:latest -Dlanguage=Go JSON.g4
$go/src/github.com/antlr/antlr4/parser# ls
json_base_listener.go  JSON.interp    JSONLexer.interp  json_listener.go  JSON.tokens
JSON.g4                json_lexer.go  JSONLexer.tokens  json_parser.go
$go/src/github.com/antlr/antlr4/parser# cd ..
$go/src/github.com/antlr/antlr4# vi main.go
$go/src/github.com/antlr/antlr4# vi input.json
$go/src/github.com/antlr/antlr4# go get github.com/antlr/antlr4/runtime/Go/antlr/v4
go: downloading github.com/antlr/antlr4/runtime/Go/antlr/v4 v4.0.0-20230321174746-8dcc6526cfb1
go: downloading github.com/antlr/antlr4/runtime/Go/antlr v1.4.10
go: downloading golang.org/x/exp v0.0.0-20220722155223-a9213eeb770e
go: added github.com/antlr/antlr4/runtime/Go/antlr/v4 v4.0.0-20230321174746-8dcc6526cfb1
go: added golang.org/x/exp v0.0.0-20220722155223-a9213eeb770e
$go/src/github.com/antlr/antlr4# go run main.go input.json
{"name":"antlr4"}<EOF>
{"name":"antlr4"}
{"name":"antlr4"}
"name":"antlr4"
"antlr4"
$go/src/github.com/antlr/antlr4# cat input.json
{
        "name": "antlr4"
}
$go/src/github.com/antlr/antlr4# vi input.json
$go/src/github.com/antlr/antlr4# cat input.json
{
        "a": "1"
}
$go/src/github.com/antlr/antlr4# go run main.go input.json
{"a":"1"}<EOF>
{"a":"1"}
{"a":"1"}
"a":"1"
"1"
$go/src/github.com/antlr/antlr4#
```

**Comment by ericvergnaud** [comment]
@parrt blessed

**Pull request merged**
