### PR TITLE
fix: use 32bit murmur3 same with java, implement array2dhashset which…

### PR DESCRIPTION
**Pull request by jjeffcaii**
Hi All:

This PR fixes several serious performance problem in Go runtime:
1. the `murmur3` implementation in Go SDK has some problem, it's not consistent with Java.
2. some hash code implementation is not correct, some of them are not consistent with Java.
3. the `Set` implementation which based on `map[int][]interface{}` has poor performance, it is not consistent with Java,  I implement the `Array2DHashSet` instead, this implementation is same with Java.
4. the hash cache is now fixed for `PredictionContext`.

Many problems have been raised, and I think this PR will fix them, please check these issues:
https://github.com/antlr/antlr4/issues/2888
https://github.com/antlr/grammars-v4/issues/2272
https://github.com/antlr/antlr4/issues/2152

The core problem in Golang runtime: it wastes too much time on hash code computing because of the incorrect `Murmur3` and `Set` and `hasher` implementation. Compare the Java and the original Go runtime, Go computes murmur3 *~80,000,000* times, but the Java runtime only *~600,000* times.

Here's my benchmark in my MBP '16 2019, the g4 files are copied from https://github.com/antlr/grammars-v4/tree/master/sql/mysql/Positive-Technologies, the original Go runtime cost *4.8s*, and this PR costs *171ms*.

Benchmark:

```go
	begin := time.Now()
	var sql string

	sql = "SELECT DATE_FORMAT(IF(COUNT(*)>0,'2021-01-02','2020-01-01'),'%Y') AS cc FROM student WHERE uid BETWEEN 1 AND 5"
	//sql = "SELECT 1"

	is := antlr.NewInputStream(sql)
	lexer := p.NewMySqlLexer(antlrx.NewCaseChangingStream(is, true))
	//lexer := p.NewMySqlLexer(is)

	ts := antlr.NewCommonTokenStream(lexer, antlr.TokenDefaultChannel)

	mp := p.NewMySqlParser(ts)
	//mp.GetInterpreter().SetPredictionMode(antlr.PredictionModeSLL)
	mp.RemoveErrorListeners()
	mp.SetErrorHandler(antlr.NewBailErrorStrategy())

	_ = mp.Root()

	fmt.Println("cost:", time.Since(begin)) 
        // COST:
        // BEFORE: 4.853549529s
        // AFTER: 171ms
        // JAVA: 20ms
```

### CODE REVIEW

**Comment by parrt** [comment]
Can somebody in Go area review? @davesisson @easonlin404 @pboyer ?

**Comment by jjeffcaii** [comment]
Is anyone focusing on it?

**Comment by parrt** [comment]
Can any of the Go folks take a look @davesisson @easonlin404 @pboyer ?   I'm afraid I'm not qualified

**Comment by KvanTTT** [comment]
Maybe somebody else can review, not necessary Go folks? @ericvergnaud ?

**Comment by ericvergnaud** [comment]
I'm a bit skeptical re the inconsistent use of MurmurHash (why is not used by hashATNConfig ?).
That said, I believe in tests ans as long as the tests pass and there is a performance improvement I can't think of any reason to reject this PR.

**Comment by jjeffcaii** [comment]
@ericvergnaud Thanks for the review.

The main difference of murmur3 is that I changed it to 32bit like the java codes, and the `hashATNConfig` is copied from java runtime:

https://github.com/antlr/antlr4/blob/ce3c483ec50592d8e265c644e31ec5e8261c87fb/runtime/Java/src/org/antlr/v4/runtime/atn/ATNConfigSet.java#L40-L63

To be honest, I am not familiar with the core antlr implementation, most codes were translated from the Java runtime, try my best. Hope it can help those who are using the Go runtime.

**Comment by parrt** [comment]
I concur with @ericvergnaud .  The tests pass and improves performance; it also brings it in line with what ANTLR core does. Sam Harwell worked really hard to get that performance up, and using that hash function was important. merging.

**Pull request merged**
