### PR TITLE
Fix for multithreading issues

### PR DESCRIPTION
**Pull request by mike-lischke**
Closes issue #1435.

### CODE REVIEW

**Comment by parrt** [comment]
@mike-lischke looks like g++ is failing. do we support g++?

**Comment by mike-lischke** [comment]
I don't know what's wrong there. Linux is not my area of expertise. Whoever changed the Travis config should look again and fix it.

**Comment by parrt** [comment]
@mike-lischke current master passes so it must be something introduced here. I'll look.

**Comment by parrt** [comment]
Hi @mike-lischke, please see log https://travis-ci.org/antlr/antlr4/jobs/183449684 for compile errors with g++-5 that I kicked off at travis.

**Comment by gaulouis** [comment]
Can I try a clone ? What is the URL of the branche ?

**Comment by mike-lischke** [comment]
et voilá :-) here we go

I'm still new to Travis and misinterpreted the matrix changes as something that changed the used compiler for the tests (gcc instead of clang). That's why I asked for someone else to fix it, sorry for that. At the end it was just a simple problem (missing header include).

**Pull request merged**
