### PR TITLE
Typescript support for antlr4 JavaScript runtime

### PR DESCRIPTION
**Pull request by BurtHarris**
Per issue  #1254, this adds TypeScript support to a subset of the JavaScript runtime, in the new file index.d.ts in the JavaScript runtime src directory.  

Other changes on this branch include previously submitted changes to integrate runtime with NPM, and tool settings for NPM TypeScript, and Tslint integration.

### CODE REVIEW

**Comment by BurtHarris** [comment]
I've learned more at this point, withdrawing the pull request.   Will resubmit later...

**Comment by Marais** [comment]
When will the typescript index.d.ts file be merged into master?
Would be great to have it.

**Comment by BurtHarris** [comment]
Sorry @Marais , this effort got more involved than I had originally expected.   I have outside commitments that prevent me from spending enough time on it to even estimate.   

You are welcome to copy the  `index.d.ts` file from branch **typescript** at https://github.com/BurtHarris/antlr4/tree/typescript/runtime/JavaScript/src/antlr4, but this was just the start, insufficent to write a reasonable ANTLR application in Typescript.

**Comment by Marais** [comment]
Thanks for the reply. I think I will use antlr without the d.ts.

**Pull request closed without merging**
