### PR TITLE
Cpp runtime generation fixes, when treat warnings as errors enabled

### PR DESCRIPTION
**Pull request by binaryzebra**
Hello,

I've tried to use your project and found a few minor issues in C++ runtime generation target. It does not work for C++ projects when warnings treated as errors. I am new to ANTLR, and I've tried to fix it. Seems I've found all places, at least which I've used. 

Best regards,
Vitaliy

### CODE REVIEW

**Review by mike-lischke — APPROVED** [review]

**Comment by mike-lischke** [comment]
@parrt This C++ fix is ready to be merged.

**Comment by parrt** [comment]
Hi @binaryzebra  could you please sign the contributors.txt file?  Also it looks like we have a conflict with Cpp.stg how so you might have to re-base.

**Comment by parrt** [comment]
Hi @binaryzebra I can't merge this until you resolve conflicts. thanks.

**Comment by mike-lischke** [comment]
@parrt Seems the author is not willing to sign, so you can close this PR.

**Pull request closed without merging**
