### PR TITLE
maven-compiler-plugin 3.8.1

### PR DESCRIPTION
**Pull request by sullis**
(latest version)

### CODE REVIEW

**Comment by sullis** [comment]
contributors.txt
https://github.com/antlr/antlr4/pull/2648

**Comment by sharwell** [comment]
Is the previous one causing a problem?

**Comment by sullis** [comment]
> Is the previous one causing a problem?

maven-compiler-plugin 3.8.1 is compatible with Java 8, Java 11, etc

**Comment by parrt** [comment]
I will pull in these changes and see if everything still works :)

**Pull request merged**
