### PR TITLE
add license prefix

### PR DESCRIPTION
**Pull request by ericvergnaud**

### CODE REVIEW

**Comment by KvanTTT** [comment]
Maybe remove such headers from all files? Why is such duplication required? Also, we are constantly forgetting to update the year in all such headers, there are a lot of files with 2017 year.

**Comment by parrt** [comment]
I think all files need the copyright protection a lawyer told me some years ago.

**Comment by KvanTTT** [comment]
Maybe at least to remove end year? It's tedious to update it every time.

**Comment by parrt** [comment]
Agreed that it is tedious. Unfortunately, I don't know what the law says about whether we need a date on there...

**Pull request merged**
