### PR TITLE
[CSharp] #2021 fixes nuget packaging options to avoid missing dll exceptions

### PR DESCRIPTION
**Pull request by kaedvann**
@ericvergnaud Hi,
I modified csproj options a bit, now I can get a working nuget package locally without the issue we described in #2021.
I added .net 3.5 as a target to "main" csproj along with netstandard, since it's easier to keep track of requirements for both sets of api's when editing code and, ideally, both targets can be packed into a nuget package with a single command. Right now it's possible only on Windows via `msbuild /t:pack` or Visual Studio; unfortunately, due to https://github.com/Microsoft/msbuild/issues/1333, right now `dotnet build pack` does not work for .net 3.5 target the way it should, so I adjusted the existing script to create packages from .nuspec and different solutions for different targets.

### CODE REVIEW

**Comment by ericvergnaud** [comment]
Hey! 
thanks for the help, much appreciated.
Up to now I've always released from my mac using Mono.
Not sure if build-nuget-package.sh is of much use on a winter box..
Would it be too much to ask if you can provide a powershell script for releasing from Windows?

**Comment by kaedvann** [comment]
Nah, it's a single msbuild call, so that's ok, I added the script, although the old one should continue to work with mono, it's just less convenient. It's cumbersome to have two ways to make a package, however.

**Comment by ericvergnaud** [comment]
Thanks
From your previous comment; I thought that due to Microsoft/msbuild#1333 packaging was only possible on windows. Hence my ask for the script.
What am I missing?

**Comment by kaedvann** [comment]
Sorry, didn't make myself clear enough. It's not about windows, it's an issue with `dotnet cli` . You can't use it both on windows and Linux to build projects targeting .net 3.5, you need full msbuild for it, or, in your case, xbuild from mono. So I edited your existing script to make dotnet build only standard target (explicitly setting it in build command parameters), the rest is still done by xbuild and nuget. The downside is that you have two ways to make a package and three sln/csproj files, so it gets a bit confusing, but the only way to get rid of them are either dropping .net 3.5 support (in that case you just use single csproj and `dotnet build pack` on all platforms, or dropping requirement to be able to build package with both targets on non-windows machine. Anyone will still be able to compile netstandard target on any platform, but windows will be required to make nuget package with both standard and net3.5 dll's.

**Comment by kaedvann** [comment]
Or you leave everything as is, this way  you can build everything everywhere, but have to cope with multiple csproj's and duplicating package metadata in nuspec and csproj.

**Comment by ericvergnaud** [comment]
Ok I guess we will publish from windows until MS fixes #1333 .
Then we'll get back to a single unified way that works on all platforms.
Again, many thanks for your help with this.
@parrt are you comfortable with this?

**Comment by parrt** [comment]
@ericvergnaud can you explain the changes for me? Is it just packaging? new name?

**Comment by kaedvann** [comment]
if you are comfortable with publishing from windows, excess csproj/sln should probably be removed to reduce clutter. It will still be possible to compile .net standard version on any os supported by .net core.

@parrt hi. It's about more simple packaging process (all metadata in single file, both target frameworks are defined in single csproj file, single msbuild call for all restore/build/pack operation); defining both target frameworks (.net 3.5 and .net standard) in single csproj allows IntelliSense to perform analysis against both targets, thus preventing you from introducing changes incompatible with any of the platforms.
During build both targets will produce dll with the same name, yes, since it's more correct behaviour when targeting multiple runtimes and working with .net standard api's (or you'll get weird dll not found errors depending on runtime you use to build an app transitively dependent on this library, that's what #2021 was initially about).

**Comment by parrt** [comment]
Hmm...well,I really need to rely on you guys for correct C# behavior and packaging. Am I still able to build from Mac?   How does this affect the nuget packages we have now?

**Comment by kaedvann** [comment]
You can build from any platform supported by .net core tools (including Mac) using command `dotnet build -c Release -f netstandard1.3 Antlr4.dotnet.sln`. You'll get working dll targeting .net standard, which you can consume from both mono and .net core projects. I'm not sure about building for .net 3.5 using mono, I don't know if xbuild supports new csproj format, but this should not be an issue anyway since libraries built for .net standard are supported by current mono version. 
As for nuget package, supported platforms will remain the same (basically everything .net related after 3.5), but the issue my co-worker described in #2021 will be fixed.

**Comment by parrt** [comment]
Ok, i'm not sure exactly what @ericvergnaud  wants me to make a decision on. I don't know much about the C# ecosystem.

**Comment by ericvergnaud** [comment]
@parrt our current CI is not affected, but our release process to Nuget is.
Due to bugs/limitations, we need to publish from Windows, and I want to make sure you are comfortable with this.

**Comment by parrt** [comment]
Ah! Hmm...I *think* I can get a Windows VM running on my mac. would it require installation of all M$ dev tools and such or just nuget stuff?

**Comment by ericvergnaud** [comment]
I believe the community edition suffices:
https://www.visualstudio.com/fr/thank-you-downloading-visual-studio/?sku=Community&rel=15
@kaedvann can you confirm?

**Comment by kaedvann** [comment]
Yes, community edition will work, you really require only msbuild anyway. Oh, and to enable building for .net 3.5 on modern windows you will need to explicitly enable it in "Windows Features", like described [here](https://docs.microsoft.com/en-us/dotnet/framework/install/dotnet-35-windows-10), and add .net 3.5 sdk during visual studio install (they improved installer in 2017, so you'll only need to check relevant sdk's in 'individual components' tab)

**Comment by parrt** [comment]
Ok, So there is no name change or anything like that on the visible nuget product?

**Comment by parrt** [comment]
Ok, i have windows 10 x64 in vmware with Visual Studio Comm 2015. Is that sufficient?

**Comment by ericvergnaud** [comment]
Can you try from cmd line in c# folder:
Powershell ./build-nuget.ps1
(Not sure about the exact script name)

Envoyé de mon iPhone

**Comment by kaedvann** [comment]
@parrt just to make sure, is it visual studio 2015 or visual studio 15 (which is in fact visual studio 2017, they need some consistency on naming)? If really is vs 2015 (it will have version id like 14.0.25420.10 in "about" window), it will not work. If the version shown is something like 15.3.3 or 15.3.4, than it's fine. You'll need to add msbuild to PATH (it'll be something like `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin`) and then execute the script I added (runtime/CSharp/runtime/CSharp/Build-NugetPackage.ps1) from Powershell.

**Comment by parrt** [comment]
Pretty sure it's 2015 not 15. Heh, will the mac version of VS work?

**Comment by ericvergnaud** [comment]
Not sure about the mac
I installed https://www.visualstudio.com/thank-you-downloading-visual-studio/?sku=Community&rel=15 <https://www.visualstudio.com/thank-you-downloading-visual-studio/?sku=Community&rel=15>
That’s VS2017 community, so should work

**Comment by parrt** [comment]
ok, i'm away from work machine today so will try later.

**Comment by kaedvann** [comment]
@parrt hi, any luck with setting up renewed build?

**Comment by parrt** [comment]
Okay it looks like I have Visual Studio Community 2015

screen shot 2017-10-09 at 4 42 03 pm

 I am downloading 2017 now.

**Comment by parrt** [comment]
Ok, now says:
screen shot 2017-10-09 at 4 48 59 pm

Do I need any other installed products?

**Comment by kaedvann** [comment]
VS is fine, we just need to ensure you have necessary sdk's and _stuff_
1) ensure msbuild is added to PATH, is should be accessible from command line (it is installed with visual studio, just not added to PATH automatically)
2) ensure .net 3.5 is enabled in Programs & Features (I described it a bit [earlier](https://github.com/antlr/antlr4/pull/2024#issuecomment-333442684))
3) .net core sdk should be installed (`dotnet --version` works in command line and shows something meaningful)

Hm, that should be it.

**Comment by parrt** [comment]
Ok, enabled .net 3.5. and msbuild appears to work. I had to reboot after setting the path. hahaha. just like old times.

screen shot 2017-10-10 at 12 24 03 pm

.net core sdk shows 2.0.0 from prompt. Sound good?

**Comment by kaedvann** [comment]
Yup, now the script `runtime/CSharp/runtime/CSharp/Build-NugetPackage.ps1` should create you a nuget package with both targets and all relevant metadata filled.

**Comment by kaedvann** [comment]
@parrt Hi, sorry to bother you, but have you had any lack with packaging?

**Comment by parrt** [comment]
hiya. just finished school semester and today off to 3 or 4 day vacation. i hope to start antlr stuff again on Monday

**Comment by parrt** [comment]
Doesn't this means I can no longer test C# target on my mac and can no longer use the target on Mac or Linux? I'm just extrapolating from the fact that we cannot build it from UNIX. Is this true?

**Comment by kaedvann** [comment]
No, of course not, it would be quite inappropriate of me. You can explicitly build only the version supported by Linux and Mac (using a command 'dotnet build -c Release -f netstandard1.3 Antlr4.dotnet.sln', I'll also make sure there is a build script in repository to do this), you'll receive a dll which you can consume from Mono >= 4.6 or .NET Core >= 1.0. And the nuget package will still be compatible with everything supported right now, the build limitation is due to .NET Framework 3.5 not being a first-class citizen on Linux and Mac (and, in fact, in modern Windows as well, but that's irrelevant). If msbuild team fixes the bug I mentioned and msbuild would be able to use mono packages to build .net 3.5 on any platform, you would use the same build script on any platform. 
Or maybe you'll drop support for 3.5 some day and build just standard version.

**Comment by parrt** [comment]
ok, sounds good. Could you update the [doc](https://github.com/antlr/antlr4/blob/master/doc/releasing-antlr.md) for me so I know how to build and push to nuget?   Perhaps check "Creating and packaging the assembly" section to see if it still makes sense for building locally as well? thanks!

**Comment by parrt** [comment]
@kaedvann when I run it, it brings up notepad with

```
msbuild /target:restore /target:rebuild /target:pack /property:Configuration=Release .\Antlr4.dotnet.sln
```

when I run that I get:

```
C:\Users\parrt\source\repos\antlr4>msbuild /target:restore /target:rebuild /target:pack /property:Configuration=Release runtime\CSharp\runtime\CSharp\Antlr4.dotnet.sln
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 10/23/2017 1:59:12 PM.
Project "C:\Users\parrt\source\repos\antlr4\runtime\CSharp\runtime\CSharp\Antlr4.dotnet.sln" on node 1 (restore;rebuild;pack target(s)).
ValidateSolutionConfiguration:
  Building solution configuration "Release|Any CPU".
Project "C:\Users\parrt\source\repos\antlr4\runtime\CSharp\runtime\CSharp\Antlr4.dotnet.sln" (1) is building "C:\Users\parrt\source\repos\antlr4\runtime\CS
harp\runtime\CSharp\Antlr4.Runtime\Antlr4.Runtime.dotnet.csproj" (2) on node 1 (restore target(s)).
C:\Users\parrt\source\repos\antlr4\runtime\CSharp\runtime\CSharp\Antlr4.Runtime\Antlr4.Runtime.dotnet.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' s
pecified could not be found.
Done Building Project "C:\Users\parrt\source\repos\antlr4\runtime\CSharp\runtime\CSharp\Antlr4.Runtime\Antlr4.Runtime.dotnet.csproj" (restore target(s)) --
 FAILED.

Done Building Project "C:\Users\parrt\source\repos\antlr4\runtime\CSharp\runtime\CSharp\Antlr4.dotnet.sln" (restore;rebuild;pack target(s)) -- FAILED.


Build FAILED.

"C:\Users\parrt\source\repos\antlr4\runtime\CSharp\runtime\CSharp\Antlr4.dotnet.sln" (restore;rebuild;pack target) (1) ->
"C:\Users\parrt\source\repos\antlr4\runtime\CSharp\runtime\CSharp\Antlr4.Runtime\Antlr4.Runtime.dotnet.csproj" (restore target) (2) ->
  C:\Users\parrt\source\repos\antlr4\runtime\CSharp\runtime\CSharp\Antlr4.Runtime\Antlr4.Runtime.dotnet.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk'
 specified could not be found.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.53

C:\Users\parrt\source\repos\antlr4>
```

**Comment by parrt** [comment]
In powershell, it can't find msbuild.

**Comment by kaedvann** [comment]
@parrt Huh, that's weird. 
...
Search a bit around msbuild issues, got the impression that vs enterprise (which I use) does some additional magic in connecting old build tools to new ones. Completely unexpected. Anyway, I found this workaround https://github.com/Microsoft/msbuild/issues/2532, could you please test it?
As for the doc, I would update it as soon as we get you to reliably build the package. Guess my machine is so .net oriented, some stuff just works for me without much thought. 😆

**Comment by ewanmellor** [comment]
Was this change merged into antlr4/master?  I see the "Merge branch 'master' into master" line above from a day or two ago, but I don't see these changesets in the repo.  Did they get reverted or something?

The reason I ask is, all the AppVeyor tests are failing now, and it happened apparently at the point of this merge.

**Comment by kaedvann** [comment]
I think @parrt merged current master into my branch, this PR is still open and no commits by me are present in antlr4/master.

**Comment by parrt** [comment]
I was manually testing this on Windows by pulling @kaedvann 's branch to a test local branch. I'm going to test his workaround to my problem tomorrow as I'm not going to the office today.

**Comment by ewanmellor** [comment]
I think that the AppVeyor test failures were coincidental; AppVeyor also rolled out new images this week.  I have filed PR #2077 to address that.

**Comment by parrt** [comment]
crap. Didn't get to it and won't be back to the office until Monday where I have everything installed on the Windows instance.

**Comment by kaedvann** [comment]
@parrt hi, any updates?

**Comment by parrt** [comment]
Ok, found solution [here](https://social.msdn.microsoft.com/Forums/en-US/85407413-c583-48e7-998e-f83feab6267e/msbuild-is-not-recognized-as-internal-or-external-command?forum=msbuild). now new dos and powershell Prompts both find it as build engine version 4.6.1586.0.

Blech. no i get:

```
PS C:\Users\parrt\source\repos\antlr4> runtime/CSharp/runtime/CSharp/Build-NugetPackage.ps1
runtime/CSharp/runtime/CSharp/Build-NugetPackage.ps1 : File
C:\Users\parrt\source\repos\antlr4\runtime\CSharp\runtime\CSharp\Build-NugetPackage.ps1 cannot be loaded because
running scripts is disabled on this system. For more information, see about_Execution_Policies at
http://go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ runtime/CSharp/runtime/CSharp/Build-NugetPackage.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

yuck. now this:

```
PS C:\Users\parrt> Set-ExecutionPolicy -scope CurrentUser
cmdlet Set-ExecutionPolicy at command pipeline position 1
Supply values for the following parameters:
ExecutionPolicy: unrestricted
```

Same problem as before. can't find something.

```
PS C:\Users\parrt\source\repos\antlr4> msbuild /target:restore /target:rebuild /target:pack /property:Configuration=Rele
ase .\runtime\CSharp\runtime\CSharp\Antlr4.dotnet.sln
Microsoft (R) Build Engine version 4.6.1586.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 11/7/2017 2:27:27 PM.
Project "C:\Users\parrt\source\repos\antlr4\runtime\CSharp\runtime\CSharp\Antlr4.dotnet.sln" on node 1 (restore;rebuild
;pack target(s)).
ValidateSolutionConfiguration:
  Building solution configuration "Release|Any CPU".
C:\Users\parrt\source\repos\antlr4\runtime\CSharp\runtime\CSharp\Antlr4.dotnet.sln.metaproj : error MSB4057: The target
 "restore" does not exist in the project. [C:\Users\parrt\source\repos\antlr4\runtime\CSharp\runtime\CSharp\Antlr4.dotn
et.sln]
Done Building Project "C:\Users\parrt\source\repos\antlr4\runtime\CSharp\runtime\CSharp\Antlr4.dotnet.sln" (restore;reb
uild;pack target(s)) -- FAILED.


Build FAILED.

"C:\Users\parrt\source\repos\antlr4\runtime\CSharp\runtime\CSharp\Antlr4.dotnet.sln" (restore;rebuild;pack target) (1)
->
  C:\Users\parrt\source\repos\antlr4\runtime\CSharp\runtime\CSharp\Antlr4.dotnet.sln.metaproj : error MSB4057: The targ
et "restore" does not exist in the project. [C:\Users\parrt\source\repos\antlr4\runtime\CSharp\runtime\CSharp\Antlr4.do
tnet.sln]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.54
PS C:\Users\parrt\source\repos\antlr4>
```

**Comment by kaedvann** [comment]
Huh, that wasn't the best solution since you now got an ancient msbuild which does not support new .NET Core tools. 

Anyway, perhaps that was not a good idea, with you being not very familiar with .NET world and its quirks, maybe it's best to leave build system as is for now since right now it solves the problem of getting a working package. 

So, what if you try running `runtime/CSharp/runtime/CSharp/build-nuget-package.sh` script on your mac in comfortable environment? If it works as it should and produces good-looking nuget package, I can live with that. In that case I'll verify the document about building process and ensure it's up to date, make sure all CI hooks work, clean up this branch and you will be able to painlessly merge it. Really sorry about all your trouble, it's a pity it didn't result in improvement I hoped for.

**Comment by parrt** [comment]
Yeah, this is pretty painful. Even on mac after 20 minutes installing stuff I get:

```bash
beast:~/antlr/code/antlr4 $ runtime/CSharp/runtime/CSharp/build-nuget-package.sh
Step 1: Building .NET 3.5 DLL

>>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<

XBuild Engine Version 14.0
Mono, Version 5.4.0.0
Copyright (C) 2005-2013 Various Mono authors
MSBUILD: error MSBUILD0000: Project file 'Antlr4.mono.sln' not found.
Step 2: Building .NET Core DLL
MSBUILD : error MSB1009: Project file does not exist.
Switch: Antlr4.dotnet.sln
MSBUILD : error MSB1009: Project file does not exist.
Switch: Antlr4.dotnet.sln
Step 3: Packaging both DLLs into a single nuget package
Attempting to build package from 'Package.nuspec'.
Could not find file "/Users/parrt/antlr/code/antlr4/Package.nuspec"
```

**Comment by parrt** [comment]
Even with msbuild I get:

```
beast:~/antlr/code/antlr4 $ find . -name *.nu*
./build/Antlr4.nuspec
./build/Antlr4.Runtime.nuspec
./build/Antlr4.VS2008.nuspec
./runtime/CSharp/build/Antlr4.nuspec
./runtime/CSharp/build/Antlr4.Runtime.nuspec
./runtime/CSharp/build/Antlr4.VS2008.nuspec
./runtime/CSharp/runtime/CSharp/Package.nuspec
./runtime-testsuite/target/classes/CSharp/build/Antlr4.nuspec
./runtime-testsuite/target/classes/CSharp/build/Antlr4.Runtime.nuspec
./runtime-testsuite/target/classes/CSharp/build/Antlr4.VS2008.nuspec
./runtime-testsuite/target/classes/CSharp/runtime/CSharp/Package.nuspec
beast:~/antlr/code/antlr4 $ vi runtime/CSharp/runtime/CSharp/build-nuget-package.sh
beast:~/antlr/code/antlr4 $ runtime/CSharp/runtime/CSharp/build-nuget-package.sh
Step 1: Building .NET 3.5 DLL
Microsoft (R) Build Engine version 15.4.0.0 (master/f296e67b Thu Sep 21 19:38:16 EDT 2017) for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: Antlr4.mono.sln
Step 2: Building .NET Core DLL
MSBUILD : error MSB1009: Project file does not exist.
Switch: Antlr4.dotnet.sln
MSBUILD : error MSB1009: Project file does not exist.
Switch: Antlr4.dotnet.sln
Step 3: Packaging both DLLs into a single nuget package
Attempting to build package from 'Package.nuspec'.
Could not find file "/Users/parrt/antlr/code/antlr4/Package.nuspec"
```

**Comment by kaedvann** [comment]
Looks like an issue with relative paths to me, maybe if you navigate to `runtime/CSharp/runtime/CSharp/` and run the script from there, it will work. Anyway, this part didn't really change and it should work the same as before. 

But, as a matter of fact, I have a much better idea I should have thought about sooner. I think I can fiddle with appveyor and make it produce nuget package as a build artifact. You can download it and publish if needed, and, more importantly, it requires one time setup, it will be documented in appveyor settings and will work for everyone. I think I'll look into it during the weekend.

**Comment by parrt** [comment]
Wow! Great idea! if we could appveyor to build all the artifacts, that would be awesome.

**Comment by xied75** [comment]
Other projects has been doing this, see if this helps:
https://github.com/icsharpcode/SharpZipLib/blob/master/appveyor.yml.old

**Comment by kaedvann** [comment]
@xied75 that was helpful, thank you. 
@parrt Hi, I got appveyor to produce [nuget packages] (https://ci.appveyor.com/project/parrt/antlr4/build/4.7.1-SNAPSHOT+AppVeyor.1350/artifacts)
I also updated the doc about releasing and removed unnecessary `package.nuspec` to avoid confusion. So it looks like you can publish the package from any platform as long as appveyor works and you have `nuget.exe`.
I tried to remove other excess .csproj files, but they are somehow used in testing, which I couldn't completely figure out and rewrite to new csproj, so I'll guess they'll live till next improvement attempt.

**Comment by parrt** [comment]
great! so if @ericvergnaud signs off on this I'll merge. I can see the artifact :)

**Comment by kaedvann** [comment]
Has been a while. @ericvergnaud ?

**Comment by ericvergnaud** [comment]
Sorry missed this
I’ll look into it this weekend

Envoyé de mon iPhone

**Comment by ericvergnaud** [comment]
@parrt if it works for you, it works. blessed

**Comment by parrt** [comment]
Seems to work and I downloaded an artifact, though I didn't test the artifact as I didn't know immediately how to test it. @kaedvann can you verify that the artifact at appveyor is correct?

**Comment by parrt** [comment]
@kaedvann Hmm...something is wrong with the C# build on travis: https://travis-ci.org/antlr/antlr4/jobs/307183842 can you take a look?

**Comment by parrt** [comment]
Cool. i just merged that one and this one. thanks VERY much for pushing this through!

**Comment by kaedvann** [comment]
Great! But I still would like to answer @parrt . Yes, I checked the produced artifact, it seemed to resolve the initial issue this PR was about. About testing - NuGet has a command to install package from local file, something like `Install-Package SomePackage -Source C:\PathToThePackageDir\`. If you have a test project or something, you could add this nuget to the project and run some checks. Since the packages contains two dll's, you'll need to run the tests both on full framework (Mono or Windows, shouldn't matter) or .NET Core runtime. Oh, and as the package is in fact a zip-archive, you could unpack it and check .nuspec inside to ensure all the metadata about the package is correctly filled (I checked that too, but still, anything can happen).
Look forward to seeing this updated package on nuget. :)

**Comment by xied75** [comment]
@parrt @ericvergnaud I wonder should we version the new nuget package to e.g. 4.7.2? So that it won't replace the current 4.7.1 to avoid breaking already running builds.

**Comment by ericvergnaud** [comment]
Hi
There is no plan to replace the current package (if that’s even possible which would be frightening)

Envoyé de mon iPhone

**Comment by parrt** [comment]
Oh right we did some weird thing with numbering to get out a release. can we do 4.7.1.1?

**Comment by ericvergnaud** [comment]
Definitely 

Envoyé de mon iPhone

**Comment by xied75** [comment]
Not that good if considering SemVer is not using the 4th number.

**Comment by parrt** [comment]
Yeah but better than 4.7.2 which would mean 4.7.1 ;)

**Comment by parrt** [comment]
@ericvergnaud @kaedvann can you alter the build config for 4.7.1.1? I'd like to push out 4.7.1 soon. thanks!

**Comment by kaedvann** [comment]
@parrt it is only the <Version> node in the `Antlr4.Runtime.dotnet.csproj` file. No other adjustments required

**Comment by parrt** [comment]
Ok, done: https://github.com/antlr/antlr4/commit/b9adef5878c5b84eb9b70bad2df56334fb7e1b9e

**Pull request merged**
