### PR TITLE
Runtime tests fixes (C++, Python, PHP, C#)

### PR DESCRIPTION
**Pull request by KvanTTT**
* Set up C++ runtime tests on Windows
* Add scripts for testing C++ on Windows
* Fix python and php tests running from IDE

### CODE REVIEW

**Comment by KvanTTT** [comment]
Windows machine requrires installed Visual Studio 2022 or 2019, but I can't mange it because runner is self-hosted. @ericvergnaud could you please install [Visual Studio 2022Community](https://visualstudio.microsoft.com/vs/community/) (it's free) to the default directory `C\Program Files`?

**Comment by KvanTTT** [comment]
Unfortunately I can't install msbuild on Windows using chocolatey because of denied access

```
C:\ProgramData\chocolatey\bin\cinst.exe visualstudio2022-workload-vctools -y
```

@ericvergnaud is it possible to install free [Visual Studio Community 2022](https://visualstudio.microsoft.com/vs/community/) on self-hosted Windows machine? Msbuild is being detected automatically.

**Comment by parrt** [comment]
> @parrt @ericvergnaud is it possible to install free [Visual Studio Community 2022](https://visualstudio.microsoft.com/vs/community/) or execute abovementioned command on self-hosted Windows machine?

is ok with me if machine has disk space.

**Comment by KvanTTT** [comment]
But I can't do it since I don't have access to the machine and it's self-hosted :)

**Comment by parrt** [comment]
Yep, waiting to hear from @ericvergnaud  :)

**Comment by KvanTTT** [comment]
I temporary disabled C++ tests on Windows. @parrt I suggest merging since the request fixes Windows C++ projects (runtime and demo), the tests can be enabled later.

**Comment by parrt** [comment]
Looks like excellent work, @KvanTTT thanks!

**Comment by parrt** [comment]
It looks like some of the commits did not have DCO but I forced it

**Comment by ericvergnaud** [comment]
Have you tried actions/setup-dotnet@v1 ?
I believe it contains MSBuild

**Comment by KvanTTT** [comment]
Ok, even so, such msbuild doesn't have required c++ libraries.

**Pull request merged**
