### PR TITLE
#3450 create NoViableAltException at the point in time when actually throwing it

### PR DESCRIPTION
**Pull request by aamotharald**
This addresses #3540 - Java: ParserATNSimulator creates Exceptions that get thrown at a later point in time

### CODE REVIEW

**Comment by aamotharald** [comment]
> Hi @marcospassos , I am having failing tests for the PHP part of antlr4 although I changed Java coding. I cannot find the PHP source code. Is that being generated? I am not able to understand the problem there and would need help..

Sorry @marcospassos , the problem was raising the PR against the master branch (better name: trunk..) instead against the dev branch. You can ignore this.

**Comment by aamotharald** [comment]
Hi @parrt ,
who would be a suitable contact to discuss this PR.
This PR does not change functionality/behaviour at all but allows to monitor software projects using antlr dynatrace (https://www.dynatrace.com/) and have NO false-positive errors in dynatrace.

**Comment by parrt** [comment]
hi. That seems reasonable, though I hesitate to remove a method, noViableAlt(), that somebody might have overridden.

**Comment by aamotharald** [comment]
Hi @parrt ,

good point. I will check if I can keep the method signature to not introduce a regression to somebody who might override this method. Thanks for the review!

**Comment by parrt** [comment]
Yeah, that's what I was worried about. I'm going to close this even though there are some useful bits here.

**Comment by parrt** [comment]
(maybe ping me if you wanna reopen and keep same API...)

**Comment by aamotharald** [comment]
@parrt , I'll rework and open a new PR taking the latest [antlr:dev](https://github.com/antlr/antlr4/tree/dev) branch as base towards end of the week. OK? Anything else to consider?

**Comment by aamotharald** [comment]
@whitten : https://en.wikipedia.org/wiki/Developer_Certificate_of_Origin

**Comment by parrt** [comment]
Our new thingie: https://github.com/antlr/antlr4/blob/dev/developer-cert-of-origin.txt

**Pull request closed without merging**
