### PR TITLE
"int" is a reserved keyword.

### PR DESCRIPTION
**Pull request by hce**
closure-compiler complains about this with an error...

### CODE REVIEW

**Comment by ericvergnaud** [comment]
Sorry, but I don't agree that int is a reserved keyword.
See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar

**Comment by sharwell** [comment]
According to ECMA-262 §7.6.1, it seems @ericvergnaud is correct. Nevertheless, if this helps the closure-compiler avoid a warning is there any reason not to include it?

**Comment by ericvergnaud** [comment]
Sounds like a closure-compiler bug, not the first one from what I can guess googling around.
There are hundreds of javascript rewriters out there, so will only accept this as a last resort.

**Comment by ericvergnaud** [comment]
According to some people, the solution is to use --language_in ECMASCRIPT5_STRICT as an option to the closure compiler.

**Comment by sharwell** [comment]
@ericvergnaud I don't see any disadvantages to the new code. The old name `int` wasn't serving any particular purpose that `integer` won't work for as well. My vote is :+1: on this. If you don't see any disadvantage we should go ahead and accept this change.

**Comment by ericvergnaud** [comment]
@hce 
I'd like to get some feedback on the --language_in ECMASCRIPT5_STRICT approach. We you able to try it out?

**Comment by hce** [comment]
When calling closure-compiler with --language_in ECMASCRIPT5_STRICT, the problem does indeed not occur.

Sorry for not responding sooner!

**Comment by ericvergnaud** [comment]
Thanks.
Closing this since it is not required.

**Pull request closed without merging**
