### PR TITLE
Fix #1855, #2211

### LINKED ISSUE #1855: Support passing std::unique_ptr through antlrcpp::Any
The C++ runtime for Antlr4.7 uses a class `Any` as return type of visitor methods. This type has copy constructors that require the contained type to be copyable. `std::unique_ptr` obviously doesn't satisfy this requirement.

The following fragment demonstrates this. It won't compile giving an error about a copy constructor of `std::unique_ptr` being used from the instantiation of the `clone()` function of the `Derived<T>` class in `Any.h`:
```
#include <memory>
#include "antlr4-runtime.h"

int main()
{
  std::unique_ptr<int *> a;
  antlrcpp::Any b(std::move(a));
  return 0;
}
```

As an experiment I explicitly deleted the copy constructors from the `Any` class and removed the `clone()` functions. I then also modified the `AbstractParseTreeVisitor::aggregateResult()` function to be:
```
    virtual antlrcpp::Any aggregateResult(antlrcpp::Any &/*aggregate*/, antlrcpp::Any &nextResult) {
      return std::move(nextResult);
    }
```

This function was the only one requiring copy constructors of `Any`. With these modifications my code is able to store objects containing `std::unique_ptr`s in `Any` instances.

My idea is that the purpose of `Any` in visitors is to pass ownership of an arbitrary object created in one function up to its caller. `std::unique_ptr` was specifically created to support this transfer of ownership. 

I would therefore like to request the possibility to store objects containing `std::unique_ptr`s in the `Any` class (possibly by making the modifications I showed above).

### PR DESCRIPTION
**Pull request by EternalPhane**
Make `clone()` function of `antlrcpp::Any::Derive` return either new `Derive*` or `nullptr` depending on whether template type is copy-constructible.

Related: #1855

### CODE REVIEW

**Comment by daniele-niero** [comment]
Hello,

Is this already merged to the master branch? I have compiled the cpp runtime and I still have the problem.

**Comment by mike-lischke** [comment]
No it's not merged yet.

**Comment by EternalPhane** [comment]
Ping...

**Comment by mike-lischke** [comment]
@parrt This is a pure C++ patch and all checks passed. Can you please merge?

**Pull request merged**
