### PR TITLE
Merge cpp

### PR DESCRIPTION
**Pull request by parrt**
We have C++!!!!

### CODE REVIEW

**Comment by marcospassos** [comment]
@parrt is there any estimate for a release date of 4.6? I can't wait to start using it :)

**Comment by parrt** [comment]
well, you can build yourself from github src if you want ;)  I'm waiting on Swift target. hopefully within a few weeks.

**Comment by marcospassos** [comment]
Yes, I can, but it must be official :)

Besides this, we need the new version of the Maven and IntelliJ plugins to complete the party.

**Comment by parrt** [comment]
True dat.

**Comment by ericvergnaud** [comment]
Wow!!!

**Comment by pureconfig** [comment]
People have been waiting *years and years* for the C++ target. Why not release 4.6 now and 4.6.1 with Swift later on?

**Comment by parrt** [comment]
@pureconfig we're all set to go minus a few build issues for 4.6 *with* swift. :)

**Comment by marcospassos** [comment]
Go! Go! Go!

**Comment by parrt** [comment]
@marcospassos working on build issues cross-platform etc.. ;)

**Pull request merged**
