### PR TITLE
fix minor issues with bild.py

### PR DESCRIPTION
**Pull request by kazzmir**
1. update the location of the bild site, to github
2. use urllib2 to open url's, which automatically uses proxies defined by $http_proxy

### CODE REVIEW

**Comment by kazzmir** [comment]
The reference to bildtool.org can stay. Should I undo that one commit, and leave the other 2?

**Comment by parrt** [comment]
please undo that one, yep.
Ter

**Comment by kazzmir** [comment]
Done

**Comment by parrt** [comment]
Ah. missed it. this pull still shows bildtool.org change though: https://github.com/kazzmir/antlr4/commit/95a9aa8e88886e89c086c9fb3ba34e3b3f4eebb0

**Comment by kazzmir** [comment]
Yea, I did another commit to undo that one, https://github.com/kazzmir/antlr4/commit/95a9aa8e88886e89c086c9fb3ba34e3b3f4eebb0. I wasn't sure how to completely remove https://github.com/kazzmir/antlr4/commit/95a9aa8e88886e89c086c9fb3ba34e3b3f4eebb0 since I already pushed to my repo.

Alternatively I can close this pull request, make a new fork, and redo the two good commits.

**Comment by kazzmir** [comment]
Oops the revert commit is https://github.com/kazzmir/antlr4/commit/b4f7550911b9026ea327464e5285c6bea7ca4166

**Comment by parrt** [comment]
Hi, yeah, I've gotten myself confused. Let's close and do another one with the good commits. thanks!

**Pull request closed without merging**
