### PR TITLE
Fix codegen template for Go parser

### LINKED ISSUE #2826: Error "undefined: GetInvokingContext" for Go target
Test.g4:
```g4
grammar Test;

itemList locals [ []string Items ]
   : '<' item+ '>' EOF { fmt.Printf("Items in list: %v\n", $Items) }
   ;

item
   : tkn='A' { $itemList::Items = append($itemList::Items, $tkn.GetText()) }
   ;

// Ignore whitespace in lexer
WhiteSpace: [ \r\n\t]+ -> skip;
```

Go code for testing:
```go
package main

import (
	"github.com/antlr/antlr4/runtime/Go/antlr"
	"tester/parser"
)

type testListener struct {
	*parser.BaseTestListener
}

func main() {
	is := antlr.NewInputStream("< A A A >")

	lexer := parser.NewTestLexer(is)
	stream := antlr.NewCommonTokenStream(lexer, antlr.TokenDefaultChannel)

	p := parser.NewTestParser(stream)
	antlr.ParseTreeWalkerDefault.Walk(&testListener{}, p.Start())
}
```

Go module descriptor for compiling the code above:
```
module tester

go 1.12

require github.com/antlr/antlr4 v0.0.0-20200503195918-621b933c7a7f
```

Generating the parser:
```bash
java -jar $PWD/antlr-4.8-complete.jar -Dlanguage=Go -o parser Test.g4
```

Running the code tester:
```bash
$ go run tester.go
# tester/parser
parser/test_parser.go:328:2: undefined: GetInvokingContext
```

### PR DESCRIPTION
**Pull request by preethamrn**
This fixes #2826. It adds the required pointer receiver and type assertion to the `GetInvokingContext` call.

No changes to the runtime are necessary.

### CODE REVIEW

**Comment by preethamrn** [comment]
@ericvergnaud I was wondering if you could review this as it fixes a pretty big issue with the current Go template. Currently dynamic scoping causes a compiler error: `undefined: GetInvokingContext`.

**Comment by parrt** [comment]
Another one for @jcking to check out.

**Comment by parrt** [comment]
@jcking  should we leave a bunch of this Go clean up until after 4.10? Maybe others too like https://github.com/antlr/antlr4/pull/3186

**Comment by jimidle** [comment]
This looks good to me, but I will change it a little given that I just fixed the naming in the template and this is one place that is affected. I will send a PR to replace this one.

**Pull request closed without merging**
