### PR TITLE
JavaScript runtime bugfixes

### PR DESCRIPTION
**Pull request by ethall**
While adding TypeScript declaration files to the JavaScript runtime module (#2678), I've found and resolved various issues. More detail on each commit can be found it its description.

### Inconsistencies
- bcfeea6
- 5738df1

### Bugs
- d7a82a2
- 87788e7
- 6712106
- Everything after "Updated contributors.txt"

### Checklist
- [x] Signed contributors.txt.
- [x] Done creating type declaration files. (More bugs may be squashed in the meantime.)
- [x] Updated this description with the PR number. (See above.)
- [ ] Added test coverage for all changes.

### CODE REVIEW

**Comment by ericvergnaud** [comment]
Hi,
Thanks for this.
Re so called 'bugs', I suspect this could simply be dead code (inherited from the Java->JS migration).
The only way to integrate these changes would be if you provide tests that provide evidence of the bug and the fix.

**Comment by ethall** [comment]
Sure, not a problem.

**Comment by ethall** [comment]
@ericvergnaud 
If I've understood the documentation correctly, these tests should live in
`runtime-testsuite/test/org/antlr/v4/test/runtime/javascript/*/api`?

**Comment by ericvergnaud** [comment]
suggest you only provide them for node, in 1 file named for example ApiTests under the node folder

**Comment by ethall** [comment]
I've found an alternative solution ([antlr4ts](https://github.com/tunnelvisionlabs/antlr4ts)) that provides a more fully-featured ANTLR4 runtime than the pure JavaScript runtime maintained by the ANTLR project.  Although `antlr4ts` is in alpha at the time of writing, I have yet to run into any significant problems using it.

I've archived my fork in case anyone from the future wants to pick up where I left off.

**Pull request closed without merging**
