### PR TITLE
C# and Go runtime tests fixes on non-Windows OS 

### PR DESCRIPTION
**Pull request by KvanTTT**
Trying non-draft to check if Circle-CI builds will be started.

### CODE REVIEW

**Comment by KvanTTT** [comment]
@ericvergnaud unfortunately, ordinary PR didn't help. Could you please run the Circle-CI pipeline manually?

**Comment by KvanTTT** [comment]
Is it possible to run pipeline manually?

**Comment by ericvergnaud** [comment]
This PR is draft too by the way

**Comment by KvanTTT** [comment]
Yes, I changed it because it does not affect Circle-CI build.

**Comment by ericvergnaud** [comment]
All other PRs seem to make it to Circle CI, so there must be something weird with this one

**Comment by KvanTTT** [comment]
Not exactly with this one, but with all my pull requests. I registered in CircleCI, maybe it can help in some way.

**Comment by ericvergnaud** [comment]
Suggest you file a ticket with CircleCI, to find out whether your PRs are received, and if so why they are ignored.
From there, if required file a ticket with GitHub ?

**Comment by KvanTTT** [comment]
Done: https://support.circleci.com/hc/en-us/requests/100574#

**Pull request closed without merging**
