### PR TITLE
[Python3] Move the metadata into `PEP 621`-compliant `pyproject.toml`.

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by ericvergnaud** [comment]
Hi,
thanks for this but I suspect it affects the releasee process ?

**Comment by KOLANICH** [comment]
It affects. Instead of `python3 setup.py <needed args>` one should call `python3 -m build <needed args>`

**Comment by ericvergnaud** [comment]
Can you update the release docs accordingly ?

**Comment by KOLANICH** [comment]
In fact it turns out the fix in the docs is not needed, it is already prescribed to use `python3 -m build` there.

**Comment by ericvergnaud** [comment]
@parrt blessed

**Comment by parrt** [comment]
Can you guys update the release doc so i know how to use non-setup.py?

**Comment by ericvergnaud** [comment]
It’s already done - no update neededEnvoyé de mon iPhoneLe 18 mai 2023 à 01:10, Terence Parr ***@***.***> a écrit :﻿
Can you guys update the release doc so i know how to use non-setup.py?

**Pull request merged**
