### PR TITLE
[Swift] Use for in loops

### PR DESCRIPTION
**Pull request by Dante-Broggi**
NFC

### CODE REVIEW

**Comment by parrt** [comment]
Looks good to me with my limited Swift abilities... but we have some failing tests. Let me resolve the conflict if I can and try the continuous integration again

**Comment by parrt** [comment]
Oh Shoot.  we totally changed how the serialization works in Swift.  could you rebase and try again or maybe just revert ATNDeserializer.swift and make the associated `for` changes?

**Comment by Dante-Broggi** [comment]
Rebased to drop the ATNDeserializer.swift changes.

**Comment by parrt** [comment]
thanks!

**Pull request merged**
