### PR TITLE
Issue 1483

### PR DESCRIPTION
**Pull request by mike-lischke**
Mostly that toString() enhancement, but also some other minor changes.

### CODE REVIEW

**Comment by parrt** [comment]
I merged the next one so i'll close this (redundant).

**Comment by mike-lischke** [comment]
Uhm, I'm not sure this is correct. I sent PRs from different repos. If it were redundant all the changes would appear in all the PRs.

**Comment by parrt** [comment]
They had the same commit messages. Should I reopen this?

**Comment by mike-lischke** [comment]
Yes, please reopen + merge. There are unmerged commits in that branch.

**Comment by parrt** [comment]
howdy! Why are commit messages the same? can we separate them out? new PR?

**Comment by mike-lischke** [comment]
Which PRs are you comparing? I only see one PR with that commit message. Where's the duplicate?

**Comment by parrt** [comment]
compare https://github.com/antlr/antlr4/pull/1512 and https://github.com/antlr/antlr4/pull/1511  Ah. only first commit msg was same. ok, i'll reopen and compare.

**Comment by mike-lischke** [comment]
Damn, you are right. That first commit shouldn't have gone into 2 PRs. I have to watch out more carefully. 

> 
> compare #1512 <https://github.com/antlr/antlr4/pull/1512> and #1511 <https://github.com/antlr/antlr4/pull/1511> Ah. only first commit msg was same. ok, i'll reopen and compare.
> 

Mike
-- 
www.soft-gems.net

**Pull request merged**
