### PR TITLE
Improve case insensitive lexing code

### PR DESCRIPTION
**Pull request by kaz**
- Javascript: make it work
  - It did not work at all.
- Golang: now can be imported directly
  - `import "github.com/antlr/antlr4/doc/resources"`
- Python: newly added

### CODE REVIEW

**Comment by kaz** [comment]
@parrt Could you review this?

**Comment by kaz** [comment]
Thanks for your review!
I'm going to work on writing new streams for such targets (C++, Swift, and newly added PHP).
I'll open new PR to do that, but anyway could you merge this PR now?

**Comment by KvanTTT** [comment]
Unfortunately not :( I don't have such permissions.

**Comment by parrt** [comment]
Looks great. thanks!

**Pull request merged**
