### PR TITLE
#999: Using unicode(c) instead of str(c) to avoid exception when unic…

### PR DESCRIPTION
**Pull request by worsht**
…ode string contains high byte chars

### CODE REVIEW

**Comment by ericvergnaud** [comment]
Hi,
thanks for this.
If not already done, you need to sign the contributor agreement (see contributors.txt)
Eric

**Comment by worsht** [comment]
done, thanks!

**Comment by parrt** [comment]
merging manually.

**Comment by worsht** [comment]
Hi @ericvergnaud @parrt ,
Is there any ETA on releasing a new version of antlr4-python2-runtime with this fix?
Thanks
Rajiv

**Comment by parrt** [comment]
I should do one soon as a key speed increase in python is ready as well. I'm just starting to teach 2 classes tho so timing will be delayed.
Ter

**Pull request closed without merging**
