### PR TITLE
ANTLRFileStream,java: field fileName

### PR DESCRIPTION
**Pull request by HSorensen**
Simplify ANTLRFileStream by using the field "name" for super class ANTLRInputStream
* Change field fileName to use the field name from ANTLRInputStream.
* Change load( ) method to private
* Remove getSourceName()

### CODE REVIEW

**Comment by sharwell** [comment]
While this would have almost certainly been an improvement in the early days of ANTLR 4, I'm concerned because this introduces breaking changes in an API that people are likely depending on. At this point I'm not comfortable with the impact of the change on existing users.

**Comment by HSorensen** [comment]
If someone really use the existing interface to first use the interface to
create a ANTLRFileStream with one name and then use load with a different
name I think it is already broken.
The contract for the filename in the interface is the getSourceName().

Would it be better to use @deprecated for the fileName field and the
load(filename,encoding) method?

All the tests passes with the changes.
IMO, if someone is depending on the current interface there should be a
test-case for their needs.

**Comment by sharwell** [comment]
> If someone really use the existing interface to first use the interface to create a ANTLRFileStream with one name and then use load with a different name I think it is already broken.

Yes, you are correct. I think it would make sense to update the `load` method to write to the `fileName` field. The more likely problems which I refer to as breaking changes would be the following:

1. A class can currently extend `ANTLRFileStream` and override the `load` method. All such code will break if this pull request is merged.
2. A class can currently extend `ANTLRFileStream` and access the `fileName` field.

> IMO, if someone is depending on the current interface there should be a test-case for their needs.

I agree completely, but the reality is this project doesn't include tests for all the cases people use. Instead, this project historically tends to rely on the code review process to identify potentially breaking changes before they make it into the code. With tens of millions of users spanning nearly every country on earth, every breaking change is not a matter of *if*, but *how many*.

**Comment by HSorensen** [comment]
You are right. 
If you must preserve existing behavior you are right, but that also means you cannot update fileName from load( ) in-case some is using the existing behaviour:)
. 
I created a second version using @Deprecated.

**Pull request closed without merging**
