### PR TITLE
Testability and build improvements

### PR DESCRIPTION
**Pull request by ewanmellor**
Miscellaneous testability and build improvements.

### CODE REVIEW

**Comment by parrt** [comment]
Does this fix previous build? Looks like that failed:

```
org.antlr.v4.test.runtime.swift.TestPerformance
testOne[Swift:DropLoopEntryBranchInLRRule_4](org.antlr.v4.test.runtime.swift.TestPerformance)  Time elapsed: 64.679 sec  <<< FAILURE!
junit.framework.ComparisonFailure: 
expected:<null> but was:<fatal error: unexpectedly found nil while unwrapping an Optional value
>
testOne[Swift:DropLoopEntryBranchInLRRule_3](org.antlr.v4.test.runtime.swift.TestPerformance)  Time elapsed: 7.804 sec  <<< FAILURE!
junit.framework.ComparisonFailure: 
expected:<null> but was:<fatal error: unexpectedly found nil while unwrapping an Optional value
>
...
```

**Comment by ewanmellor** [comment]
@parrt Those test failures are fixed with my Swift 4.2 fixes, which I just filed as PR #2407.  If you want to merge #2407 then I can rebase this one so that they pass (or just merge them together, they don't conflict).

**Comment by parrt** [comment]
@ewanmellor done! merged #2047

**Comment by ewanmellor** [comment]
I've rebased this on top of PR #2408, which should fix the test failures.

**Pull request merged**
