### PR TITLE
Python local import fixes

### PR DESCRIPTION
**Pull request by SkittlePox**
This should allow the `pygrun` executable to run lexer files with both implicit and explicit relative imports. It is a partial fix to issue #3230. This **does not** fix the `Python3.stg` template which causes the implicit relative import in the generated lexer file.

### CODE REVIEW

**Comment by SkittlePox** [comment]
This indeed does fix #3230 in full. Checks not passed because of `Failed to download action` errors:
```
Download action repository 'actions/checkout@v2'
Download action repository 'actions/setup-java@v1'
Download action repository 'stCarolas/setup-maven@v4'
Warning: Failed to download action 'https://api.github.com/repos/stCarolas/setup-maven/tarball/1d56b37995622db66cce1214d81014b09807fb5a'. Error: A task was canceled.
Warning: Back off 26.298 seconds before retry.
Warning: Failed to download action 'https://api.github.com/repos/stCarolas/setup-maven/tarball/1d56b37995622db66cce1214d81014b09807fb5a'. Error: The operation was canceled.
Warning: Back off 21.457 seconds before retry.
Error: The operation was canceled.
```
Re-run tests and they should pass if the actions download.

**Comment by ericvergnaud** [comment]
Can you also fix Python 2 ?

**Comment by SkittlePox** [comment]
Okay, looks like I fixed a bug which is only an issue for Python3 and not Python2. Implicit relative imports were removed in Python3, but are acceptable in Python2, meaning the `pygrun` in Python2 should work just fine.

**Comment by parrt** [comment]
Is this blessed @ericvergnaud ?

**Comment by ericvergnaud** [comment]
@parrt blessed

**Comment by parrt** [comment]
@SkittlePox  could you resolve the conflict, that just got introduced, and then I can merge? thank you!

**Pull request merged**
