### PR TITLE
Fix compiler warning cpp

### PR DESCRIPTION
**Pull request by jmcken8**
GCC generates a warning when forward-declaring a class if that class has
already declared with `__attributes__`:

    warning: type attributes ignored after type is already defined [-Wattributes]

This is a bug in GCC: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=39159

This works around that bug by only forward-declaring the class if it hasn't
already been declared.

Addresses (parts of): #2450, #2481

### CODE REVIEW

**Review by mike-lischke — COMMENTED** [review]
If this patch is still valid then please fix the contributors.txt file conflict and we can merge it.

**Comment by mike-lischke** [comment]
The original author can just add more patches to his PR to fix the issue. If the OP is not interested in fixing it then we should close it and you may pick it up and post a new PR.

**Comment by jmcken8** [comment]
```
java.io.IOException: Process exited with status 143:
```

It looks like the swift process was killed with SIGTERM. Any idea why that would happen?

**Review by mike-lischke — APPROVED** [review]

**Comment by mike-lischke** [comment]
That's frequently happens and you can ignore that.

@parrt This patch is ready to merge.

**Pull request merged**
