### PR TITLE
Added "default" and "values" to bad words C# set

### PR DESCRIPTION
**Pull request by KvanTTT**

### CODE REVIEW

**Comment by KvanTTT** [comment]
I fixed #1125 bug, but actually "symbol conflicts with generated code in target language or runtime" is not appropriate name of this error. We can move all [keywords](https://github.com/antlr/antlr4/blob/4.6/tool/resources/org/antlr/v4/tool/templates/codegen/CSharp/CSharp.stg#L1061) to badWords but I don't like this idea.

**Comment by parrt** [comment]
Ah.  sorry I didn't see this.  Anyway, it looks like C# target does something different and so I just added the appropriate `values` keyword.

**Comment by KvanTTT** [comment]
Can we add "default" keyword to badWords set? It's not working properly for C# for now...

**Comment by parrt** [comment]
I saw it in the C# stg file. Does it not get converted properly to have `@`?

**Comment by KvanTTT** [comment]
Yes, see this: https://github.com/antlr/stringtemplate4/issues/116

**Comment by parrt** [comment]
So, you mean "no", right? it is *not* properly converted because of the string template issue. Am I understanding it fully now?

**Comment by KvanTTT** [comment]
You are right: not properly converter. Sorry for my language 😕

**Comment by sharwell** [comment]
@parrt That's correct. StringTemplate bug prevents the template from converting the word correctly, instead treating it as a magic StringTemplate value.

**Comment by parrt** [comment]
crap. maybe it's time we push out another ST release?

**Comment by KvanTTT** [comment]
It will be great!

**Comment by ericvergnaud** [comment]
Since this is a ST bug, I would recommend fixing the bug rather than work around it i.e. Don't add to C# badwords

Envoyé de mon iPhone

**Comment by KvanTTT** [comment]
@ericvergnaud, completely agree.

**Pull request closed without merging**
