### PR TITLE
Abhijithneilabrahampatch 1

### PR DESCRIPTION
**Pull request by abhijithneilabraham**
updated readme for resolving some confusion while using the CLI.

### CODE REVIEW

**Comment by ericvergnaud** [comment]
Hi,
thanks for this but not sure anybody will review this PR with 1,874 files changed!!!
please rebase first such that your changes can be reviewed
and provide a bit more context: what exact problem does this PR propose to solve?

**Comment by abhijithneilabraham** [comment]
The PR just included a change in readme because it aroused confusion for me
and my friend and thought it must have done so for other people also.
But can you help me do it the right way? How does that many files get
changed?

**Comment by ericvergnaud** [comment]
> The PR just included a change in readme because it aroused confusion for me and my friend and thought it must have done so for other people also. But can you help me do it the right way? How does that many files get changed?
> […](#)

You could use git rebase, but if not comfortable suggest you reclone master and then replace the existing readme with the proposed one

**Comment by abhijithneilabraham** [comment]
Thanks for your kind reply. I'll sure do that.

**Comment by abhijithneilabraham** [comment]
https://github.com/antlr/antlr4/pull/2593 kindly check this one .This
contain the PR about the changes I would like to make.

**Pull request closed without merging**
