### PR TITLE
Consistent indents (tabs) for all string templates

### PR DESCRIPTION
**Pull request by KvanTTT**
Also it decreases the size of generated code.

### CODE REVIEW

**Comment by bhamiltoncx** [comment]
It'd be amazing if we could introduce automatic code formatters here.

**Comment by ericvergnaud** [comment]
Hi,
Sorry but I'm against this PR. Especially the current Python templates use spaces to comply with pep 8.
There is no such thing as consistency across targets when each language has its own "consistency" rules.

**Comment by mike-lischke** [comment]
The title of this PR is a bit misleading. It's not about formatting all runtime code, but just the string templates. The intention is very good, but the changes have to mimic what is currently used in the handwritten code.

And tabs shouldn't be used at all, as their presentation in various tools vary way too much and more often than not produce terrible output.

**Comment by mike-lischke** [comment]
@bhamiltoncx I could imagine a clang-format file in the repo which contains settings specific for each used language, to which the runtimes must conform. We just have to agree a base formatting style. I'm happy to contribute C++ settings for the Google coding style (the current C++ runtime is already formatted in that style).

**Comment by KvanTTT** [comment]
@bhamiltoncx I'm afraid that's impossible for stg files at present time. This is a specific format.

@ericvergnaud current Python2 template uses mixed indents. See tabs at https://github.com/antlr/antlr4/blob/4.6/tool/resources/org/antlr/v4/tool/templates/codegen/Python2/Python2.stg#L169 for example. Python3 and JavaScript templates have the same problem.

@mike-lischke my issue about customizable indents has been closed: https://github.com/antlr/antlr4/issues/1682. But I like this idea and I also like whitespaces. But I choose tabs because of less generated file size.

**Comment by parrt** [comment]
Yeah, i'm gonna close as I don't want to monkey with the generated code at this point.

**Pull request closed without merging**
