### PR TITLE
[Python2] Remove Python 2 support now that Python 2 is EOL

### PR DESCRIPTION
**Pull request by jcking**
Shall we?

### CODE REVIEW

**Comment by jcking** [comment]
@parrt Not sure how people feel about this, but reduces some maintenance overhead. Python 2 itself is EOL and no longer supported by Python.

**Comment by parrt** [comment]
Well, @ericvergnaud might still want it. I'll wait for his comment. I don't know anyone using python2 but...

**Comment by jcking** [comment]
Friendly poke for @ericvergnaud

**Comment by KvanTTT** [comment]
@jcking you are too fast, I would wait for at least a week before closing.

**Comment by jcking** [comment]
There was an out-of-band discussion to keep it for now.

**Pull request closed without merging**
