### PR TITLE
Improved mypy type-checking for generated Python3 files.

### PR DESCRIPTION
**Pull request by chwmilcon**
Antlr4's generated code for Python3 target had some misuse of __slots__. All the base objects were not using slots so derived objects from them didn't correctly enforce slots. __slots__ were added to base objects. Additionally, a number of forward declarations were made as class_name = None, this causes issues with mypy when checking code. Imports and other forward declarations were added to correct this. Furthermore, return types and argument types were added to functions within runtime to contribute to mypy type checking.  Emitted code was verified by generating a parser for java8 using python 3.11

### CODE REVIEW

**Comment by ericvergnaud** [comment]
Hi. Thanks for this.
I'm seeing a lot of duplicate code in this PR, I guess this was machine generated ? 
It's not currently mergeable, missing DCO, and the python 3 build now fails...

**Comment by chwmilcon** [comment]
Are you referring to the import statements being duplicated? Yes, those
were generated by monkeytype. Are there others? That might be a merge issue
on my side.

What's DCO? And I'm currently fixing the CI/CD failure. It appears that
runtime files need to be able to stand more independently than I tested
them.

**Comment by ericvergnaud** [comment]
Yes I am referring to the duplicate imports
See https://github.com/antlr/antlr4/blob/dev/CONTRIBUTING.md for contributing policy
DCO means you need to sign-off your commits

**Comment by chwmilcon** [comment]
This branch appears incomplete. Separation from private branch not done correctly.

**Pull request closed without merging**
