### PR TITLE
[Go] Improve BitSet implementation

### PR DESCRIPTION
**Pull request by jcking**
The current `BitSet` implementation uses a map. The ideal implementation uses a slice of integers and has significantly less overhead. This pull request switches `BitSet` to be backed by a slice of integers. This is very similar to how things like `std::bitset` in C++ are implemented.

### CODE REVIEW

**Comment by jcking** [comment]
@parrt Not sure who deals with Go.

**Comment by parrt** [comment]
I think @pboyer, original dev, isn't able to help anymore, but @KvanTTT has been working on perf also.

**Comment by parrt** [comment]
Getting a speed check and then will check this one.  Go target is really slow at moment and this is likely culprit.

**Comment by KvanTTT** [comment]
@jcking is it possible to look at a comparison table before/after optimization? Have you checked it?

**Comment by parrt** [comment]
real	4m14.464s on my m1 mac mini and now I'm running with these tests in.

**Comment by KvanTTT** [comment]
Have you tested performance on runtime tests? It is not reliable because of a lot of side effects and IO operation. The result may vary significantly. You can try to do it several times or take a look at two sequential AppVeyour builts: [1](https://ci.appveyor.com/project/parrt/antlr4/builds/41943576/job/lyywjsonc23m8r62), [2](https://ci.appveyor.com/project/parrt/antlr4/builds/41954992/job/s92n7tkjedok4gg9). There is a difference in 95 sec without code change at all.

**Comment by parrt** [comment]
ah. yeah, good point. Not thinking straight today.  Maybe you can test using the rig you used for your patches?

**Comment by KvanTTT** [comment]
I have not used any rig because it was obvious and significant changes (22 -> 6 min for javascript, 20 -> 8 min for Go). I have no objection to merging but ideally, it also should be tested using micro-benchmarks.

**Comment by jcking** [comment]
I can get the Go tests to run in 1 min 50 sec instead of 3 min 44 sec by making them parallel. It looks like the Go tests copy the contents of GOROOT. It might be better to just override GOPATH and avoid the copy.

**Comment by jcking** [comment]
Its also not really a micro-optimization. If you run in a for loop and set bits 0 through 63 on the map impl, its going to consume more memory and be less efficient then the slice implementation. The slice implementation will only allocate once, while the map one will have to resize and rehash at least once. It will also have to perform more allocations, depending on `map` underlying implementation. Using the slice reduces the amount of generate garbage for GC. A micro-optimization would be to take that further and avoid the slice for single element bitsets and use just a bare `uint64`.

**Comment by parrt** [comment]
@jcking maybe a good excuse for me to learn some more Go.  wow. copying entire root? strange. ok, i'll look. maybe it was old-school Go before modules.

@KvanTTT i'll try to run a Go parser...

I'll finish https://github.com/antlr/antlr4/pull/3407 first though.

**Comment by KvanTTT** [comment]
> I can get the Go tests to run in 1 min 50 sec instead of 3 min 44 sec by making them parallel. It looks like the Go tests copy the contents of GOROOT. It might be better to just override GOPATH and avoid the copy.

It's true. But I was not able to override GOPATH because of some problems, tests were not working. Anyway, single copying the content of GOPATH is better than the previous scheme with copying ALL runtime files for EVERY test.

**Comment by KvanTTT** [comment]
I remembered it's not just copying, it's copying together with ANTLR runtime files. Redirection occurs but to the new directory that contains both go system files and go ANTLR runtime files: https://github.com/antlr/antlr4/blob/master/runtime-testsuite/test/org/antlr/v4/test/runtime/go/BaseGoTest.java#L182 I don't know how to implement it in a better way. Maybe copy go system files only one time but go version also can be updated.

**Comment by parrt** [comment]
Yeah, maybe I shouldn't mess with the Go test rig until I know how it deals with modules and installing software better.

**Comment by studentmain** [comment]
This seems caused grammars-v4 vb6 grammar fail. 

https://github.com/antlr/grammars-v4/pull/2429#issuecomment-999392241

https://github.com/antlr/grammars-v4/runs/4596478383?check_suite_focus=true#step:9:5206

**Comment by KvanTTT** [comment]
I don't think so because grammars-v4 uses a stable version from the maven repository, this change is in the development branch.

**Comment by studentmain** [comment]
> I don't think so because grammars-v4 uses a stable version from the maven repository, this change is in the development branch.

Due to how `go get` works, test for golang is using the runtime from the development branch.

https://github.com/antlr/grammars-v4/blob/d48d5e1cf74e5e73d3b1f57ae91509a18ed7d912/_scripts/templates/Go/tester.psm1#L11

**Comment by KvanTTT** [comment]
Maybe I'm wrong. Is it possible to set up downloading from a certain commit?

**Comment by studentmain** [comment]
> Maybe I'm wrong. Is it possible to set up downloading from a certain commit?

Yes, it's possible. I forgot to do that when I wrote the tester.

**Comment by KvanTTT** [comment]
It looks like it's a good idea to run tests on grammar-v4 together with ordinary runtime tests.

**Comment by jcking** [comment]
https://github.com/antlr/antlr4/pull/3427 should resolve the issue. I
missed that specific case.

**Comment by parrt** [comment]
Hi. just did some testing. I built first with

```
a4.9.3 -Dlanguage=Go -o parser *.g4
```

(where a4.9.3 is an alias to run the tool.)

Not sure I'm actually using the `go.mod` file correctly, but here is what I have:

```
module go-parse-performance

go 1.17

require github.com/antlr/antlr4/runtime/Go/antlr v0.0.0-20220102222715-89f7760263f1 // indirect

replace github.com/antlr/antlr4/runtime/Go/antlr => /Users/parrt/tmp/antlr4.9.3/runtime/Go/antlr
```

That yields (subset of files in jdk 1.8) timing:

Parsed 501 files

real	0m13.971s
user	0m24.560s
sys	0m1.007s
```

Then `go.mod`:

```
module go-parse-performance

go 1.17

require github.com/antlr/antlr4/runtime/Go/antlr v0.0.0-20220102222715-89f7760263f1 // indirect

replace github.com/antlr/antlr4/runtime/Go/antlr => /Users/parrt/antlr/code/antlr4/runtime/Go/antlr
```

Gives:

```
Parsed 501 files (4.10 on disk I hope)

real	0m14.186s
user	0m23.983s
sys	0m1.123s
```

So, about the same.  Note it bounces around a bit depending on sys load of course.

```go
package main

import (
	"fmt"
	"github.com/antlr/antlr4/runtime/Go/antlr"
	"go-parse-performance/parser"
	"io/fs"
	"io/ioutil"
	"path/filepath"
	"strings"
)

func main() {
	// /Library/Java/JavaVirtualMachines/jdk-11.0.13.jdk/Contents/Home/lib/src.zip
	// /Library/Java/JavaVirtualMachines/jdk1.8.0_311.jdk/Contents/Home/src.zip
	// I unzip one of those into a local subdirectory
	root := "jdk8-src"
	files := []string{}
	filepath.WalkDir(root,
		func(path string, d fs.DirEntry, err error) error {
			files = append(files, path)
			return nil
		})
	n := 0
	for _, filename := range files {
		if n > 500 {
			break
		}
		if !strings.HasSuffix(filename, ".java") {
			continue
		}
		println(filename)
		content, err := ioutil.ReadFile(filename)
		if err != nil {
			panic("can't find file " + filename)
		}
		is := antlr.NewInputStream(string(content))
		lexer := parser.NewJavaLexer(is)

		stream := antlr.NewCommonTokenStream(lexer, antlr.TokenDefaultChannel)

		// Create the Parser
		p := parser.NewJavaParser(stream)

		p.CompilationUnit()
		n += 1
	}
	fmt.Printf("Parsed %d files\n", n)
}
```

**Pull request merged**
