### PR TITLE
Change utfcpp git url to use https

### PR DESCRIPTION
**Pull request by skef**
I and others (e.g. https://github.com/npm/npm/issues/6285 ) have encountered reliability problems with git: github urls in certain contexts. These problems can be overridden with `git config --global url.https://github.com/.insteadOf git://github.com/` but just starting with the https url would be easier for everyone.

### CODE REVIEW

**Review by mike-lischke — APPROVED** [review]

**Comment by mike-lischke** [comment]
@skef Also here, please solve the conflicts. We can then merge.

**Comment by skef** [comment]
> @skef Also here, please solve the conflicts. We can then merge.

Done

**Review by mike-lischke — APPROVED** [review]

**Comment by mike-lischke** [comment]
@parrt Another C++ only patch to merge.

**Comment by saeed3232** [comment]
Cloning into 'xerosploit'...
fatal: unable to access 'https://github.com/LionSec/xerosploit/': Could not resolve host: github.com
من عنده  حل للمشكله

**Pull request merged**
