### PR TITLE
add VS2017 build projects for the c++ runtime and demo

### PR DESCRIPTION
**Pull request by scanban**

### CODE REVIEW

**Comment by niccroad** [comment]
I have a similar change a couple of pull requests earlier (to add vs2017 projects) but this looks like it integrates the visual studio projects better.

**Comment by chund** [comment]
I also support this PR.
@scanban: please fix conflict in contributors.txt to push this PR forward.
one of us could add the PCH feature to the VS2017 also, see #2200

**Comment by scanban** [comment]
@chund: conflict fixed. I think that we could use ForcedIncludeFiles feature of msvc and additional include and cpp files for the precompiled headers, \#pragma once in antlr4-common.h 'll protect against multi inclusion. This approach 'll protect compilation on other platforms from including unneeded files:
https://github.com/scanban/antlr4/commit/0d148e36c9593d75f9a94245ad02282c9beb89f3

**Comment by scanban** [comment]
ci job stopped with "The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install python3.5" failed and exited with 100 during ." error

**Comment by parrt** [comment]
Should I close this whole thing @mike-lischke or is it fixable by removing the precompiled files?

**Comment by parrt** [comment]
@mike-lischke ok.  @scanban please close this and resubmit per Mike's comments if you like.

**Pull request closed without merging**
