### PR TITLE
Set version to 4.10

### PR DESCRIPTION
**Pull request by parrt**
in prep for 4.10 release

### CODE REVIEW

**Comment by maelmahdy86** [comment]
@parrt When v4.10 will be released as I really need the **caseInsensitive** option ?

**Comment by KvanTTT** [comment]
There are a lot of changes and improvements, some of them are still ongoing.

Also, firstly I suggest publishing a release candidate to test it on our grammars repository.

**Comment by parrt** [comment]
I think we should shoot for a release within a month. What do you guys think? We can always do a quick release after that. Let's do all of the major stuff that is related to code generation now...

**Comment by KvanTTT** [comment]
Not sure, at least I would like to complete bad words escaping (it's still incomplete), issues related to code generation, and to test grammars from grammars-v4 on the new version.

But if you are going to make releases more frequent, maybe it makes sense.

**Comment by ericvergnaud** [comment]
I’m all for frequent small (automated) releases
It reduces risk and encourages potential contributors

**Comment by KvanTTT** [comment]
Ok, I suggest at least completing all issues related to ATN serialization to stabilize the format before the next version releasing.

**Comment by parrt** [comment]
I agree that's a good cut off point. Happy to take a look at your PR for reducing the size of generated ATN strings...

**Comment by xiaozuo7** [comment]
@parrt Hi, is there any progress regarding the release of version 4.10? It has been a long time since the last release.

**Comment by KvanTTT** [comment]
Yes, I'm still waiting for your review of https://github.com/antlr/antlr4/pull/3513

**Comment by parrt** [comment]
ah! I didn't notice it was ready. Sorry!

**Comment by parrt** [comment]
I think you need to compare to dev not master

**Comment by xiaozuo7** [comment]
OK, thank you for your reply. Looking forward to your good news.

**Comment by parrt** [comment]
Oh, @KvanTTT where are we at with regards to the PR to tweak the generated symbols if they are keywords? That would also be something good to get into a major revision such as 4.10.

(working on your atn PR at the moment)

**Comment by parrt** [comment]
looks like we are getting closer folks. I merged @KvanTTT's awesome ATN optimization yesterday.

 I would like to get a bit more testing done inside Google before we declare 4.10 ready, probably with a release candidate. 

Also, @KvanTTT remind me. We merged your groovy PR to avoid generating keywords in the generated code right? https://github.com/antlr/antlr4/pull/3451 

Is there anything else we need to do on?  @kaby76 has also been working hard on keyword lists for a few more languages.

I also have been working on fixing some issues in the intellij plug-in with more recent versions of the IDE; it would be nice to get 4.10 into that upcoming release as well.

**Comment by parrt** [comment]
I also need to work on the release process haha...it's got to be quite a furball and some of that we can automate.  I hope

**Comment by KvanTTT** [comment]
>We merged your groovy PR to avoid generating keywords in the generated code right?

Yes, but the problem still is not completely resolved. But it's not critical and could be resolved in the next version.

> I would like to get a bit more testing done inside Google before we declare 4.10 ready, probably with a release candidate.

I suggest reviewing another PR that breaks ATN serialization a bit but simplifies and expends it (there is no need to use `UnicodeDeserializingMode` if using extended encoding): https://github.com/antlr/antlr4/pull/3546

**Comment by parrt** [comment]
Ok, so let's start moving towards 4.10 rc1.  Can you guys @ericvergnaud @mike-lischke @KvanTTT @jcking check to see if there are any PRs that should sneak in for 4.10?

**Comment by KvanTTT** [comment]
@kaby76 also has some useful PRs. Also take a look at https://github.com/antlr/antlr4/pull/3556

**Comment by kaby76** [comment]
Can someone state what the officially minimum requirements for PHP are? The instructions [here](https://github.com/antlr/antlr4/blob/f5f777d5af3a8e847465787e6112872065440014/doc/php-target.md) and duplicated [here](https://github.com/antlr/antlr-php-runtime/blob/12f51dcb932510481286fd14d59823ed242eda4e/README.md) say nothing. Many ["reserved words" in the PHP list](https://github.com/antlr/antlr4/blob/f5f777d5af3a8e847465787e6112872065440014/tool/src/org/antlr/v4/codegen/target/PHPTarget.java#L18) in the latest "dev" tool which I modified to remove all reserved words checks, do not cause a problem in and the generated parser works fine. For example, "break()" is a perfectly legal method name. Currently I have installed PHP 7.4.3 (cli) (built: Nov 25 2021 23:16:22) ( NTS ). https://github.com/antlr/antlr4/pull/3451

**Comment by mike-lischke** [comment]
Except for that last optimization patch from Justin I don't see anything for C++.

**Comment by parrt** [comment]
@kaby76  does that mean we can reduce the size of the naughty words list for PHP?

**Comment by KvanTTT** [comment]
> @kaby76 does that mean we can reduce the size of the naughty words list for PHP?

Probably yes, but I'm not sure about all words because some words conflict with internal members, not keywords. BTW, currently, there are no usages of `escapedName` in [PHP.stg](https://github.com/antlr/antlr4/blob/dev/tool/resources/org/antlr/v4/tool/templates/codegen/PHP/PHP.stg) and actually reserved words list doesn't affect generation.

**Comment by parrt** [comment]
Oh wow. haha.  we should resolve this by either removing or starting to use it I guess. if it is currently working maybe we just stop using it in the template file.

**Comment by ericvergnaud** [comment]
#3507 is awaiting proper performance testing
#3560 is WIP
#3547 is draft
#3229 is not progressing
#3205 is awaiting proper testing
…

in short, nothing ready to go

**Comment by parrt** [comment]
okay thanks Eric.

**Comment by parrt** [comment]
Ok, I will start the process and work on the release process as well. @jcking  let's get last minute changes in this week if we can.

**Comment by parrt** [comment]
Closing in favor of https://github.com/antlr/antlr4/pull/3599

**Pull request closed without merging**
