### PR TITLE
[C++] Cleanup EMPTY_VOCABULARY uses and remove SingleWriteMultipleRea…

### PR DESCRIPTION
**Pull request by jcking**

### CODE REVIEW

**Comment by jcking** [comment]
@mike-lischke

**Review by mike-lischke — APPROVED** [review]

**Comment by mike-lischke** [comment]
@parrt Another C++ patch ready for merge.

**Comment by parrt** [comment]
@mike-lischke  could you guys resolve the conflict? thanks!

**Comment by jcking** [comment]
Will do on Monday.

**Comment by jcking** [comment]
Fixed conflict.

**Comment by mike-lischke** [comment]
@jcking Thanks!

@parrt The C++ parser tests just take too long and always time out now, it seems :-( At least this is what CircleCI says. Github actions just have a red cross saying the action failed (not exactly helping...).

Otherwise the patch looks fine for merge.

**Comment by KvanTTT** [comment]
Is it possible to improve the performance of C++ compilation? I've noticed it's slow on my local machine as well.

Also, maybe it makes sense to request a more advanced tariff plan for ANTLR project for free because it's valuable and free project.

**Comment by mike-lischke** [comment]
It's slow because it does the worst thing you can do to a C++ project: frequent rebuilds. That's not an issue with script languages or more modern languages...

A better tariff would certainly help.

**Comment by KvanTTT** [comment]
> Improving that would require to restructure the way the tests run

Yes, something like that. I can imagine how it could work for C# (the second slowest language after C++ but even so much faster): use dynamic compilation, but can not for C++.

**Comment by parrt** [comment]
I am thinking about rebuilding the test rig so I will split apart the parsing test so that C++ can pass.

**Pull request merged**
