### PR TITLE
Memoize prediction contexts

### PR DESCRIPTION
**Pull request by JWalker1995**
Memoizes `SingletonPredictionContext.toString` and `ArrayPredictionContext.toString`.

### CODE REVIEW

**Comment by ericvergnaud** [comment]
Hi,
What problem would this solve?
Eric

Envoyé de mon iPhone

**Comment by JWalker1995** [comment]
This is an optimization. For example, using the JavaScript target to parse this java8 snippet:

```java
class HelloWorldApp {
    public static void main(String[] args) {
        System.out.println("Hello World!"); // Display the string.
    }
}
```

Without memoization: 137s
With memoization: 5s

**Comment by ericvergnaud** [comment]
Wow!
Impressive but it would be interesting to understand why toString is called.
Since we introduced MurmurHash, toString should only be called for display.
I suspect something is not working as expected in the hashing mechanism.
Since you've obviously spent some time instrumenting this, would you mind providing a stack trace of a repeated toString call for the above example?
Then we can eventually provide together a more solid optimisation.

**Comment by parrt** [comment]
@JWalker1995 any movement on this PR?

**Comment by sharwell** [comment]
@JWalker1995 The real bug here is that `toString` is called *at all* in that example. The best way to fix this would be altering `toString` to throw an exception and then fixing anything in the core parsing code which called it.

**Comment by parrt** [comment]
Per @sharwell's comment, I'm closing. thanks!

**Pull request closed without merging**
