### PR TITLE
Add browser fs fallback

### PR DESCRIPTION
**Pull request by Ketler13**
This is an attempt to fix runtime browser issue - https://github.com/antlr/antlr4/issues/2852 for environments like create-react-app where there is no possibility to manipulate webpack config without ejecting the application. I did this locally for installed antlr4 package and it helped me. Hope this solution is good enough.

Please also read [webpack 5 migration notes](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#automatic-nodejs-polyfills-removed) :
_Package authors: Use the browser field in package.json to make a package frontend-compatible. Provide alternative implementations/dependencies for the browser._

[Ignore module in package.json](https://github.com/defunctzombie/package-browser-field-spec#ignore-a-module)

Thank you for the great tool!

### CODE REVIEW

**Comment by ericvergnaud** [comment]
@parrt blessed

**Comment by MarkDGithub** [comment]
I am having the same issue, any idea when we might expect an updated npm package with the merged changes?

**Comment by parrt** [comment]
We are actually doing quite a number of important changes so I don't have a date for you but I'm hoping within a month or so we can get 4.10 out the door.

**Comment by MattNot** [comment]
Any news for this to be added in a release?

**Comment by parrt** [comment]
Finally got in major changes that I needed to make so I will start the release process over the next weak or two. sorry for the delay. This has been merged so it will show up in the release 4.10

**Comment by parrt** [comment]
(It's in dev branch now if you'd like to try out)

**Pull request merged**
