### PR TITLE
fix dev branch TypeScript target some typo

### PR DESCRIPTION
**Pull request by windwiny**
fix dev branch TypeScript target some typo

### CODE REVIEW

**Comment by ericvergnaud** [comment]
Thanks but your proposed changes break the build.

**Comment by ericvergnaud** [comment]
Hi, thanks for this.
We will NOT drop the FileStream so rollback the corresponding changes.
Also a PR should fix 1 issue, so please split this PR between docs and templates.

**Comment by windwiny** [comment]
> Hi, thanks for this. We will NOT drop the FileStream so rollback the corresponding changes. Also a PR should fix 1 issue, so please split this PR between docs and templates.

Hi, i see on the master branch ,  `webpack.config.cjs` `target` is `web`, 
on dev branch add TS target commits change it to `node16`, and add module FileStream, it use `fs` , this works on Node environment only, NOT work on web browser script.  

If this package drop fs/FileStream, or restore target to `web`, node environment user itself can import and use `fs`. 
Or we divide this `antlr4` into two packages, corresponding to the Node/Web environment ? 
otherwise every web env user must rebuild dist itself.


Maybe you can use git cherry-pick merge these small changes?  and then i close this PR.

**Comment by ericvergnaud** [comment]
Hi, thanks for your contribution. I have found a better solution, you can close this PR.

**Comment by windwiny** [comment]
In my case `const fs = isNode ? await eval("import('fs')") : null;`  not is better solution,

i use `vite` build html and ts files to js,  `await is only valid in async functions and the top level bodies of modules` ,

`<script>` add `type='module'` attr,  it need new version browser, and NOT work on offline html file `file:///xxx.html`

**Comment by ericvergnaud** [comment]
Thus purpose here is NOT for people being able to call this code in a browser but to have the same package for browser and node.
Node 16 supports top level await.

**Pull request closed without merging**
