### PR TITLE
Fix readme

### PR DESCRIPTION
**Pull request by ericvergnaud**
Proposing to enhance readme to avoid sterile polemics re our versioning

### CODE REVIEW

**Comment by ericvergnaud** [comment]
@parrt no code change, but please review

**Comment by parrt** [comment]
Should this be based on dev or master? I like your notes on versioning and such but it looks like it's pulling in other stuff as well.

**Comment by ericvergnaud** [comment]
I’ll move it to masterEnvoyé de mon iPhoneLe 19 nov. 2022 à 18:10, Terence Parr ***@***.***> a écrit :﻿
Should this be based on dev or master? I like your notes on versioning and such but it looks like it's pulling in other stuff as well.

**Comment by ericvergnaud** [comment]
In favor of #3973

**Pull request closed without merging**
