### PR TITLE
[Swift] optional unwrapping

### PR DESCRIPTION
**Pull request by Dante-Broggi**
This makes the Swift code more idiomatic.

I have additional potential improvements to the Swift runtime, some of which change `public` API, what is ANTLR's policy on (potentially) breaking changes in the runtimes?

### CODE REVIEW

**Comment by martinvw** [comment]
@parrt while this PR was mentioned in https://github.com/antlr/antlr4/issues/2932 it seems to not have been merged, is something blocking merging this or was it just overlooked? Thanks for your great work!

**Comment by parrt** [comment]
Hi!  Unfortunately I'm unable to evaluate Swift code...  I think many of the Swift guys that were helping are no longer active.  Following folks might have an idea as they have contributed in the past: @aciidb0mb3r @vi4m @MaxDesiatov @ddunbar @Bouke @neonichu @abertelrud @0xTim @alephao @buttaface @markbrownsword @sunshinejr @joesus @HaydenMcCabe @hartbit @ElektrojungeAtWork @bjhomer @bjtitus @akoufa

**Review by 0xTim — APPROVED** [review]
LGTM

**Comment by parrt** [comment]
Running testing now...

**Comment by parrt** [comment]
@ericvergnaud  any ideas what's going on with the unit tests?  https://github.com/antlr/antlr4/actions/runs/1279023333  The circleci stuff seems to work but not the github actions.

**Comment by ericvergnaud** [comment]
The CI was down due to a power failure
It’s currently running the queued jobs 

Envoyé de mon iPhone

**Pull request merged**
