### PR TITLE
[C++] Build fix/correction for UTF32 conversion.

### PR DESCRIPTION
**Pull request by mike-lischke**
Adds a few fixes after the recent UTF32 conversion changes. Also fixes some warnings.

### CODE REVIEW

**Comment by ericvergnaud** [comment]
TestCompositeParsers still fails with a compiler error, maybe you need to have a second look?

**Comment by mike-lischke** [comment]
@ericvergnaud Where do you see a compiler error? What fails is what always fails since last fall, job runtime exceeded maximum: https://travis-ci.org/antlr/antlr4/jobs/241708892

**Comment by ericvergnaud** [comment]
@mike-lischke look in https://travis-ci.org/antlr/antlr4/jobs/241757707, which is from the latest master + non cpp changes

**Comment by mike-lischke** [comment]
That's a completely different branch. Why do you post the failure notice in this PR? I have a pull request (#1910)  for that failure, but there's not much moving in antlr4 these days.

**Comment by mike-lischke** [comment]
Now I see what you mean. Still it's the wrong PR. The one where the built broke was #1907 which had been merged short before this one. Maybe @parrt can merge the fix in #1910 quickly, which is just a simple template change.

**Comment by ericvergnaud** [comment]
Agreed

**Comment by parrt** [comment]
Hi guys, i think i've caught up with merges related to bug fixes.

**Pull request merged**
