### PR TITLE
Build development and production ES5 bundles for the JavaScript runtime

### PR DESCRIPTION
**Pull request by octogonz**
Work in progress for issue https://github.com/antlr/antlr4/issues/3032

### CODE REVIEW

**Comment by octogonz** [comment]
This is an initial sketch of a fix for #3032. It builds two ES5 bundles, one for development, and one for production.  By default the `"module"` entry point links to the development bundle.

It seems that the `"main"` entry point must still refer to `src/index.js` for now, because the ANTLR runtime relies on filesystem APIs that are not available in a web browser.  (Your Webpack configuration works around that problem by mapping those modules to `"empty"`, but this is not very clean.  A better solution might be to separate the ANTLR APIs with Node.js dependencies to have their own supplementary entry point.)

I can test this and refine it some more.  But first I'm wondering how you will publish it.  It seems that the version `4.9.1` did not include the `dist` folder, so perhaps some work is also needed for whatever CI job publishes these NPM relases. (?)

**Comment by ericvergnaud** [comment]
Hi,

thanks for this.

Not sure how you relate the main entry point with fs dependency ? 

Re publishing, there is no CI per say, rather a script that Ter runs after versioning and testing everything.
We definitely want the dish folder to be published.

**Comment by octogonz** [comment]
> Not sure how you relate the main entry point with fs dependency ?

The `main` entry point is for CommonJS consumers, which is typically Node.js -- which /would/ want the `fs` APIs.

Whereas the `module` entry point is (generally) for web browsers -- which need a bundle and do NOT have `fs`.

Thus `main` and `module` for now must return two different implementations of ANTLR.  But that is not ideal.

**Comment by ericvergnaud** [comment]
But how does "src/index.js" work when there is no such file?
Also does all this work with npm link?

**Comment by ericvergnaud** [comment]
btw the javascript CI fails, so you might want to rebase to get the latest changes and see how it goes

**Comment by ericvergnaud** [comment]
Hey, we have an upcoming TypeScript target, see https://github.com/antlr/antlr4/pull/4027, so you probably want to close this ?

**Comment by octogonz** [comment]
Closing since https://github.com/antlr/antlr4/issues/3032 was closed.

**Pull request closed without merging**
