### PR TITLE
Tidying up the pom.xml files.

### PR DESCRIPTION
**Pull request by harriman**
Tidying up the pom.xml files.

### CODE REVIEW

**Comment by harriman** [comment]
appveyor tests passed: Go, Java, Javascript, python2, python3.  Failed: C++, C#.  Hoping these failures are not my fault.  C++ running in travis now - looks ok so far.

**Comment by gaulouis** [comment]
Hello,

Maybe you are concerned...


What about :

``mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V``
```
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.antlr:antlr4-runtime-test-annotation-processors:jar:4.6-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ org.antlr:antlr4-runtime-test-annotation-processors:[unknown-version], /home/travis/build/antlr/antlr4/runtime-testsuite/processors/pom.xml, line 42, column 12
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
```

**Comment by harriman** [comment]
Hello gaulouis,  I don't see this warning in my own builds or in the logs from travis-ci or appveyor.  The maven-compiler-plugin version is specified in the master pom.xml and should be inherited by runtime-testsuite\processors\pom.xml.  Are you using a recent version of mvn?

**Comment by gaulouis** [comment]
I'am confused. Your build are clean : https://travis-ci.org/antlr/antlr4/jobs/182472357

Maybe i'am not up to date...
On my local machine : Apache Maven 3.3.9 (what i have posted)
On the travis serveur : Apache Maven 3.2.5 https://travis-ci.org/antlr/antlr4/jobs/182786887#L548

I'm sorry to have disturbed you. I had better go to bed...

**Comment by harriman** [comment]
could it be that some of my changes were not merged into your version?

**Comment by parrt** [comment]
Hmm...given the failures on travis/appveyor, maybe you can "cherry pick" to figure out what breaks it?

**Comment by parrt** [comment]
I'm working on similar one based on yours. thanks! https://github.com/antlr/antlr4/pull/1486

**Comment by harriman** [comment]
Ok, thanks! Hope this helps.

**Pull request closed without merging**
