### PR TITLE
feat: Bump poms to use 4.11 Snapshot

### PR DESCRIPTION
**Pull request by jimidle**
Move to new version numbers as Go target has had significant changes and needs a new minor version

### CODE REVIEW

**Comment by ericvergnaud** [comment]
@parrt as part of releasing 4.11, we also need to cater for the .net code signing issue, see #3653

**Comment by parrt** [comment]
We just have to follow your process in doc right @ericvergnaud? (per https://github.com/antlr/antlr4/issues/3360)

**Comment by ericvergnaud** [comment]
It seems the publishing needs to be done from a winter box otherwise the naming is incomplete

**Comment by parrt** [comment]
Ok, i have two windows boxes (turned off) sitting here :)  Will be painful.

**Pull request merged**
