### PR TITLE
Test cleanup

### PR DESCRIPTION
**Pull request by jasonnn**
short summary of changes:
* consolidated duplicate code in runtime/tool directories
* removed unused code
* regenerate runtime tests
* antlr.testinprocess is true by default
* compilation is always done through the javax.tools api. 
* generated test directories are now in the form baseDir/testClass.simpleName/testName

### CODE REVIEW

**Comment by parrt** [comment]
wow! it'll take me a bit to get to this and then chew through it. I'm kinda dead in water until May 15 but might get to it sooner.

**Comment by parrt** [comment]
I'm back in action. I'll try to look through this. @ericvergnaud can as well.

**Comment by parrt** [comment]
Ok, there's a lot here. Can you explain the issues with previous so I can eval your refactoring? thanks!

**Comment by ericvergnaud** [comment]
Hi jasonn,
some of this looks great.
a breakdown into smaller prs would be helpful though...
I'm not seeing any non java target related changes here. Was this tested (test generation + running the tests) against non java targets?
Eric

**Comment by parrt** [comment]
Hmm...i'm taking a step back and looking at entire test process. I might do my own cleanup.

**Comment by parrt** [comment]
Closing as I did my own thing.

**Comment by sharwell** [comment]
@jasonnn Most of the recent work was a refactoring of the previous behavior so test inputs, grammars, and outputs were all defined in the same location. While your orthogonal improvements were not incorporated, it was not because we didn't like those ideas; we we simply focused on clarity in the test suite code. If you still see places where the test suite could be improved, please feel free to open new issues and/or send pull requests for those items.

If you'd me to provide feedback on a specific feature before you take the time to refactor it into a new pull request, please don't hesitate to ask.

**Pull request closed without merging**
