### PR TITLE
Assign token names to string literals in parse rule contexts

### LINKED ISSUE #2347: Assign token name to generated ParserRuleContext for automatically resolved tokens
Consider the following grammar:

```antlr
grammar test;
root: Token;
Token: 'token';
```

After the parser generation, I have the following `RootContext`:

```java
public static class RootContext extends ParserRuleContext {
	public TerminalNode Token() { return getToken(testParser.Token, 0); }
	public RootContext(ParserRuleContext parent, int invokingState) {
		super(parent, invokingState);
	}
	@Override public int getRuleIndex() { return RULE_root; }
}
```

But for such grammar:

```antlr
grammar test;
root: 'token';
Token: 'token';
```

The terminal node `Token` is missing in `RootContext`:

```java
public static class RootContext extends ParserRuleContext {
	public RootContext(ParserRuleContext parent, int invokingState) {
		super(parent, invokingState);
	}
	@Override public int getRuleIndex() { return RULE_root; }
}
```

It would be convenient to generate the same contexts for the abovementioned grammars.

Full codes and diff are available on https://www.diffchecker.com/eg2AIeJN

### PR DESCRIPTION
**Pull request by KvanTTT**
fixes #2347

### CODE REVIEW

**Comment by parrt** [comment]
Hmm...well, this would have to be implemented in all other targets optimally. I am not sure diverging even more with Java target is worth the increased value.

**Comment by KvanTTT** [comment]
It should work for all targets. But I'll test it on our big grammars set ASAP.

**Comment by parrt** [comment]
Oh, i get it. it doesn't change code gen, it just makes it look like the token ref had a label. ok. please do test on a few big grammars. thanks.

**Comment by KvanTTT** [comment]
Eventually, I've checked the new version on our grammars-v4 repository on Java runtime. Now I can say that everything is fine :)

**Pull request merged**
