### PR TITLE
CPP target runtime: fixed a memleak

### PR DESCRIPTION
**Pull request by FloorGoddijn**

### CODE REVIEW

**Comment by Naios** [comment]
Did you check whether this is a possible fix for the leaks reported in #1592 ?

**Comment by FloorGoddijn** [comment]
Hi Naios,

I have looked at your valgrind output, my fix is not fixing your problem, but is an equivalent situation,  I will closemy current pull request and fix yours as wel in a new one.

Regards,

Floro

**Comment by FloorGoddijn** [comment]
I am closing this one as it turns out there more locations where it leaks in a similar way, and will fix this issue: https://github.com/antlr/antlr4/issues/1592

**Comment by FloorGoddijn** [comment]
Sorry was looking at old code, this fix seems indeed to be the fix for https://github.com/antlr/antlr4/issues/1592 as well

**Comment by Naios** [comment]
@FloorGoddijn Thanks a lot :-)

**Comment by parrt** [comment]
@mike-lischke shall I merge?

**Comment by mike-lischke** [comment]
@parrt Yes, that is a good fix, however I doubt this is completely fixing #1592 (from a quick look at the memcheck log I see that there are other areas affected), but I'm happy to be proved wrong :-)

**Pull request merged**
