### PR TITLE
[C++] Force generated static data type name to titlecase

### PR DESCRIPTION
**Pull request by jcking**

### CODE REVIEW

**Comment by jcking** [comment]
@parrt Assuming tests pass.

**Comment by parrt** [comment]
@mike-lischke seems ok to me; it's an `_` added to prevent collisions on a var name.

**Comment by mike-lischke** [comment]
Hard to say if that is ok. Leading underscore denotes private variables. Are these all private? I doubt it, otherwise they had been prefixed with an underscore already.

Also without explanation I see no reason why these names should be changed at all.

**Comment by jcking** [comment]
Okay, different approach that keeps the style. I forced the type name to be capitlized, which should avoid the conflict.

The issue is that some grammars use lowecase names. This causes the static data type name and variable name to be the same, causing compilation to fail. Forcing the type name to be capitlized should address this edge case.

**Comment by parrt** [comment]
That works for me what I will wait to hear from @mike-lischke

**Review by mike-lischke — APPROVED** [review]
Yes, that's better. Thanks.

@parrt ready for merge

**Pull request merged**
