### PR TITLE
replace gramamr with grammar

### PR DESCRIPTION
**Pull request by StochasticTinkr**

### CODE REVIEW

**Comment by ericvergnaud** [comment]
Thanks for this. Have you signed the contributors agreement? (appreciate it might seem overkilling for fixing typos)

**Comment by StochasticTinkr** [comment]
I have another (more substantial) pull request, where I did. If you insist, I can do it in this one, but it definitely seems like overkill.

**Comment by ericvergnaud** [comment]
I saw the other one, which might take longer to merge, hence why I'd rather you add it to this one to start with.

**Comment by StochasticTinkr** [comment]
Fair enough. I’ll add it when I’m next in front of my computer

**Comment by ericvergnaud** [comment]
@parrt blessed

**Pull request merged**
