### PR TITLE
cache ATNConfig hashCode in Java, C#, Python and JavaScript

### PR DESCRIPTION
**Pull request by ericvergnaud**
This proposal follows findings in https://github.com/mike-lischke/antlr4ng/commit/77d0d4760f40555aae7241564a72b5d6d3f1b53a where caching ATNConfig hashCode seems to improve performance significantly during warmup

### CODE REVIEW

**Comment by ericvergnaud** [comment]
@kaby76 Do you have a benchmark we could use to see if this change genuinely improves performance, and at what cost (memory) ?

**Comment by kaby76** [comment]
> @kaby76 Do you have a benchmark we could use to see if this change genuinely improves performance, and at what cost (memory) ?

I don't have any scripts offhand to compare the performance between before and after versions of the Antlr runtime. It'll have to be done by hand, or a script developed. But, trgen could be used to run the test. Let me write something up.

**Comment by kaby76** [comment]
> > @kaby76 Do you have a benchmark we could use to see if this change genuinely improves performance, and at what cost (memory) ?

For grouped parsing of the 373 files for [sql/plsql](https://github.com/antlr/grammars-v4/tree/master/sql/plsql), 4.13.1 CSharp target vs your PR, there was no improvement. In fact, it was slightly worse on a couple of runs. I double checked everything.

**Comment by ericvergnaud** [comment]
Thanks. Are you able to run this against other targets ?Envoyé de mon iPhoneLe 4 mars 2024 à 21:54, Ken Domino ***@***.***> a écrit :﻿


@kaby76 Do you have a benchmark we could use to see if this change genuinely improves performance, and at what cost (memory) ?


For grouped parsing of the 373 files for sql/plsql, 4.13.1 CSharp target vs your PR, there was no improvement. In fact, it was slightly worse on a couple of runs. I double checked everything.

**Comment by kaby76** [comment]
I don't see any improvements with the TypeScript target either for the [cpp grammar](https://github.com/antlr/grammars-v4/tree/master/cpp).

Have you seen a perf increase with these changes?

**Comment by ericvergnaud** [comment]
No, I haven’t checked.Looks like the perf improvement achieved by antlr4ng is caused by something else…It’s significantly faster during warmup but slightly slower later so not amazing but still worth understanding…Thanksn.b. I think it’d be great to put together some benchmark so we can compare successive versions of antlr5 (and also vs antlr4)Envoyé de mon iPhoneLe 5 mars 2024 à 03:18, Ken Domino ***@***.***> a écrit :﻿
I don't see any improvements with the TypeScript target either for the cpp grammar.
Have you seen a perf increase with these changes?

**Comment by kaby76** [comment]
**Supposedly faster.** But, I cannot reproduce Mike's result. Here's my code in a zip file. 
[java.zip](https://github.com/antlr/antlr4/files/14492831/java.zip)

It doesn't run any faster at least how I'm building and running the code. But, nobody ever seems to want to write the .json files for a driver so we're left to our own device. Who knows whether I guessed right. There may be special settings and versions that are presumed to perform extra special optimizations.

In any case, Antlr4 parses the 14 files in *grouped parse mode aka "warm up"* faster than Antlr4ng.
```
03/05-03:57:23 ~/test/grammars-v4/java/java/Generated-TypeScript
$ bash run.sh ../examples/*.java
TypeScript 0 ../examples/AllInOne11.java success 0.663
TypeScript 1 ../examples/AllInOne17.java success 0.904
TypeScript 2 ../examples/AllInOne7.java success 0.334
TypeScript 3 ../examples/AllInOne8.java success 0.534
TypeScript 4 ../examples/ConsecutiveSemicolons.java success 0.001
TypeScript 5 ../examples/Escapes.java success 0.005
TypeScript 6 ../examples/ExpressionOrder.java success 0.03
TypeScript 7 ../examples/GenericConstructor.java success 0.004
TypeScript 8 ../examples/LocalVariableDeclaration.java success 0.009
TypeScript 9 ../examples/ManyStringsConcat.java success 0.537
TypeScript 10 ../examples/module-info.java success 0.002
TypeScript 11 ../examples/RecordsTesting.java success 0.011
TypeScript 12 ../examples/SwitchExpression.java success 0.008
TypeScript 13 ../examples/TryStatements.java success 0
Total Time: 3.069
```
```
03/05-03:57:55 ~/test/grammars-v4/java/java/Generated-Antlr4ng
$ bash run.sh ../examples/*.java
TypeScript 0 ../examples/AllInOne11.java success 0.686
TypeScript 1 ../examples/AllInOne17.java success 0.925
TypeScript 2 ../examples/AllInOne7.java success 0.34
TypeScript 3 ../examples/AllInOne8.java success 0.559
TypeScript 4 ../examples/ConsecutiveSemicolons.java success 0
TypeScript 5 ../examples/Escapes.java success 0.003
TypeScript 6 ../examples/ExpressionOrder.java success 0.037
TypeScript 7 ../examples/GenericConstructor.java success 0.006
TypeScript 8 ../examples/LocalVariableDeclaration.java success 0.008
TypeScript 9 ../examples/ManyStringsConcat.java success 0.764
TypeScript 10 ../examples/module-info.java success 0.002
TypeScript 11 ../examples/RecordsTesting.java success 0.012
TypeScript 12 ../examples/SwitchExpression.java success 0.008
TypeScript 13 ../examples/TryStatements.java success 0.003
Total Time: 3.374
```

**Comment by ericvergnaud** [comment]
Maybe it's only faster for the MySQL grammar...
Not sure what you mean by .json driver ? Should we create an issue in antlr5 in order to address this topic ?

**Comment by kaby76** [comment]
I will check it for the mysql grammar.

**Comment by kaby76** [comment]
Here's a run of the mysql parser grammar on bitrix_queries_cut.sql. The parse is performed twice on same input. The first time is the "before warm up", the second time is the "after warm up"):
```
03/05-04:50:21 ~/test/grammars-v4/sql/mysql/Positive-Technologies/Generated-Antlr4ng
$ bash run.sh ../examples/b*.sql ../examples/b*.sql
TypeScript 0 ../examples/bitrix_queries_cut.sql success 186.266
TypeScript 1 ../examples/bitrix_queries_cut.sql success 168.398
Total Time: 354.68
03/05-04:56:19 ~/test/grammars-v4/sql/mysql/Positive-Technologies/Generated-Antlr4ng
$ pushd
~/test/grammars-v4/sql/mysql/Positive-Technologies/Generated-TypeScript ~/test/grammars-v4/sql/mysql/Positive-Technologies/Generated-Antlr4ng
03/05-04:56:29 ~/test/grammars-v4/sql/mysql/Positive-Technologies/Generated-TypeScript
$ bash run.sh ../examples/b*.sql ../examples/b*.sql
TypeScript 0 ../examples/bitrix_queries_cut.sql success 160.187
TypeScript 1 ../examples/bitrix_queries_cut.sql success 145.515
Total Time: 305.716
03/05-05:01:41 ~/test/grammars-v4/sql/mysql/Positive-Technologies/Generated-TypeScript
$
```
Antlr4ng is slower than the original 4.13.1 TypeScript runtime.

[Positive-Technologies.zip](https://github.com/antlr/antlr4/files/14493675/Positive-Technologies.zip)

**Comment by kaby76** [comment]
I'm now able to reproduce the claimed speed-up for Antlr4ng. ***Apparently, one should not use version 16.x of NodeJS. You must use at least version 20.x in order to get the speed up.***
```
$ bash run.sh ../examples/bitrix_queries_cut.sql ../examples/bitrix_queries_cut.sql
TypeScript 0 ../examples/bitrix_queries_cut.sql success 155.915
TypeScript 1 ../examples/bitrix_queries_cut.sql success 146.365
Total Time: 302.294
03/05-05:51:49 ~/test/grammars-v4/sql/mysql/Positive-Technologies/Generated-TypeScript
$ pushd
~/test/grammars-v4/sql/mysql/Positive-Technologies/Generated-Antlr4ng ~/test/grammars-v4/sql/mysql/Positive-Technologies/Generated-TypeScript
03/05-06:01:09 ~/test/grammars-v4/sql/mysql/Positive-Technologies/Generated-Antlr4ng
$ bash run.sh ../examples/bitrix_queries_cut.sql ../examples/bitrix_queries_cut.sql
TypeScript 0 ../examples/bitrix_queries_cut.sql success 74.543
TypeScript 1 ../examples/bitrix_queries_cut.sql success 49.375
Total Time: 123.935
03/05-06:03:28 ~/test/grammars-v4/sql/mysql/Positive-Technologies/Generated-Antlr4ng
$ node --version
v20.11.1
03/05-06:03:36 ~/test/grammars-v4/sql/mysql/Positive-Technologies/Generated-Antlr4ng
$
```

**Comment by ericvergnaud** [comment]
Here’s how to do it from the console:cd to the antlr folder containing package.jsonnpm linkcd to the program folder that uses antlrnpm link antlr4Envoyé de mon iPhoneLe 5 mars 2024 à 12:34, Ken Domino ***@***.***> a écrit :﻿
I don't know how to test this PR because antlr4 is in an npm package which the package.json references. I don't know how to replace the package reference with a copy of the JavaScript/TypeScript source tree. I get Cannot find module 'antlr4' or its corresponding type declarations..

**Comment by kaby76** [comment]
I tried out the current 4.13.1 CSharp and TypeScript targets along with the Antlr4ng TypeScript target on the java/java grammar, which is one of our better grammars. I ran the parser on grouped parse mode with the 14 input files. The Antlr4ng is on par with the CSharp target. Yes, Antlr4ng is pretty good.

I haven't yet tested this PR, and I haven't figured out why Antlr4ng is so much better, and why with Node 20.

java

(Ran 10 times, bar graph computed using Octave, errors are 1 SD; [test.sh.txt](https://github.com/antlr/antlr4/files/14510311/test.sh.txt))

**Comment by kaby76** [comment]
The test.sh is what I wrote to collect and print the results. But there are dependencies. Trash, dotnet, octave, etc.

**Comment by kaby76** [comment]
The Antlr4ng code actually contains a number of optimizations which look significant. 

* BitMap is implemented as [an array of bits](https://github.com/mike-lischke/antlr4ng/blob/3afee898cdb33ddac439a8d1ae78443c11eed62e/src/misc/BitSet.ts#L18) rather than [a map to bools](https://github.com/antlr/antlr4/blob/1b3150b5de7400757fd418de4362bd28e44af106/runtime/JavaScript/src/antlr4/misc/BitSet.js#L15).
* HashSet is [bucket-list hash table](https://github.com/mike-lischke/antlr4ng/blob/3afee898cdb33ddac439a8d1ae78443c11eed62e/src/misc/HashSet.ts#L57) rather than [the native map](https://github.com/antlr/antlr4/blob/1b3150b5de7400757fd418de4362bd28e44af106/runtime/JavaScript/src/antlr4/misc/HashSet.js#L31).
* HashMap [uses HashSet](https://github.com/mike-lischke/antlr4ng/blob/3afee898cdb33ddac439a8d1ae78443c11eed62e/src/misc/HashMap.ts#L12) rather than [the native map](https://github.com/antlr/antlr4/blob/1b3150b5de7400757fd418de4362bd28e44af106/runtime/JavaScript/src/antlr4/misc/HashMap.js#L13).

Since Antlr4ng and Antlr 4.13.1 TypeScript are so different in implementation, I wanted to check parser tracing and parser atn tracing. Unfortunately, The TypeScript 4.13.1 API does not define setTrace(), and the Antlr4ng does not define the parser atn tracing flag. So, I cannot compare ATN config sets across targets. Parr worked so hard to get to be consistent across targets, but it's unavailable, which was the whole point of why Parr changed the trace code. Although Antlr 4.13.1 TypeScript does ot have a setTrace() method, I was able to set parser atn tracing between TypeScript and CSharp, and they do appear virtually identical for parsing all 14 java/java/examples/*.java files. So, I do trust the TypeScript target, but I cannot say for Antlr4ng. Just because something is fast, it doesn't mean that it works.

**Comment by kaby76** [comment]
I have a drop-in replacement of [BitSet.js](https://github.com/antlr/antlr4/files/14526319/BitSet.js.txt) adapted from Antlr4ng. It does improve on performance, but it is only ~5%.

**Comment by ericvergnaud** [comment]
> I finally figured out how to test this PR. It does not result in any improvement for TypeScript runtime.
> 
> I have a drop-in replacement of [BitSet.js](https://github.com/antlr/antlr4/files/14526319/BitSet.js.txt) adapted from Antlr4ng. It does improve on performance, but it is only ~5%.

5% is enormous! I'm closing this PR. Do you want to submit a PR with BitSet.js ?

**Comment by kaby76** [comment]
If 5% is good, then you'll like the 20% increase with this drop-in replacement for [HashSet.js](https://github.com/antlr/antlr4/files/14540823/HashSet.js.txt) (with MurmurHash.js as a required dependency). I'm thinking HashMap will see an additional performance increase.

**Comment by ericvergnaud** [comment]
> If 5% is good, then you'll like the 20% increase with this drop-in replacement for [HashSet.js](https://github.com/antlr/antlr4/files/14540823/HashSet.js.txt) (with MurmurHash.js as a required dependency). I'm thinking HashMap will see an additional performance increase.
> 
> I'm thinking why Antlr4? Why not put these changes in Antlr5 alone?

Because antlr5 uses Kotlin to generate wasm. These optimisations don't make sense there.

**Comment by ericvergnaud** [comment]
Btw I'm using your BitSet.js code but sticking to the old api for now. I'd rather refactor than add an indirection.

**Comment by ericvergnaud** [comment]
> If 5% is good, then you'll like the 20% increase with this drop-in replacement for [HashSet.js](https://github.com/antlr/antlr4/files/14540823/HashSet.js.txt) (with MurmurHash.js as a required dependency). I'm thinking HashMap will see an additional performance increase.
> 
Yes HashSet is using an object for key/value mappings, not great!
HashMap has the same issue.
(this code was written before Set and Map were introduced in JS, but they wouldn't be usable here anyway)
FYI HashCode.js IS MurmurHash

**Comment by kaby76** [comment]
> Because antlr5 uses Kotlin to generate wasm. These optimisations don't make sense there.

Shouldn't the [JavaScript](https://github.com/antlr/antlr5/tree/0dab63cd5ec8b5259498146e6d27727cc76303e3/tool/resources/org/antlr/v5/tool/templates/codegen/JavaScript)/[TypeScript](https://github.com/antlr/antlr5/tree/0dab63cd5ec8b5259498146e6d27727cc76303e3/tool/resources/org/antlr/v5/tool/templates/codegen/TypeScript) templates and [runtime](https://github.com/antlr/antlr5/tree/0dab63cd5ec8b5259498146e6d27727cc76303e3/runtime/JavaScript/src/antlr4) be removed in Antlr5? And, does it make sense to modify the Antlr4 code any further, vis-a-vis limited resources to develop both Antlr4 and Antlr5, and Mike's work on Antlr4ng?

**Comment by ericvergnaud** [comment]
We're keeping the TS template as a reference until we have something kinda working in wasm. Then it will be removed.
A perf improvement is always welcome, especially when it's localized like it is here. We don't want users to switch to antlrng for wrong reasons...

**Comment by ericvergnaud** [comment]
@kaby76 closing this in favor of #4549 , #4550 and #4551 
I've put you as reviewer

**Pull request closed without merging**
