### PR TITLE
javascript: typo in Hash

### PR DESCRIPTION
**Pull request by akaJes**
performance decrease after fix

### CODE REVIEW

**Comment by ericvergnaud** [comment]
I agree the current code seems incorrect, but the proposed change breaks many tests!

**Comment by ericvergnaud** [comment]
@akaJes Thanks for detecting this!
Your fix was incomplete, so I submitted PR #2633 (which includes your contribution)
With complete fix I find performance to be similar

**Comment by ericvergnaud** [comment]
@parrt not sure what the status is

**Comment by ericvergnaud** [comment]
@parrt can you check the status? it's marked as merged, but not closed?

**Comment by parrt** [comment]
It looks "open" in my browser but with conflict.

**Comment by ericvergnaud** [comment]
@parrt I think we can close, it was merged by me in #2633

**Pull request closed without merging**
