### PR TITLE
Update maven plugin versions

### PR DESCRIPTION
**Pull request by parrt**
trying to do some updates to the version numbers to get cleaner maven compiles / installs.

### CODE REVIEW

**Comment by parrt** [comment]
Ok, I have updated all of the versions that I could easily find and updated the documentation with a reliable build sequence from an empty maven repository.  we have some nasty cyclic dependency. Try wiping out `.m2` and then trying to build... the runtime tests rely on the software already being built with a jar in the repository cache. doh!!!

**Comment by parrt** [comment]
@KvanTTT and @ericvergnaud  please take a look...  Note that I'm using jdk8 and will turn my attention back to the java 8 PR now.

**Comment by parrt** [comment]
I had to update the scripts that run the tests also use `java.**` not `java.*`.  that was why everything was failing but it looks better now!

**Comment by KvanTTT** [comment]
Unfortunately, now all our tests are red on master. I don't recommend merging without passing all pipelines.

**Comment by parrt** [comment]
They passed all of the circlei

**Pull request merged**
