### PR TITLE
tweak wildcard

### PR DESCRIPTION
**Pull request by parrt**

### CODE REVIEW

**Comment by parrt** [comment]
@ericvergnaud did I do this right?

**Comment by ericvergnaud** [comment]
seems ok to me, but would be great to have a test that triggers this template and prove correctness.

**Comment by parrt** [comment]
Indeed. weird that we don't test wildcard...oh must be in lexer.

**Comment by parrt** [comment]
well crap. worked locally but fails at travis. must be whitespace thing. pushing expanded tabs.

**Pull request merged**
