### PR TITLE
Adding getTokenSource in BufferedTokenStream

### PR DESCRIPTION
**Pull request by hkff**
detected after calling parser.compileParseTreePattern ()

### CODE REVIEW

**Comment by ericvergnaud** [comment]
Hi,
thanks for this, but to be honest I am not supportive of this PR.
The preferred patterns for accessing members vary across languages.
In Java, it is getters, in C# it is properties.
In Python and JavaScript, the preferred pattern is direct access, since the behavior can be controlled through the __getattr__ method in Python and the Object.createProperty feature in JavaScript.
I appreciate that the current Python and JavaScript code bases still largely mimic the Java implementation, due to their origin, but the long term plan is to gradually adopt natural language patterns.
Eric

**Comment by hkff** [comment]
Hi,

I totally agree with that. So the other option is to change all the calls to getTokenSource by a direct access.

Walid

**Comment by ericvergnaud** [comment]
Cool!
Please proceed :-)
Eric

**Comment by hkff** [comment]
Done :)

**Comment by parrt** [comment]
Hi. I will also need you to sign the contributors.txt file at the root of the repository. thanks!

**Comment by hkff** [comment]
Done.

**Pull request merged**
