### PR TITLE
Initialize decisionToDFA in init in Go.stg

### PR DESCRIPTION
**Pull request by pboyer**
Fixes: https://github.com/antlr/antlr4/issues/1743

### CODE REVIEW

**Comment by pboyer** [comment]
@millergarym I've extended this to both the parser template as well.

**Comment by millergarym** [comment]
@pboyer looks good to me.
Are there any places in the runtime that might have similar issues?
When I have some time I'll benchmark this and let you know the result.

**Comment by pboyer** [comment]
@millergarym It's not obvious to me, at first glance, what parts of the system need more optimization right now. I covered some obvious issues in #1755 found in profiling.

I'm not entirely caught up with your benchmarking work, but it seems to me that we'd greatly benefit from profiling the parser against more realistic, large grammars.

**Comment by millergarym** [comment]
@pboyer @parrt 

Woo-hoo. Between 6 and 12 times speed up. 

There is test user if you would like to look around and play
http://jenkins.wx.io:8080/
antlr4-trial
qIkE@3Urc@$W

I haven't tested it against the dgraph hand written lexer, as it requires a different tool chan. But since it was 40x faster, I would guess this would still be ~10x slower. The standard idiom of hand written lexers in Go is basically a combinator, my guess it that there is no heap allocation. From previous profiling a lot of the time is taken up with memory alloc and you can't beat zero.

I will leave the Jenkins instance up for another week, after which the below images will break.

Re: microbenching for Java, I came across http://microbenchmarks.appspot.com/ looks cool, but haven't tried it.

Cheers
Gary

Benchmarking
Benchmarking
Benchmarking
Benchmarking
Benchmarking
Benchmarking

**Comment by pboyer** [comment]
Awesome! Thanks so much for doing this and getting the ball rolling on the
perf improvements @millergarym!

**Pull request merged**
