### PR TITLE
This is one implementation addressing issue 160.

### PR DESCRIPTION
**Pull request by niccroad**
Change to support import of lexer grammars containing modes into other
lexer grammars. The semantics for this are,
   * sets of channels from all grammars are merged
   * rules of modes found in an imported grammar which are in the root
     grammar are merged into the root grammar mode.
   * modes which are not in the root grammar are added to the root
     grammar, excluding modes which become empty due to a re-definition of
     rules in the root grammar.

### CODE REVIEW

**Comment by niccroad** [comment]
Hi Terrence Parr/Sam Harwell,
I have been using antlr4 for some grammars I am working on and found a need for importing multi-mode lexer grammars into other lexer grammars. This didn't seem too difficult so I implemented this and some test cases. Would be happy to discuss other behaviour for the import but the implementation here suited my requirements and seemed broadly to implement Terrence Parr's description of import as compositing two grammar files and replacing slave rules with parent rules.

**Comment by parrt** [comment]
@sharwell What do you think of importing lexers with modes? Semantics described seem ok but I'm wondering about edge cases that could screw us. Maybe rule/tokentype ordering?

**Comment by KvanTTT** [comment]
I like this improvement, seems like in-demand: #256, #160.

Also, another issue should be considered: https://github.com/antlr/antlr4/issues/970

@niccroad did you test grammars import with combined grammars?

**Comment by parrt** [comment]
@KvanTTT Could you do me a favor and look at the code to see if it seems right to you? thanks!

**Comment by KvanTTT** [comment]
For sure, but later, until the end of week.

**Comment by niccroad** [comment]
I didn't look at importing modal lexers into combined grammars. Will add a test case for that I think.

**Comment by parrt** [comment]
thanks

**Comment by niccroad** [comment]
The latest change demonstrates importing a modal lexer grammar into a composite grammar. Of course this just generates an error to state that composite grammars should not contain modes. As you can't create a composite grammar containing modes I think this error should be the correct behavior of an import creating such a composite grammar. The test simply checks for the error when the composite grammar is parsed.

**Comment by niccroad** [comment]
"Maybe rule/tokentype ordering?"
Using the nomenclature of master for the importing and slave for imported grammars.

I didn't think that importing the rules and modes creates any additional issues that importing the lexer rules does not already introduce here. Hopefully using the same strategy for ordering the modal rules as for importing other lexer rules accounts for this anyway. I did think that intuitively importing the slave rules before the master rules (not the existing strategy of after) was the better strategy, but presently the import puts the slave rules after the master ones. This means that lexer disambiguation between rules which are a prefix for other lexer rules must happen inside one lexer grammar at present and the slave grammar should not declare tokens which are a suffix of master rules.

Probably once you start breaking up the lexer rules you will want to declare and use a common set of lexer tokens between the master and slave grammars (as I do). The solution for this is to declare your tokens in the slave lexer grammar which results in them having the same token id numbers when they are generated in the master grammar. This means a parser grammar which builds against the slave lexer grammar can also use the master lexer at run-time. Note to this the token ordering is slave before master tokens which is why this works. But if you do want a fixed set of token ids for two related lexer grammars then declaring tokens seems reasonable so I didn't see a need to worry about this if you import without declaring tokens.

Reordering the lexer rules of import seems likely to break a wide variety of existing grammars. 

Additional consideration, my understanding of the potential ordering issues here is also likely to be quite superficial. I managed to start my latest grammars off by declaring my IDENTIFIER rule before all my KEYWORD rules. Then it took me a while to work out why it failed to parse in simple test cases, with the error to the effect of expecting 'class' at 'class'.

**Comment by KvanTTT** [comment]
Overall LGTM. But ideally it would be great to resolve these issues:

* Write at least one test with conflicted channel names.
* Add info about modes and channels merging to [doc](https://github.com/antlr/antlr4/blob/master/doc/grammars.md#grammar-imports).

**Comment by parrt** [comment]
@niccroad That ID before keyword thing is what concerns me but it's already a problem as you say. If you define ID in imported slave, is it perforce "before" any keywords in grammar?

**Comment by niccroad** [comment]
@parrt, No any rules imported into a existing mode are suffixed onto the modes rules list, and the rule import loop didn't change and does this already. Actually this explains why its slave after master at import time.

I think you can run afoul of this strategy if you define, or redefine ID in master which may cause all the slave keywords to match ID however.

**Comment by parrt** [comment]
ok, so any more objections?

**Comment by niccroad** [comment]
Latest change updates the documentation and adds a test case for a channel rule which conflicts. I would be more than happy if my documentation changes get rephrased as necessary (my writing style tends to be more verbose than necessary).

**Comment by parrt** [comment]
ok, guys. thanks! looks good.

**Comment by niccroad** [comment]
@parrt @sharwell 

Have been thinking about the keyword / ID lexer issue a bit further. It might be possible to add a warning when the lexer will completely consume one rule inside another.

The process would happen during the algorithm which converts a lexer NFA into a DFA (I am assuming this happens somewhere in the tool, but it may not be, it may be using Thompson's algorithm on the NFA for several reasons or even the exponential version NFA version).

Anyway where this happens when you identify all the terminal states out of the constructed DFA, you check if another rule is always in the same state set as the terminal rules DFA state set, and has a lower rule number, e.g if ID matches every terminal state of 'keyword' and has a lower rule number. If that is so then the lower rule number state will always match the input of the higher rule number and the higher rule is redundant. My thought is that this should produce a warning.

If you think there is already a NFA to DFA process in the lexer tool to build this into I might give it a go. If not its probably beyond my scope to introduce such a process primarily to produce a warning (unfortunately).

**Comment by parrt** [comment]
I just pulled in a warning for ID vs keyword from @KvanTTT :)

**Comment by niccroad** [comment]
Might have a look at that change and give it a try. A cursory look indicates it doesn't find keywords shadowed by ID's however. I think that needs to be done by finding the unreachable tokens in the DFA created after NFA to DFA conversion (and in Antlr4 per mode obviously). I think Kvan's change will pick up the direct keyword clashes however, which is a start.

Also note, my last parser theory course was more than 10 years ago, and its not something I do day to day. I am probably over simplifying what problems can be solved by that conversion algorithm.

**Comment by KvanTTT** [comment]
>A cursory look indicates it doesn't find keywords shadowed by ID's however.

Yes, my solution from #2066 finds warnings for only simple cases with duplicated tokens. Deeper analysis requires at least DFA's difference algorithm implementation.

The general satisfactory solution will check a difference between token's DFA and throw a warning if it's not an empty, i.e. `A \ B != Ø` where `A` is a token declaration written before the `B` token declaration.

Let check this term in practice.

This sample will throw a warning because of difference between `ID` rule and `A` rule is `[B-Z][A-Z]*`, i.e. not an empty.

```antlr
ID : [A-Z]+;
A : 'A';
```

This sample won't throw a warning because of difference is an empty language.

```antlr
A : 'A';
ID : [A-Z]+;
```

The following sample also will throw a warning:

```antlr
A : 'A';
B : 'A';
```

Despite the fact that ANTLR lexer covers not only regular languages but [context-free](https://github.com/antlr/antlr4/blob/master/doc/lexer-rules.md#recursive-lexer-rules) too I suggest checking only not recursive tokens. Those exclude tokens like this:

```
ACTION : '{' ( ACTION | ~[{}] )* '}' ;
```

Such tokens are rare and do not significantly affect warnings checking.

**Pull request merged**
