### PR TITLE
Fix Dart linter errors under strict mode

### PR DESCRIPTION
**Pull request by jcking**

### CODE REVIEW

**Comment by jcking** [comment]
@parrt Not sure who maintains the Dart runtime. But this change addresses some Dart linter errors that surface when running in strict mode with null safety turned on.

**Comment by KvanTTT** [comment]
@lingyv-li maintains Dart runtime, at least it was before.

**Comment by KvanTTT** [comment]
Unfortunately, Dart tests are failing.

**Comment by jcking** [comment]
Whoops, I did not realize the underlying variable was plural but the setter/getter was singular. Fixed the variable to be singular as well.

**Pull request merged**
