### PR TITLE
C# and Go runtime tests fixes on non-Windows OS

### PR DESCRIPTION
**Pull request by KvanTTT**

### CODE REVIEW

**Comment by KvanTTT** [comment]
I don't understand why circle-ci status is not displayed for me?

**Comment by ericvergnaud** [comment]
Because it's a draft PR maybe ?
Are you able to see builds here: https://app.circleci.com/pipelines/github/antlr/antlr4 ?

**Comment by KvanTTT** [comment]
> Because it's a draft PR maybe?

Maybe. If so, it's quite strange behavior, because builds from AppVeyor and Github are available.

> Are you able to see builds here: https://app.circleci.com/pipelines/github/antlr/antlr4 ?

I only see builds for master and other pull requests. Could you please start the pipeline on CircleCI manually?

**Comment by KvanTTT** [comment]
I'm going to create a new non-draft PR.

**Pull request closed without merging**
