### PR TITLE
[Go] Add Iterative tree walker in go

### PR DESCRIPTION
**Pull request by rishabh-arya95**
Adding the iterative tree walker implementation for GO, inspired by the java iterative walker
https://github.com/antlr/antlr4/pull/1231

### CODE REVIEW

**Comment by parrt** [comment]
Now that I have merged the update to the Go Target made by @jimidle maybe you guys can take another look to ensure it is compatible.

**Comment by jimidle** [comment]
I will take a look at this after 4.11.0 is released. Right now, I do not know if anyone has attempted this, but it is probably best done with generics and current tree stuff does not use generics... yet.

**Comment by jimidle** [comment]
@parrt Would you please assign this to me, or label it with Go.

**Comment by jimidle** [comment]
This code now needs to be moved in to the /v4 version of the go runtime. I have not tried this and there are no tests, but as it is a new file, it seems safe enough. We can merge this one and I can copy it to the v4 version.

**Comment by parrt** [comment]
@jimidle so I should merge this one and then you will copy it to v4?

**Comment by jimidle** [comment]
Yes. Let’s do that. The OP hasn’t resubmitted. It’s a small addition, so I
can just do it.

**Comment by parrt** [comment]
done @jimidle !

**Pull request merged**
