### PR TITLE
issue#2573: Initial dependency and profile management for JDK 11

### PR DESCRIPTION
**Pull request by nbuso**
Allow to build the library at JDK 11 compliance. Unfortunately I don't have all the languages environments set up to complete all the tests.
Please have a look and let me know if I need to make changes

### CODE REVIEW

**Comment by nbuso** [comment]
Can a JDK 11 be added in Travis configuration to review this pull request? I changed project adding profiles for JDK 8 and 11, travis should run twice one with JDK 8 and one with JDK 11

**Comment by ericvergnaud** [comment]
Hi,
what problem are you trying to solve? Jdk11 can run classes in Jdk7 format, so why do you need to recompile?

**Comment by nbuso** [comment]
@ericvergnaud you are right, I was trying to get rid of this warning:
[WARNING] Supported source version 'RELEASE_8' from annotation processor 'org.antlr.v4.runtime.misc.RuleDependencyProcessor' less than -source '11'
[WARNING] Supported source version 'RELEASE_8' from annotation processor 'org.antlr.v4.runtime.misc.NullUsageProcessor' less than -source '11'

but was compiling against com.tunnelvisionlabs:antlr4:4.7.3 and I didn't these classes completely disappeared in the original antlr4 repository.

Close now

**Comment by sharwell** [comment]
@nbuso That package is part of https://github.com/tunnelvisionlabs/antlr4.

**Pull request closed without merging**
