### PR TITLE
[Swift] Changes to Mutex-es to guard the staticly shared [DFA]

### LINKED ISSUE #3271: Swift Target Crashes with Multi-Threading
- [x] I am not submitting a question on how to use ANTLR; instead, go to [antlr4-discussion google group](https://groups.google.com/forum/#!forum/antlr-discussion) or ask at [stackoverflow](http://stackoverflow.com/questions/tagged/antlr4)
- [x] I have done a search of the existing issues to make sure I'm not sending in a duplicate

# Reproducing Error

Running via Xcode for iOS 13
Project Swift Version: 4.2
Compiled swift target from 4.9.2 release

## Grammar
```
grammar math;

NUMBER : [0-9] ;
WS : [ \r\n\t] + -> skip ;

operation : l=NUMBER op='+' r=NUMBER  ;
```

## Swift Code
```swift
for _ in 0...10 {
    DispatchQueue.global().async {
        let chars = ANTLRInputStream("1+1")
        let lexer = mathLexer(chars)
        
        let tokenStream = CommonTokenStream(lexer)
        let parser = try! mathParser(tokenStream)
        
        let node = try? parser.operation()
    }
}
```

# What Happened

The program crashes in LexerATNSimulator.swift on line 721 with EXC_BAD_ACCESS. There was a double free at some point in the stack.

Any help is greatly appreciated! Hopefully this is just user error.

### PR DESCRIPTION
**Pull request by martinvw**
Request for review: @janyou, @ewanmellor, @hanjoes, @rmehta33 

By sharing the mutex in the same way as the DFA array it becomes possible to run in parallel

Fixes #3271

### CODE REVIEW

**Comment by ericvergnaud** [comment]
Hi,

this sounds useful but I'm not sure your test is 'hungry' enough to prove that it works.
there is a genuine possibility that the first iteration ends before the second one starts,
plus they both generate the same DFA enrichment so might be missing important scenarios.
May I suggest that you try parsing longer and different inputs in parallel such that the test does proves that it works in the problematic scenarios too ?

**Comment by martinvw** [comment]
Without my changes this test always fails and with it always succeeds. I do believe we should aim for a bit more code coverage but I doubt that multiple or much more complex grammar is needed, however a longer text of course make sense.

I do not completely understand the second part of your comment, I might need a hint about that one.

Thanks for your time!

**Comment by ericvergnaud** [comment]
The reason a mutex is required is because originally the DFA is empty and gets populated gradually as the runtimes bumps into new grammar fragments. No mutex is required for reading.
Since the current test always parses the same expression, the DFA only gets populated once with a single exception where 2 threads are populating it the same way at the same time (which you seem ti have encountered)
In real situations It’s much more likely that 2 threads will populate it in different ways, thus going through slightly different code paths, hence my ask that you use longer and different expressions 

Envoyé de mon iPhone

**Comment by martinvw** [comment]
Thanks for the explanation!

That makes a lot of sense, thanks for insight. I’ll try to look into it
later this week.

Could you also shed some light on when the ParserATNSimulator code path is
triggered? I do believe my current tests might not cover this as well.

**Comment by martinvw** [comment]
@ericvergnaud I updated the test with a bit more complex expressions, do you think this would be enough:

https://github.com/antlr/antlr4/pull/3276/files#diff-3a18ea2989cadcaf86cc213acaeeac01f23da4167ce1a7031bd19ff3aa27ef86R16-R38

I check the call trace and I see that we actually touch all the changed files with the current test, so that looks good.

**Comment by ericvergnaud** [comment]
@parrt blessed, the failing test is unrelated and is fixed through another PR

**Comment by martinvw** [comment]
Thanks!

**Pull request merged**
