### PR TITLE
Fix .interp file parsing test for the Java runtime.

### PR DESCRIPTION
**Pull request by parrt**
Also includes separating the generation of the .interp file from writing it out so that we can use both independently.

Still working on the Python part.

### CODE REVIEW

**Comment by parrt** [comment]
All right I'm going to merge this because a not sure what to do about the Python runtime.  I have a number of  unit tests for the Java API token stream rewriter... maybe this needs to be ported to Python instead of using these submitted by @youkaichao ?

**Comment by ericvergnaud** [comment]
Each runtime may already have its own test suite, and some already have i.e. Python, JavaScript...
As per API testing, I think it's a good idea to make those tests visible

**Comment by parrt** [comment]
Ah. Yes, Swift has them. JavaScript too. Go does but not in separate dir. has `testing_assert_test.go` etc... Dart has one. Csharp tests 2 bug fixes.

**Comment by parrt** [comment]
Given that, I'll merge so we can move forward.

**Comment by KvanTTT** [comment]
Does it make sense to delete `*.interp` files after your changes?

**Comment by parrt** [comment]
OH! Yes, it does make sense. shoot. i'll do and just push to upstream master

**Comment by parrt** [comment]
Done.

**Pull request merged**
