### PR TITLE
CMake build fixes for Visual Studio

### PR DESCRIPTION
**Pull request by gendalph**
Remove unsupported cmd line options (gcc).
Disable tons of  warning for DLL.
Enable parallel build.

----------------------------------------------
cmake 3.9.2
----------------------------------------------
Microsoft Visual Studio Community 2017 Preview (2)
Version 15.4.0 Preview 1.0

Installed Version: Community

Visual C++ 2017   00369-60000-00001-AA769
Microsoft Visual C++ 2017

### CODE REVIEW

**Comment by parrt** [comment]
Ooops. Please sign the contributors file; otherwise I have to back this out.

**Comment by parrt** [comment]
actually I will back out and then you can make a new PR with the sig.  sorry for the hassles.

**Comment by gendalph** [comment]
https://github.com/antlr/antlr4/pull/2083

**Comment by parrt** [comment]
@gendalph Can you help me out by making a new PR with these changes? I can't figure out the git to revert the revert :) thanks!

**Comment by gendalph** [comment]
+ fix build shared demo

**Pull request merged**
